// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type PostalAdArea struct {
	PostalAdAreaID        pgtype.UUID        `db:"postal_ad_area_id" json:"postal_ad_area_id"`
	PostalAdAreaCode      string             `db:"postal_ad_area_code" json:"postal_ad_area_code"`
	PostalAdAreaNameFi    string             `db:"postal_ad_area_name_fi" json:"postal_ad_area_name_fi"`
	PostalAdAreaNameSv    *string            `db:"postal_ad_area_name_sv" json:"postal_ad_area_name_sv"`
	PostalAdAreaCreatedAt pgtype.Timestamptz `db:"postal_ad_area_created_at" json:"postal_ad_area_created_at"`
	PostalAdAreaUpdatedAt pgtype.Timestamptz `db:"postal_ad_area_updated_at" json:"postal_ad_area_updated_at"`
}

type PostalMunicipality struct {
	PostalMunicipalityID                pgtype.UUID        `db:"postal_municipality_id" json:"postal_municipality_id"`
	PostalMunicipalityCode              string             `db:"postal_municipality_code" json:"postal_municipality_code"`
	PostalMunicipalityNameFi            string             `db:"postal_municipality_name_fi" json:"postal_municipality_name_fi"`
	PostalMunicipalityNameSv            *string            `db:"postal_municipality_name_sv" json:"postal_municipality_name_sv"`
	PostalMunicipalityLanguageRatioCode *string            `db:"postal_municipality_language_ratio_code" json:"postal_municipality_language_ratio_code"`
	PostalMunicipalityCreatedAt         pgtype.Timestamptz `db:"postal_municipality_created_at" json:"postal_municipality_created_at"`
	PostalMunicipalityUpdatedAt         pgtype.Timestamptz `db:"postal_municipality_updated_at" json:"postal_municipality_updated_at"`
}

type PostalPostalCode struct {
	PostalPostalCodeID        pgtype.UUID        `db:"postal_postal_code_id" json:"postal_postal_code_id"`
	PostalPostalCodeDate      time.Time          `db:"postal_postal_code_date" json:"postal_postal_code_date"`
	PostalPostalCodeCode      string             `db:"postal_postal_code_code" json:"postal_postal_code_code"`
	PostalPostalCodeNameFi    string             `db:"postal_postal_code_name_fi" json:"postal_postal_code_name_fi"`
	PostalPostalCodeNameSv    *string            `db:"postal_postal_code_name_sv" json:"postal_postal_code_name_sv"`
	PostalPostalCodeAbbrFi    *string            `db:"postal_postal_code_abbr_fi" json:"postal_postal_code_abbr_fi"`
	PostalPostalCodeAbbrSv    *string            `db:"postal_postal_code_abbr_sv" json:"postal_postal_code_abbr_sv"`
	PostalPostalCodeValidFrom *time.Time         `db:"postal_postal_code_valid_from" json:"postal_postal_code_valid_from"`
	PostalPostalCodeTypeCode  *string            `db:"postal_postal_code_type_code" json:"postal_postal_code_type_code"`
	PostalAdAreaID            pgtype.UUID        `db:"postal_ad_area_id" json:"postal_ad_area_id"`
	PostalMunicipalityID      pgtype.UUID        `db:"postal_municipality_id" json:"postal_municipality_id"`
	PostalPostalCodeCreatedAt pgtype.Timestamptz `db:"postal_postal_code_created_at" json:"postal_postal_code_created_at"`
	PostalPostalCodeUpdatedAt pgtype.Timestamptz `db:"postal_postal_code_updated_at" json:"postal_postal_code_updated_at"`
}
