// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertPostalAdAreasBulk = `-- name: UpsertPostalAdAreasBulk :many
INSERT INTO public.postal_ad_areas (
    postal_ad_area_code,
    postal_ad_area_name_fi,
    postal_ad_area_name_sv,
    postal_ad_area_created_at,
    postal_ad_area_updated_at
)
SELECT
    codes,
    names_fi,
    NULLIF(names_sv, ''),
    now(),
    now()
FROM unnest(
    $1::text[],
    $2::text[],
    $3::text[]
) AS t(codes, names_fi, names_sv)
ON CONFLICT (postal_ad_area_code) DO UPDATE
SET postal_ad_area_name_fi = EXCLUDED.postal_ad_area_name_fi,
    postal_ad_area_name_sv = EXCLUDED.postal_ad_area_name_sv,
    postal_ad_area_updated_at = now()
RETURNING postal_ad_area_id, postal_ad_area_code, postal_ad_area_name_fi, postal_ad_area_name_sv, postal_ad_area_created_at, postal_ad_area_updated_at
`

type UpsertPostalAdAreasBulkParams struct {
	Codes   []string `db:"codes" json:"codes"`
	NamesFi []string `db:"names_fi" json:"names_fi"`
	NamesSv []string `db:"names_sv" json:"names_sv"`
}

// Ad Areas
func (q *Queries) UpsertPostalAdAreasBulk(ctx context.Context, arg *UpsertPostalAdAreasBulkParams) ([]PostalAdArea, error) {
	rows, err := q.db.Query(ctx, upsertPostalAdAreasBulk, arg.Codes, arg.NamesFi, arg.NamesSv)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostalAdArea{}
	for rows.Next() {
		var i PostalAdArea
		if err := rows.Scan(
			&i.PostalAdAreaID,
			&i.PostalAdAreaCode,
			&i.PostalAdAreaNameFi,
			&i.PostalAdAreaNameSv,
			&i.PostalAdAreaCreatedAt,
			&i.PostalAdAreaUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPostalMunicipalitiesBulk = `-- name: UpsertPostalMunicipalitiesBulk :many
INSERT INTO public.postal_municipalities (
    postal_municipality_code,
    postal_municipality_name_fi,
    postal_municipality_name_sv,
    postal_municipality_language_ratio_code,
    postal_municipality_created_at,
    postal_municipality_updated_at
)
SELECT
    codes,
    names_fi,
    NULLIF(names_sv, ''),
    NULLIF(language_ratio_codes, ''),
    now(),
    now()
FROM unnest(
    $1::text[],
    $2::text[],
    $3::text[],
    $4::text[]
) AS t(codes, names_fi, names_sv, language_ratio_codes)
ON CONFLICT (postal_municipality_code) DO UPDATE
SET postal_municipality_name_fi = EXCLUDED.postal_municipality_name_fi,
    postal_municipality_name_sv = EXCLUDED.postal_municipality_name_sv,
    postal_municipality_language_ratio_code = EXCLUDED.postal_municipality_language_ratio_code,
    postal_municipality_updated_at = now()
RETURNING postal_municipality_id, postal_municipality_code, postal_municipality_name_fi, postal_municipality_name_sv, postal_municipality_language_ratio_code, postal_municipality_created_at, postal_municipality_updated_at
`

type UpsertPostalMunicipalitiesBulkParams struct {
	Codes              []string `db:"codes" json:"codes"`
	NamesFi            []string `db:"names_fi" json:"names_fi"`
	NamesSv            []string `db:"names_sv" json:"names_sv"`
	LanguageRatioCodes []string `db:"language_ratio_codes" json:"language_ratio_codes"`
}

// Municipalities
func (q *Queries) UpsertPostalMunicipalitiesBulk(ctx context.Context, arg *UpsertPostalMunicipalitiesBulkParams) ([]PostalMunicipality, error) {
	rows, err := q.db.Query(ctx, upsertPostalMunicipalitiesBulk,
		arg.Codes,
		arg.NamesFi,
		arg.NamesSv,
		arg.LanguageRatioCodes,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PostalMunicipality{}
	for rows.Next() {
		var i PostalMunicipality
		if err := rows.Scan(
			&i.PostalMunicipalityID,
			&i.PostalMunicipalityCode,
			&i.PostalMunicipalityNameFi,
			&i.PostalMunicipalityNameSv,
			&i.PostalMunicipalityLanguageRatioCode,
			&i.PostalMunicipalityCreatedAt,
			&i.PostalMunicipalityUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPostalPostalCodesBulk = `-- name: UpsertPostalPostalCodesBulk :execrows
INSERT INTO public.postal_postal_codes (
    postal_postal_code_date,
    postal_postal_code_code,
    postal_postal_code_name_fi,
    postal_postal_code_name_sv,
    postal_postal_code_abbr_fi,
    postal_postal_code_abbr_sv,
    postal_postal_code_valid_from,
    postal_postal_code_type_code,
    postal_ad_area_id,
    postal_municipality_id,
    postal_postal_code_created_at,
    postal_postal_code_updated_at
)
SELECT
    dates,
    codes,
    names_fi,
    NULLIF(names_sv, ''),
    NULLIF(abbrs_fi, ''),
    NULLIF(abbrs_sv, ''),
    valids_from,
    NULLIF(type_codes, ''),
    ad_area_ids,
    municipality_ids,
    now(),
    now()
FROM unnest(
    $1::date[],
    $2::text[],
    $3::text[],
    $4::text[],
    $5::text[],
    $6::text[],
    $7::date[],
    $8::text[],
    $9::uuid[],
    $10::uuid[]
) AS t(
    dates,
    codes,
    names_fi,
    names_sv,
    abbrs_fi,
    abbrs_sv,
    valids_from,
    type_codes,
    ad_area_ids,
    municipality_ids
)
ON CONFLICT (postal_postal_code_code) DO UPDATE
SET postal_postal_code_date = EXCLUDED.postal_postal_code_date,
    postal_postal_code_name_fi = EXCLUDED.postal_postal_code_name_fi,
    postal_postal_code_name_sv = EXCLUDED.postal_postal_code_name_sv,
    postal_postal_code_abbr_fi = EXCLUDED.postal_postal_code_abbr_fi,
    postal_postal_code_abbr_sv = EXCLUDED.postal_postal_code_abbr_sv,
    postal_postal_code_valid_from = EXCLUDED.postal_postal_code_valid_from,
    postal_postal_code_type_code = EXCLUDED.postal_postal_code_type_code,
    postal_ad_area_id = EXCLUDED.postal_ad_area_id,
    postal_municipality_id = EXCLUDED.postal_municipality_id,
    postal_postal_code_updated_at = now()
`

type UpsertPostalPostalCodesBulkParams struct {
	Dates           []time.Time   `db:"dates" json:"dates"`
	Codes           []string      `db:"codes" json:"codes"`
	NamesFi         []string      `db:"names_fi" json:"names_fi"`
	NamesSv         []string      `db:"names_sv" json:"names_sv"`
	AbbrsFi         []string      `db:"abbrs_fi" json:"abbrs_fi"`
	AbbrsSv         []string      `db:"abbrs_sv" json:"abbrs_sv"`
	ValidsFrom      []time.Time   `db:"valids_from" json:"valids_from"`
	TypeCodes       []string      `db:"type_codes" json:"type_codes"`
	AdAreaIds       []pgtype.UUID `db:"ad_area_ids" json:"ad_area_ids"`
	MunicipalityIds []pgtype.UUID `db:"municipality_ids" json:"municipality_ids"`
}

// Postal Codes
func (q *Queries) UpsertPostalPostalCodesBulk(ctx context.Context, arg *UpsertPostalPostalCodesBulkParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertPostalPostalCodesBulk,
		arg.Dates,
		arg.Codes,
		arg.NamesFi,
		arg.NamesSv,
		arg.AbbrsFi,
		arg.AbbrsSv,
		arg.ValidsFrom,
		arg.TypeCodes,
		arg.AdAreaIds,
		arg.MunicipalityIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
