version: "3"

tasks:
  dev:
    desc: Run the server with automatic reload on source/.env changes
    cmds:
      - reflex -r '\.go$' -r 'go\.(mod|sum)$' -r '\.env$' -R vendor -- sh -c 'go run ./cmd/app'
    env:
      CGO_ENABLED: "0"

  db:new:
    desc: Create a new timestamped migration (NAME required)
    dotenv: [".env", ".env.local"]
    cmds:
      - sh -c 'cd db/migrations && tern new {{.NAME}}'

  db:up:
    desc: Apply all pending migrations to the latest version
    dotenv: [".env", ".env.local"]
    cmds:
      - sh -c 'cd db/migrations && tern migrate'

  db:status:
    desc: Show current migration state
    dotenv: [".env", ".env.local"]
    cmds:
      - sh -c 'cd db/migrations && tern status'

  sqlc:
    desc: Generate type-safe Go code from SQL queries
    dotenv: [".env", ".env.local"]
    cmds:
      - sqlc generate -f sqlc.yaml
    sources:
      - db/schema/**/*.sql
      - db/queries/**/*.sql
    generates:
      - internal/db/**/*
