version: "3"

tasks:
  dev:
    desc: Run the server with automatic reload on source/.env changes
    cmds:
      - reflex --regex='\.go$' --decoration=none --start-service -- sh -c 'go run ./cmd'
    env:
      CGO_ENABLED: "0"

  db:new:
    desc: Create a new timestamped migration (NAME required)
    dotenv: ["../../.env"]
    dir: db/migrations
    cmds:
      - tern new {{.NAME}}

  db:migrate:
    desc: Apply all pending migrations to the latest version
    dotenv: ["../../.env"]
    dir: db/migrations
    cmds:
      - tern migrate

  db:status:
    desc: Show current migration state
    dotenv: ["../../.env"]
    dir: db/migrations
    cmds:
      - tern status

  db:generate:
    desc: Generate type-safe Go code from SQL queries
    dotenv: [".env", ".env.local"]
    cmds:
      - sqlc generate -f sqlc.yaml
    sources:
      - db/schema/**/*.sql
      - db/queries/**/*.sql
    generates:
      - internal/db/**/*
