version: "3"

dotenv: [".env", "./backend/.env"]

includes:
  backend:
    taskfile: ./backend/Taskfile.yml
    dir: ./backend
  client:
    taskfile: ./koditon/Taskfile.yml
    dir: ./koditon

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list
