root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd"
bin = "./tmp/main"
delay = 300
exclude_dir = ["tmp", "vendor", "testdata", "db/migrations", "scripts", ".cache", ".gocache", ".task"]
exclude_regex = ["_test\\.go"]
include_dir = ["cmd", "internal", "db"]
include_ext = ["go", "sql", "tpl", "tmpl", "html", "yaml", "yml", "json"]
kill_delay = "500ms"
send_interrupt = true
stop_on_error = true
