[database]
host = {{ env "DB_HOST" | default "localhost" }}
port = {{ env "DB_PORT" | default "5432" }}
database = {{ env "DB_NAME" | default "koditon" }}
user = {{ env "DB_USER" | default "postgres" }}
password = {{ env "DB_PASSWORD" | default "postgres" }}
version_table = schema_migrations
