// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteShortcutToken = `-- name: DeleteShortcutToken :exec
DELETE FROM public.shortcut_tokens
WHERE shortcut_tokens_cuid = $1
`

func (q *Queries) DeleteShortcutToken(ctx context.Context, shortcutTokensCuid string) error {
	_, err := q.db.Exec(ctx, deleteShortcutToken, shortcutTokensCuid)
	return err
}

const getAllValidShortcutTokens = `-- name: GetAllValidShortcutTokens :many
SELECT shortcut_tokens_id, shortcut_tokens_cuid, shortcut_tokens_token, shortcut_tokens_loaded, shortcut_tokens_created_at, shortcut_tokens_updated_at, shortcut_tokens_expires_at FROM public.shortcut_tokens
ORDER BY shortcut_tokens_created_at DESC
`

func (q *Queries) GetAllValidShortcutTokens(ctx context.Context) ([]ShortcutToken, error) {
	rows, err := q.db.Query(ctx, getAllValidShortcutTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShortcutToken{}
	for rows.Next() {
		var i ShortcutToken
		if err := rows.Scan(
			&i.ShortcutTokensID,
			&i.ShortcutTokensCuid,
			&i.ShortcutTokensToken,
			&i.ShortcutTokensLoaded,
			&i.ShortcutTokensCreatedAt,
			&i.ShortcutTokensUpdatedAt,
			&i.ShortcutTokensExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShortcutAdByID = `-- name: GetShortcutAdByID :one
SELECT shortcut_ads_id, shortcut_ads_url, shortcut_ads_type, shortcut_ads_first_seen_at, shortcut_ads_last_seen_at, shortcut_ads_data, shortcut_ads_updated_at, shortcut_ads_building_id FROM public.shortcut_ads
WHERE shortcut_ads_id = $1
`

func (q *Queries) GetShortcutAdByID(ctx context.Context, shortcutAdsID int64) (ShortcutAd, error) {
	row := q.db.QueryRow(ctx, getShortcutAdByID, shortcutAdsID)
	var i ShortcutAd
	err := row.Scan(
		&i.ShortcutAdsID,
		&i.ShortcutAdsUrl,
		&i.ShortcutAdsType,
		&i.ShortcutAdsFirstSeenAt,
		&i.ShortcutAdsLastSeenAt,
		&i.ShortcutAdsData,
		&i.ShortcutAdsUpdatedAt,
		&i.ShortcutAdsBuildingID,
	)
	return i, err
}

const getShortcutBuildingByExternalID = `-- name: GetShortcutBuildingByExternalID :one
SELECT shortcut_buildings_id, shortcut_buildings_external_id, shortcut_buildings_building_id, shortcut_buildings_building_type, shortcut_buildings_building_subtype, shortcut_buildings_construction_year, shortcut_buildings_floor_count, shortcut_buildings_apartment_count, shortcut_buildings_heating_system, shortcut_buildings_building_material, shortcut_buildings_plot_type, shortcut_buildings_wall_structure, shortcut_buildings_heat_source, shortcut_buildings_has_elevator, shortcut_buildings_has_sauna, shortcut_buildings_latitude, shortcut_buildings_longitude, shortcut_buildings_additional_addresses, shortcut_buildings_url, shortcut_buildings_created_at, shortcut_buildings_updated_at, shortcut_buildings_address, shortcut_buildings_processed_at, shortcut_buildings_page_not_found, shortcut_buildings_frame_construction_method, shortcut_buildings_housing_company, shortcut_buildings_geom FROM public.shortcut_buildings
WHERE shortcut_buildings_external_id = $1
`

func (q *Queries) GetShortcutBuildingByExternalID(ctx context.Context, shortcutBuildingsExternalID int64) (ShortcutBuilding, error) {
	row := q.db.QueryRow(ctx, getShortcutBuildingByExternalID, shortcutBuildingsExternalID)
	var i ShortcutBuilding
	err := row.Scan(
		&i.ShortcutBuildingsID,
		&i.ShortcutBuildingsExternalID,
		&i.ShortcutBuildingsBuildingID,
		&i.ShortcutBuildingsBuildingType,
		&i.ShortcutBuildingsBuildingSubtype,
		&i.ShortcutBuildingsConstructionYear,
		&i.ShortcutBuildingsFloorCount,
		&i.ShortcutBuildingsApartmentCount,
		&i.ShortcutBuildingsHeatingSystem,
		&i.ShortcutBuildingsBuildingMaterial,
		&i.ShortcutBuildingsPlotType,
		&i.ShortcutBuildingsWallStructure,
		&i.ShortcutBuildingsHeatSource,
		&i.ShortcutBuildingsHasElevator,
		&i.ShortcutBuildingsHasSauna,
		&i.ShortcutBuildingsLatitude,
		&i.ShortcutBuildingsLongitude,
		&i.ShortcutBuildingsAdditionalAddresses,
		&i.ShortcutBuildingsUrl,
		&i.ShortcutBuildingsCreatedAt,
		&i.ShortcutBuildingsUpdatedAt,
		&i.ShortcutBuildingsAddress,
		&i.ShortcutBuildingsProcessedAt,
		&i.ShortcutBuildingsPageNotFound,
		&i.ShortcutBuildingsFrameConstructionMethod,
		&i.ShortcutBuildingsHousingCompany,
		&i.ShortcutBuildingsGeom,
	)
	return i, err
}

const getShortcutBuildingByID = `-- name: GetShortcutBuildingByID :one
SELECT shortcut_buildings_id, shortcut_buildings_external_id, shortcut_buildings_building_id, shortcut_buildings_building_type, shortcut_buildings_building_subtype, shortcut_buildings_construction_year, shortcut_buildings_floor_count, shortcut_buildings_apartment_count, shortcut_buildings_heating_system, shortcut_buildings_building_material, shortcut_buildings_plot_type, shortcut_buildings_wall_structure, shortcut_buildings_heat_source, shortcut_buildings_has_elevator, shortcut_buildings_has_sauna, shortcut_buildings_latitude, shortcut_buildings_longitude, shortcut_buildings_additional_addresses, shortcut_buildings_url, shortcut_buildings_created_at, shortcut_buildings_updated_at, shortcut_buildings_address, shortcut_buildings_processed_at, shortcut_buildings_page_not_found, shortcut_buildings_frame_construction_method, shortcut_buildings_housing_company, shortcut_buildings_geom FROM public.shortcut_buildings
WHERE shortcut_buildings_id = $1
`

func (q *Queries) GetShortcutBuildingByID(ctx context.Context, shortcutBuildingsID pgtype.UUID) (ShortcutBuilding, error) {
	row := q.db.QueryRow(ctx, getShortcutBuildingByID, shortcutBuildingsID)
	var i ShortcutBuilding
	err := row.Scan(
		&i.ShortcutBuildingsID,
		&i.ShortcutBuildingsExternalID,
		&i.ShortcutBuildingsBuildingID,
		&i.ShortcutBuildingsBuildingType,
		&i.ShortcutBuildingsBuildingSubtype,
		&i.ShortcutBuildingsConstructionYear,
		&i.ShortcutBuildingsFloorCount,
		&i.ShortcutBuildingsApartmentCount,
		&i.ShortcutBuildingsHeatingSystem,
		&i.ShortcutBuildingsBuildingMaterial,
		&i.ShortcutBuildingsPlotType,
		&i.ShortcutBuildingsWallStructure,
		&i.ShortcutBuildingsHeatSource,
		&i.ShortcutBuildingsHasElevator,
		&i.ShortcutBuildingsHasSauna,
		&i.ShortcutBuildingsLatitude,
		&i.ShortcutBuildingsLongitude,
		&i.ShortcutBuildingsAdditionalAddresses,
		&i.ShortcutBuildingsUrl,
		&i.ShortcutBuildingsCreatedAt,
		&i.ShortcutBuildingsUpdatedAt,
		&i.ShortcutBuildingsAddress,
		&i.ShortcutBuildingsProcessedAt,
		&i.ShortcutBuildingsPageNotFound,
		&i.ShortcutBuildingsFrameConstructionMethod,
		&i.ShortcutBuildingsHousingCompany,
		&i.ShortcutBuildingsGeom,
	)
	return i, err
}

const getShortcutBuildingListingsByBuildingID = `-- name: GetShortcutBuildingListingsByBuildingID :many
SELECT shortcut_building_listings_id, shortcut_building_listings_building_id, shortcut_building_listings_layout, shortcut_building_listings_size, shortcut_building_listings_price, shortcut_building_listings_price_per_sqm, shortcut_building_listings_deleted_at, shortcut_building_listings_created_at, shortcut_building_listings_updated_at, shortcut_building_listings_marketing_time, shortcut_building_listings_idx FROM public.shortcut_building_listings
WHERE shortcut_building_listings_building_id = $1
ORDER BY shortcut_building_listings_created_at DESC
`

func (q *Queries) GetShortcutBuildingListingsByBuildingID(ctx context.Context, shortcutBuildingListingsBuildingID pgtype.UUID) ([]ShortcutBuildingListing, error) {
	rows, err := q.db.Query(ctx, getShortcutBuildingListingsByBuildingID, shortcutBuildingListingsBuildingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShortcutBuildingListing{}
	for rows.Next() {
		var i ShortcutBuildingListing
		if err := rows.Scan(
			&i.ShortcutBuildingListingsID,
			&i.ShortcutBuildingListingsBuildingID,
			&i.ShortcutBuildingListingsLayout,
			&i.ShortcutBuildingListingsSize,
			&i.ShortcutBuildingListingsPrice,
			&i.ShortcutBuildingListingsPricePerSqm,
			&i.ShortcutBuildingListingsDeletedAt,
			&i.ShortcutBuildingListingsCreatedAt,
			&i.ShortcutBuildingListingsUpdatedAt,
			&i.ShortcutBuildingListingsMarketingTime,
			&i.ShortcutBuildingListingsIdx,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShortcutBuildingRentalsByBuildingID = `-- name: GetShortcutBuildingRentalsByBuildingID :many
SELECT shortcut_building_rentals_id, shortcut_building_rentals_building_id, shortcut_building_rentals_layout, shortcut_building_rentals_size, shortcut_building_rentals_price, shortcut_building_rentals_deleted_at, shortcut_building_rentals_created_at, shortcut_building_rentals_updated_at, shortcut_building_rentals_marketing_time, shortcut_building_rentals_idx FROM public.shortcut_building_rentals
WHERE shortcut_building_rentals_building_id = $1
ORDER BY shortcut_building_rentals_created_at DESC
`

func (q *Queries) GetShortcutBuildingRentalsByBuildingID(ctx context.Context, shortcutBuildingRentalsBuildingID pgtype.UUID) ([]ShortcutBuildingRental, error) {
	rows, err := q.db.Query(ctx, getShortcutBuildingRentalsByBuildingID, shortcutBuildingRentalsBuildingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShortcutBuildingRental{}
	for rows.Next() {
		var i ShortcutBuildingRental
		if err := rows.Scan(
			&i.ShortcutBuildingRentalsID,
			&i.ShortcutBuildingRentalsBuildingID,
			&i.ShortcutBuildingRentalsLayout,
			&i.ShortcutBuildingRentalsSize,
			&i.ShortcutBuildingRentalsPrice,
			&i.ShortcutBuildingRentalsDeletedAt,
			&i.ShortcutBuildingRentalsCreatedAt,
			&i.ShortcutBuildingRentalsUpdatedAt,
			&i.ShortcutBuildingRentalsMarketingTime,
			&i.ShortcutBuildingRentalsIdx,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidShortcutToken = `-- name: GetValidShortcutToken :one
SELECT shortcut_tokens_id, shortcut_tokens_cuid, shortcut_tokens_token, shortcut_tokens_loaded, shortcut_tokens_created_at, shortcut_tokens_updated_at, shortcut_tokens_expires_at FROM public.shortcut_tokens
ORDER BY shortcut_tokens_created_at DESC
LIMIT 1
`

func (q *Queries) GetValidShortcutToken(ctx context.Context) (ShortcutToken, error) {
	row := q.db.QueryRow(ctx, getValidShortcutToken)
	var i ShortcutToken
	err := row.Scan(
		&i.ShortcutTokensID,
		&i.ShortcutTokensCuid,
		&i.ShortcutTokensToken,
		&i.ShortcutTokensLoaded,
		&i.ShortcutTokensCreatedAt,
		&i.ShortcutTokensUpdatedAt,
		&i.ShortcutTokensExpiresAt,
	)
	return i, err
}

const insertShortcutToken = `-- name: InsertShortcutToken :one
INSERT INTO public.shortcut_tokens (
    shortcut_tokens_cuid,
    shortcut_tokens_token,
    shortcut_tokens_loaded,
    shortcut_tokens_expires_at
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (shortcut_tokens_cuid) DO UPDATE SET
    shortcut_tokens_token = EXCLUDED.shortcut_tokens_token,
    shortcut_tokens_loaded = EXCLUDED.shortcut_tokens_loaded,
    shortcut_tokens_expires_at = EXCLUDED.shortcut_tokens_expires_at,
    shortcut_tokens_updated_at = NOW()
RETURNING shortcut_tokens_id, shortcut_tokens_cuid, shortcut_tokens_token, shortcut_tokens_loaded, shortcut_tokens_created_at, shortcut_tokens_updated_at, shortcut_tokens_expires_at
`

type InsertShortcutTokenParams struct {
	ShortcutTokensCuid      string    `db:"shortcut_tokens_cuid" json:"shortcut_tokens_cuid"`
	ShortcutTokensToken     string    `db:"shortcut_tokens_token" json:"shortcut_tokens_token"`
	ShortcutTokensLoaded    string    `db:"shortcut_tokens_loaded" json:"shortcut_tokens_loaded"`
	ShortcutTokensExpiresAt time.Time `db:"shortcut_tokens_expires_at" json:"shortcut_tokens_expires_at"`
}

func (q *Queries) InsertShortcutToken(ctx context.Context, arg *InsertShortcutTokenParams) (ShortcutToken, error) {
	row := q.db.QueryRow(ctx, insertShortcutToken,
		arg.ShortcutTokensCuid,
		arg.ShortcutTokensToken,
		arg.ShortcutTokensLoaded,
		arg.ShortcutTokensExpiresAt,
	)
	var i ShortcutToken
	err := row.Scan(
		&i.ShortcutTokensID,
		&i.ShortcutTokensCuid,
		&i.ShortcutTokensToken,
		&i.ShortcutTokensLoaded,
		&i.ShortcutTokensCreatedAt,
		&i.ShortcutTokensUpdatedAt,
		&i.ShortcutTokensExpiresAt,
	)
	return i, err
}

const listShortcutAds = `-- name: ListShortcutAds :many
SELECT shortcut_ads_id, shortcut_ads_url, shortcut_ads_type, shortcut_ads_first_seen_at, shortcut_ads_last_seen_at, shortcut_ads_data, shortcut_ads_updated_at, shortcut_ads_building_id FROM public.shortcut_ads
ORDER BY shortcut_ads_last_seen_at DESC
LIMIT $1 OFFSET $2
`

type ListShortcutAdsParams struct {
	Limit  int64 `db:"limit" json:"limit"`
	Offset int64 `db:"offset" json:"offset"`
}

func (q *Queries) ListShortcutAds(ctx context.Context, arg *ListShortcutAdsParams) ([]ShortcutAd, error) {
	rows, err := q.db.Query(ctx, listShortcutAds, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShortcutAd{}
	for rows.Next() {
		var i ShortcutAd
		if err := rows.Scan(
			&i.ShortcutAdsID,
			&i.ShortcutAdsUrl,
			&i.ShortcutAdsType,
			&i.ShortcutAdsFirstSeenAt,
			&i.ShortcutAdsLastSeenAt,
			&i.ShortcutAdsData,
			&i.ShortcutAdsUpdatedAt,
			&i.ShortcutAdsBuildingID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShortcutBuildings = `-- name: ListShortcutBuildings :many
SELECT shortcut_buildings_id, shortcut_buildings_external_id, shortcut_buildings_building_id, shortcut_buildings_building_type, shortcut_buildings_building_subtype, shortcut_buildings_construction_year, shortcut_buildings_floor_count, shortcut_buildings_apartment_count, shortcut_buildings_heating_system, shortcut_buildings_building_material, shortcut_buildings_plot_type, shortcut_buildings_wall_structure, shortcut_buildings_heat_source, shortcut_buildings_has_elevator, shortcut_buildings_has_sauna, shortcut_buildings_latitude, shortcut_buildings_longitude, shortcut_buildings_additional_addresses, shortcut_buildings_url, shortcut_buildings_created_at, shortcut_buildings_updated_at, shortcut_buildings_address, shortcut_buildings_processed_at, shortcut_buildings_page_not_found, shortcut_buildings_frame_construction_method, shortcut_buildings_housing_company, shortcut_buildings_geom FROM public.shortcut_buildings
ORDER BY shortcut_buildings_created_at DESC
LIMIT $1 OFFSET $2
`

type ListShortcutBuildingsParams struct {
	Limit  int64 `db:"limit" json:"limit"`
	Offset int64 `db:"offset" json:"offset"`
}

func (q *Queries) ListShortcutBuildings(ctx context.Context, arg *ListShortcutBuildingsParams) ([]ShortcutBuilding, error) {
	rows, err := q.db.Query(ctx, listShortcutBuildings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShortcutBuilding{}
	for rows.Next() {
		var i ShortcutBuilding
		if err := rows.Scan(
			&i.ShortcutBuildingsID,
			&i.ShortcutBuildingsExternalID,
			&i.ShortcutBuildingsBuildingID,
			&i.ShortcutBuildingsBuildingType,
			&i.ShortcutBuildingsBuildingSubtype,
			&i.ShortcutBuildingsConstructionYear,
			&i.ShortcutBuildingsFloorCount,
			&i.ShortcutBuildingsApartmentCount,
			&i.ShortcutBuildingsHeatingSystem,
			&i.ShortcutBuildingsBuildingMaterial,
			&i.ShortcutBuildingsPlotType,
			&i.ShortcutBuildingsWallStructure,
			&i.ShortcutBuildingsHeatSource,
			&i.ShortcutBuildingsHasElevator,
			&i.ShortcutBuildingsHasSauna,
			&i.ShortcutBuildingsLatitude,
			&i.ShortcutBuildingsLongitude,
			&i.ShortcutBuildingsAdditionalAddresses,
			&i.ShortcutBuildingsUrl,
			&i.ShortcutBuildingsCreatedAt,
			&i.ShortcutBuildingsUpdatedAt,
			&i.ShortcutBuildingsAddress,
			&i.ShortcutBuildingsProcessedAt,
			&i.ShortcutBuildingsPageNotFound,
			&i.ShortcutBuildingsFrameConstructionMethod,
			&i.ShortcutBuildingsHousingCompany,
			&i.ShortcutBuildingsGeom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnprocessedShortcutBuildings = `-- name: ListUnprocessedShortcutBuildings :many
SELECT shortcut_buildings_id, shortcut_buildings_external_id, shortcut_buildings_building_id, shortcut_buildings_building_type, shortcut_buildings_building_subtype, shortcut_buildings_construction_year, shortcut_buildings_floor_count, shortcut_buildings_apartment_count, shortcut_buildings_heating_system, shortcut_buildings_building_material, shortcut_buildings_plot_type, shortcut_buildings_wall_structure, shortcut_buildings_heat_source, shortcut_buildings_has_elevator, shortcut_buildings_has_sauna, shortcut_buildings_latitude, shortcut_buildings_longitude, shortcut_buildings_additional_addresses, shortcut_buildings_url, shortcut_buildings_created_at, shortcut_buildings_updated_at, shortcut_buildings_address, shortcut_buildings_processed_at, shortcut_buildings_page_not_found, shortcut_buildings_frame_construction_method, shortcut_buildings_housing_company, shortcut_buildings_geom FROM public.shortcut_buildings
WHERE shortcut_buildings_processed_at IS NULL AND shortcut_buildings_page_not_found = false
ORDER BY shortcut_buildings_created_at DESC
LIMIT $1
`

func (q *Queries) ListUnprocessedShortcutBuildings(ctx context.Context, limit int64) ([]ShortcutBuilding, error) {
	rows, err := q.db.Query(ctx, listUnprocessedShortcutBuildings, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShortcutBuilding{}
	for rows.Next() {
		var i ShortcutBuilding
		if err := rows.Scan(
			&i.ShortcutBuildingsID,
			&i.ShortcutBuildingsExternalID,
			&i.ShortcutBuildingsBuildingID,
			&i.ShortcutBuildingsBuildingType,
			&i.ShortcutBuildingsBuildingSubtype,
			&i.ShortcutBuildingsConstructionYear,
			&i.ShortcutBuildingsFloorCount,
			&i.ShortcutBuildingsApartmentCount,
			&i.ShortcutBuildingsHeatingSystem,
			&i.ShortcutBuildingsBuildingMaterial,
			&i.ShortcutBuildingsPlotType,
			&i.ShortcutBuildingsWallStructure,
			&i.ShortcutBuildingsHeatSource,
			&i.ShortcutBuildingsHasElevator,
			&i.ShortcutBuildingsHasSauna,
			&i.ShortcutBuildingsLatitude,
			&i.ShortcutBuildingsLongitude,
			&i.ShortcutBuildingsAdditionalAddresses,
			&i.ShortcutBuildingsUrl,
			&i.ShortcutBuildingsCreatedAt,
			&i.ShortcutBuildingsUpdatedAt,
			&i.ShortcutBuildingsAddress,
			&i.ShortcutBuildingsProcessedAt,
			&i.ShortcutBuildingsPageNotFound,
			&i.ShortcutBuildingsFrameConstructionMethod,
			&i.ShortcutBuildingsHousingCompany,
			&i.ShortcutBuildingsGeom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markShortcutBuildingPageNotFound = `-- name: MarkShortcutBuildingPageNotFound :exec
UPDATE public.shortcut_buildings
SET shortcut_buildings_page_not_found = true, shortcut_buildings_updated_at = CURRENT_TIMESTAMP
WHERE shortcut_buildings_id = $1
`

func (q *Queries) MarkShortcutBuildingPageNotFound(ctx context.Context, shortcutBuildingsID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markShortcutBuildingPageNotFound, shortcutBuildingsID)
	return err
}

const markShortcutBuildingProcessed = `-- name: MarkShortcutBuildingProcessed :exec
UPDATE public.shortcut_buildings
SET shortcut_buildings_processed_at = CURRENT_TIMESTAMP, shortcut_buildings_updated_at = CURRENT_TIMESTAMP
WHERE shortcut_buildings_id = $1
`

func (q *Queries) MarkShortcutBuildingProcessed(ctx context.Context, shortcutBuildingsID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markShortcutBuildingProcessed, shortcutBuildingsID)
	return err
}

const upsertShortcutAd = `-- name: UpsertShortcutAd :one
INSERT INTO public.shortcut_ads (
    shortcut_ads_id,
    shortcut_ads_url,
    shortcut_ads_type,
    shortcut_ads_data,
    shortcut_ads_building_id
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (shortcut_ads_id) DO UPDATE SET
    shortcut_ads_url = EXCLUDED.shortcut_ads_url,
    shortcut_ads_type = EXCLUDED.shortcut_ads_type,
    shortcut_ads_data = EXCLUDED.shortcut_ads_data,
    shortcut_ads_building_id = EXCLUDED.shortcut_ads_building_id,
    shortcut_ads_last_seen_at = now(),
    shortcut_ads_updated_at = CURRENT_TIMESTAMP
RETURNING shortcut_ads_id, shortcut_ads_url, shortcut_ads_type, shortcut_ads_first_seen_at, shortcut_ads_last_seen_at, shortcut_ads_data, shortcut_ads_updated_at, shortcut_ads_building_id
`

type UpsertShortcutAdParams struct {
	ShortcutAdsID         int64       `db:"shortcut_ads_id" json:"shortcut_ads_id"`
	ShortcutAdsUrl        string      `db:"shortcut_ads_url" json:"shortcut_ads_url"`
	ShortcutAdsType       string      `db:"shortcut_ads_type" json:"shortcut_ads_type"`
	ShortcutAdsData       []byte      `db:"shortcut_ads_data" json:"shortcut_ads_data"`
	ShortcutAdsBuildingID pgtype.UUID `db:"shortcut_ads_building_id" json:"shortcut_ads_building_id"`
}

func (q *Queries) UpsertShortcutAd(ctx context.Context, arg *UpsertShortcutAdParams) (ShortcutAd, error) {
	row := q.db.QueryRow(ctx, upsertShortcutAd,
		arg.ShortcutAdsID,
		arg.ShortcutAdsUrl,
		arg.ShortcutAdsType,
		arg.ShortcutAdsData,
		arg.ShortcutAdsBuildingID,
	)
	var i ShortcutAd
	err := row.Scan(
		&i.ShortcutAdsID,
		&i.ShortcutAdsUrl,
		&i.ShortcutAdsType,
		&i.ShortcutAdsFirstSeenAt,
		&i.ShortcutAdsLastSeenAt,
		&i.ShortcutAdsData,
		&i.ShortcutAdsUpdatedAt,
		&i.ShortcutAdsBuildingID,
	)
	return i, err
}

const upsertShortcutBuilding = `-- name: UpsertShortcutBuilding :one
INSERT INTO public.shortcut_buildings (
    shortcut_buildings_external_id,
    shortcut_buildings_building_id,
    shortcut_buildings_building_type,
    shortcut_buildings_building_subtype,
    shortcut_buildings_construction_year,
    shortcut_buildings_floor_count,
    shortcut_buildings_apartment_count,
    shortcut_buildings_heating_system,
    shortcut_buildings_building_material,
    shortcut_buildings_plot_type,
    shortcut_buildings_wall_structure,
    shortcut_buildings_heat_source,
    shortcut_buildings_has_elevator,
    shortcut_buildings_has_sauna,
    shortcut_buildings_latitude,
    shortcut_buildings_longitude,
    shortcut_buildings_additional_addresses,
    shortcut_buildings_url,
    shortcut_buildings_address,
    shortcut_buildings_frame_construction_method,
    shortcut_buildings_housing_company
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21
)
ON CONFLICT (shortcut_buildings_external_id) DO UPDATE SET
    shortcut_buildings_building_id = EXCLUDED.shortcut_buildings_building_id,
    shortcut_buildings_building_type = EXCLUDED.shortcut_buildings_building_type,
    shortcut_buildings_building_subtype = EXCLUDED.shortcut_buildings_building_subtype,
    shortcut_buildings_construction_year = EXCLUDED.shortcut_buildings_construction_year,
    shortcut_buildings_floor_count = EXCLUDED.shortcut_buildings_floor_count,
    shortcut_buildings_apartment_count = EXCLUDED.shortcut_buildings_apartment_count,
    shortcut_buildings_heating_system = EXCLUDED.shortcut_buildings_heating_system,
    shortcut_buildings_building_material = EXCLUDED.shortcut_buildings_building_material,
    shortcut_buildings_plot_type = EXCLUDED.shortcut_buildings_plot_type,
    shortcut_buildings_wall_structure = EXCLUDED.shortcut_buildings_wall_structure,
    shortcut_buildings_heat_source = EXCLUDED.shortcut_buildings_heat_source,
    shortcut_buildings_has_elevator = EXCLUDED.shortcut_buildings_has_elevator,
    shortcut_buildings_has_sauna = EXCLUDED.shortcut_buildings_has_sauna,
    shortcut_buildings_latitude = EXCLUDED.shortcut_buildings_latitude,
    shortcut_buildings_longitude = EXCLUDED.shortcut_buildings_longitude,
    shortcut_buildings_additional_addresses = EXCLUDED.shortcut_buildings_additional_addresses,
    shortcut_buildings_url = EXCLUDED.shortcut_buildings_url,
    shortcut_buildings_address = EXCLUDED.shortcut_buildings_address,
    shortcut_buildings_frame_construction_method = EXCLUDED.shortcut_buildings_frame_construction_method,
    shortcut_buildings_housing_company = EXCLUDED.shortcut_buildings_housing_company,
    shortcut_buildings_updated_at = CURRENT_TIMESTAMP
RETURNING shortcut_buildings_id, shortcut_buildings_external_id, shortcut_buildings_building_id, shortcut_buildings_building_type, shortcut_buildings_building_subtype, shortcut_buildings_construction_year, shortcut_buildings_floor_count, shortcut_buildings_apartment_count, shortcut_buildings_heating_system, shortcut_buildings_building_material, shortcut_buildings_plot_type, shortcut_buildings_wall_structure, shortcut_buildings_heat_source, shortcut_buildings_has_elevator, shortcut_buildings_has_sauna, shortcut_buildings_latitude, shortcut_buildings_longitude, shortcut_buildings_additional_addresses, shortcut_buildings_url, shortcut_buildings_created_at, shortcut_buildings_updated_at, shortcut_buildings_address, shortcut_buildings_processed_at, shortcut_buildings_page_not_found, shortcut_buildings_frame_construction_method, shortcut_buildings_housing_company, shortcut_buildings_geom
`

type UpsertShortcutBuildingParams struct {
	ShortcutBuildingsExternalID              int64         `db:"shortcut_buildings_external_id" json:"shortcut_buildings_external_id"`
	ShortcutBuildingsBuildingID              *string       `db:"shortcut_buildings_building_id" json:"shortcut_buildings_building_id"`
	ShortcutBuildingsBuildingType            *string       `db:"shortcut_buildings_building_type" json:"shortcut_buildings_building_type"`
	ShortcutBuildingsBuildingSubtype         *string       `db:"shortcut_buildings_building_subtype" json:"shortcut_buildings_building_subtype"`
	ShortcutBuildingsConstructionYear        pgtype.Int4   `db:"shortcut_buildings_construction_year" json:"shortcut_buildings_construction_year"`
	ShortcutBuildingsFloorCount              pgtype.Int4   `db:"shortcut_buildings_floor_count" json:"shortcut_buildings_floor_count"`
	ShortcutBuildingsApartmentCount          pgtype.Int4   `db:"shortcut_buildings_apartment_count" json:"shortcut_buildings_apartment_count"`
	ShortcutBuildingsHeatingSystem           *string       `db:"shortcut_buildings_heating_system" json:"shortcut_buildings_heating_system"`
	ShortcutBuildingsBuildingMaterial        *string       `db:"shortcut_buildings_building_material" json:"shortcut_buildings_building_material"`
	ShortcutBuildingsPlotType                *string       `db:"shortcut_buildings_plot_type" json:"shortcut_buildings_plot_type"`
	ShortcutBuildingsWallStructure           *string       `db:"shortcut_buildings_wall_structure" json:"shortcut_buildings_wall_structure"`
	ShortcutBuildingsHeatSource              *string       `db:"shortcut_buildings_heat_source" json:"shortcut_buildings_heat_source"`
	ShortcutBuildingsHasElevator             *string       `db:"shortcut_buildings_has_elevator" json:"shortcut_buildings_has_elevator"`
	ShortcutBuildingsHasSauna                *string       `db:"shortcut_buildings_has_sauna" json:"shortcut_buildings_has_sauna"`
	ShortcutBuildingsLatitude                pgtype.Float8 `db:"shortcut_buildings_latitude" json:"shortcut_buildings_latitude"`
	ShortcutBuildingsLongitude               pgtype.Float8 `db:"shortcut_buildings_longitude" json:"shortcut_buildings_longitude"`
	ShortcutBuildingsAdditionalAddresses     *string       `db:"shortcut_buildings_additional_addresses" json:"shortcut_buildings_additional_addresses"`
	ShortcutBuildingsUrl                     string        `db:"shortcut_buildings_url" json:"shortcut_buildings_url"`
	ShortcutBuildingsAddress                 *string       `db:"shortcut_buildings_address" json:"shortcut_buildings_address"`
	ShortcutBuildingsFrameConstructionMethod *string       `db:"shortcut_buildings_frame_construction_method" json:"shortcut_buildings_frame_construction_method"`
	ShortcutBuildingsHousingCompany          *string       `db:"shortcut_buildings_housing_company" json:"shortcut_buildings_housing_company"`
}

func (q *Queries) UpsertShortcutBuilding(ctx context.Context, arg *UpsertShortcutBuildingParams) (ShortcutBuilding, error) {
	row := q.db.QueryRow(ctx, upsertShortcutBuilding,
		arg.ShortcutBuildingsExternalID,
		arg.ShortcutBuildingsBuildingID,
		arg.ShortcutBuildingsBuildingType,
		arg.ShortcutBuildingsBuildingSubtype,
		arg.ShortcutBuildingsConstructionYear,
		arg.ShortcutBuildingsFloorCount,
		arg.ShortcutBuildingsApartmentCount,
		arg.ShortcutBuildingsHeatingSystem,
		arg.ShortcutBuildingsBuildingMaterial,
		arg.ShortcutBuildingsPlotType,
		arg.ShortcutBuildingsWallStructure,
		arg.ShortcutBuildingsHeatSource,
		arg.ShortcutBuildingsHasElevator,
		arg.ShortcutBuildingsHasSauna,
		arg.ShortcutBuildingsLatitude,
		arg.ShortcutBuildingsLongitude,
		arg.ShortcutBuildingsAdditionalAddresses,
		arg.ShortcutBuildingsUrl,
		arg.ShortcutBuildingsAddress,
		arg.ShortcutBuildingsFrameConstructionMethod,
		arg.ShortcutBuildingsHousingCompany,
	)
	var i ShortcutBuilding
	err := row.Scan(
		&i.ShortcutBuildingsID,
		&i.ShortcutBuildingsExternalID,
		&i.ShortcutBuildingsBuildingID,
		&i.ShortcutBuildingsBuildingType,
		&i.ShortcutBuildingsBuildingSubtype,
		&i.ShortcutBuildingsConstructionYear,
		&i.ShortcutBuildingsFloorCount,
		&i.ShortcutBuildingsApartmentCount,
		&i.ShortcutBuildingsHeatingSystem,
		&i.ShortcutBuildingsBuildingMaterial,
		&i.ShortcutBuildingsPlotType,
		&i.ShortcutBuildingsWallStructure,
		&i.ShortcutBuildingsHeatSource,
		&i.ShortcutBuildingsHasElevator,
		&i.ShortcutBuildingsHasSauna,
		&i.ShortcutBuildingsLatitude,
		&i.ShortcutBuildingsLongitude,
		&i.ShortcutBuildingsAdditionalAddresses,
		&i.ShortcutBuildingsUrl,
		&i.ShortcutBuildingsCreatedAt,
		&i.ShortcutBuildingsUpdatedAt,
		&i.ShortcutBuildingsAddress,
		&i.ShortcutBuildingsProcessedAt,
		&i.ShortcutBuildingsPageNotFound,
		&i.ShortcutBuildingsFrameConstructionMethod,
		&i.ShortcutBuildingsHousingCompany,
		&i.ShortcutBuildingsGeom,
	)
	return i, err
}

const upsertShortcutBuildingFromSitemap = `-- name: UpsertShortcutBuildingFromSitemap :one
INSERT INTO public.shortcut_buildings (
    shortcut_buildings_external_id,
    shortcut_buildings_url
) VALUES (
    $1, $2
)
ON CONFLICT (shortcut_buildings_external_id) DO UPDATE SET
    shortcut_buildings_url = EXCLUDED.shortcut_buildings_url,
    shortcut_buildings_updated_at = CURRENT_TIMESTAMP
RETURNING shortcut_buildings_id, shortcut_buildings_external_id, shortcut_buildings_building_id, shortcut_buildings_building_type, shortcut_buildings_building_subtype, shortcut_buildings_construction_year, shortcut_buildings_floor_count, shortcut_buildings_apartment_count, shortcut_buildings_heating_system, shortcut_buildings_building_material, shortcut_buildings_plot_type, shortcut_buildings_wall_structure, shortcut_buildings_heat_source, shortcut_buildings_has_elevator, shortcut_buildings_has_sauna, shortcut_buildings_latitude, shortcut_buildings_longitude, shortcut_buildings_additional_addresses, shortcut_buildings_url, shortcut_buildings_created_at, shortcut_buildings_updated_at, shortcut_buildings_address, shortcut_buildings_processed_at, shortcut_buildings_page_not_found, shortcut_buildings_frame_construction_method, shortcut_buildings_housing_company, shortcut_buildings_geom
`

type UpsertShortcutBuildingFromSitemapParams struct {
	ShortcutBuildingsExternalID int64  `db:"shortcut_buildings_external_id" json:"shortcut_buildings_external_id"`
	ShortcutBuildingsUrl        string `db:"shortcut_buildings_url" json:"shortcut_buildings_url"`
}

func (q *Queries) UpsertShortcutBuildingFromSitemap(ctx context.Context, arg *UpsertShortcutBuildingFromSitemapParams) (ShortcutBuilding, error) {
	row := q.db.QueryRow(ctx, upsertShortcutBuildingFromSitemap, arg.ShortcutBuildingsExternalID, arg.ShortcutBuildingsUrl)
	var i ShortcutBuilding
	err := row.Scan(
		&i.ShortcutBuildingsID,
		&i.ShortcutBuildingsExternalID,
		&i.ShortcutBuildingsBuildingID,
		&i.ShortcutBuildingsBuildingType,
		&i.ShortcutBuildingsBuildingSubtype,
		&i.ShortcutBuildingsConstructionYear,
		&i.ShortcutBuildingsFloorCount,
		&i.ShortcutBuildingsApartmentCount,
		&i.ShortcutBuildingsHeatingSystem,
		&i.ShortcutBuildingsBuildingMaterial,
		&i.ShortcutBuildingsPlotType,
		&i.ShortcutBuildingsWallStructure,
		&i.ShortcutBuildingsHeatSource,
		&i.ShortcutBuildingsHasElevator,
		&i.ShortcutBuildingsHasSauna,
		&i.ShortcutBuildingsLatitude,
		&i.ShortcutBuildingsLongitude,
		&i.ShortcutBuildingsAdditionalAddresses,
		&i.ShortcutBuildingsUrl,
		&i.ShortcutBuildingsCreatedAt,
		&i.ShortcutBuildingsUpdatedAt,
		&i.ShortcutBuildingsAddress,
		&i.ShortcutBuildingsProcessedAt,
		&i.ShortcutBuildingsPageNotFound,
		&i.ShortcutBuildingsFrameConstructionMethod,
		&i.ShortcutBuildingsHousingCompany,
		&i.ShortcutBuildingsGeom,
	)
	return i, err
}

const upsertShortcutBuildingListing = `-- name: UpsertShortcutBuildingListing :one
INSERT INTO public.shortcut_building_listings (
    shortcut_building_listings_building_id,
    shortcut_building_listings_layout,
    shortcut_building_listings_size,
    shortcut_building_listings_price,
    shortcut_building_listings_price_per_sqm,
    shortcut_building_listings_marketing_time,
    shortcut_building_listings_idx
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (shortcut_building_listings_building_id, shortcut_building_listings_layout, shortcut_building_listings_size, shortcut_building_listings_price, shortcut_building_listings_price_per_sqm, shortcut_building_listings_deleted_at, shortcut_building_listings_marketing_time, shortcut_building_listings_idx) DO UPDATE SET
    shortcut_building_listings_updated_at = CURRENT_TIMESTAMP
RETURNING shortcut_building_listings_id, shortcut_building_listings_building_id, shortcut_building_listings_layout, shortcut_building_listings_size, shortcut_building_listings_price, shortcut_building_listings_price_per_sqm, shortcut_building_listings_deleted_at, shortcut_building_listings_created_at, shortcut_building_listings_updated_at, shortcut_building_listings_marketing_time, shortcut_building_listings_idx
`

type UpsertShortcutBuildingListingParams struct {
	ShortcutBuildingListingsBuildingID    pgtype.UUID   `db:"shortcut_building_listings_building_id" json:"shortcut_building_listings_building_id"`
	ShortcutBuildingListingsLayout        *string       `db:"shortcut_building_listings_layout" json:"shortcut_building_listings_layout"`
	ShortcutBuildingListingsSize          pgtype.Float8 `db:"shortcut_building_listings_size" json:"shortcut_building_listings_size"`
	ShortcutBuildingListingsPrice         pgtype.Float8 `db:"shortcut_building_listings_price" json:"shortcut_building_listings_price"`
	ShortcutBuildingListingsPricePerSqm   pgtype.Float8 `db:"shortcut_building_listings_price_per_sqm" json:"shortcut_building_listings_price_per_sqm"`
	ShortcutBuildingListingsMarketingTime *string       `db:"shortcut_building_listings_marketing_time" json:"shortcut_building_listings_marketing_time"`
	ShortcutBuildingListingsIdx           pgtype.Int4   `db:"shortcut_building_listings_idx" json:"shortcut_building_listings_idx"`
}

func (q *Queries) UpsertShortcutBuildingListing(ctx context.Context, arg *UpsertShortcutBuildingListingParams) (ShortcutBuildingListing, error) {
	row := q.db.QueryRow(ctx, upsertShortcutBuildingListing,
		arg.ShortcutBuildingListingsBuildingID,
		arg.ShortcutBuildingListingsLayout,
		arg.ShortcutBuildingListingsSize,
		arg.ShortcutBuildingListingsPrice,
		arg.ShortcutBuildingListingsPricePerSqm,
		arg.ShortcutBuildingListingsMarketingTime,
		arg.ShortcutBuildingListingsIdx,
	)
	var i ShortcutBuildingListing
	err := row.Scan(
		&i.ShortcutBuildingListingsID,
		&i.ShortcutBuildingListingsBuildingID,
		&i.ShortcutBuildingListingsLayout,
		&i.ShortcutBuildingListingsSize,
		&i.ShortcutBuildingListingsPrice,
		&i.ShortcutBuildingListingsPricePerSqm,
		&i.ShortcutBuildingListingsDeletedAt,
		&i.ShortcutBuildingListingsCreatedAt,
		&i.ShortcutBuildingListingsUpdatedAt,
		&i.ShortcutBuildingListingsMarketingTime,
		&i.ShortcutBuildingListingsIdx,
	)
	return i, err
}

const upsertShortcutBuildingRental = `-- name: UpsertShortcutBuildingRental :one
INSERT INTO public.shortcut_building_rentals (
    shortcut_building_rentals_building_id,
    shortcut_building_rentals_layout,
    shortcut_building_rentals_size,
    shortcut_building_rentals_price,
    shortcut_building_rentals_marketing_time,
    shortcut_building_rentals_idx
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (shortcut_building_rentals_building_id, shortcut_building_rentals_layout, shortcut_building_rentals_size, shortcut_building_rentals_price, shortcut_building_rentals_deleted_at, shortcut_building_rentals_marketing_time, shortcut_building_rentals_idx) DO UPDATE SET
    shortcut_building_rentals_updated_at = CURRENT_TIMESTAMP
RETURNING shortcut_building_rentals_id, shortcut_building_rentals_building_id, shortcut_building_rentals_layout, shortcut_building_rentals_size, shortcut_building_rentals_price, shortcut_building_rentals_deleted_at, shortcut_building_rentals_created_at, shortcut_building_rentals_updated_at, shortcut_building_rentals_marketing_time, shortcut_building_rentals_idx
`

type UpsertShortcutBuildingRentalParams struct {
	ShortcutBuildingRentalsBuildingID    pgtype.UUID   `db:"shortcut_building_rentals_building_id" json:"shortcut_building_rentals_building_id"`
	ShortcutBuildingRentalsLayout        *string       `db:"shortcut_building_rentals_layout" json:"shortcut_building_rentals_layout"`
	ShortcutBuildingRentalsSize          pgtype.Float8 `db:"shortcut_building_rentals_size" json:"shortcut_building_rentals_size"`
	ShortcutBuildingRentalsPrice         pgtype.Float8 `db:"shortcut_building_rentals_price" json:"shortcut_building_rentals_price"`
	ShortcutBuildingRentalsMarketingTime *string       `db:"shortcut_building_rentals_marketing_time" json:"shortcut_building_rentals_marketing_time"`
	ShortcutBuildingRentalsIdx           pgtype.Int4   `db:"shortcut_building_rentals_idx" json:"shortcut_building_rentals_idx"`
}

func (q *Queries) UpsertShortcutBuildingRental(ctx context.Context, arg *UpsertShortcutBuildingRentalParams) (ShortcutBuildingRental, error) {
	row := q.db.QueryRow(ctx, upsertShortcutBuildingRental,
		arg.ShortcutBuildingRentalsBuildingID,
		arg.ShortcutBuildingRentalsLayout,
		arg.ShortcutBuildingRentalsSize,
		arg.ShortcutBuildingRentalsPrice,
		arg.ShortcutBuildingRentalsMarketingTime,
		arg.ShortcutBuildingRentalsIdx,
	)
	var i ShortcutBuildingRental
	err := row.Scan(
		&i.ShortcutBuildingRentalsID,
		&i.ShortcutBuildingRentalsBuildingID,
		&i.ShortcutBuildingRentalsLayout,
		&i.ShortcutBuildingRentalsSize,
		&i.ShortcutBuildingRentalsPrice,
		&i.ShortcutBuildingRentalsDeletedAt,
		&i.ShortcutBuildingRentalsCreatedAt,
		&i.ShortcutBuildingRentalsUpdatedAt,
		&i.ShortcutBuildingRentalsMarketingTime,
		&i.ShortcutBuildingRentalsIdx,
	)
	return i, err
}
