//go:build go1.22

// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// City defines model for City.
type City struct {
	Id            openapi_types.UUID `json:"id"`
	Name          string             `json:"name"`
	Neighborhoods []Neighborhood     `json:"neighborhoods"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// HintatiedotCitiesResponse defines model for HintatiedotCitiesResponse.
type HintatiedotCitiesResponse struct {
	Cities []string `json:"cities"`
}

// HintatiedotTransaction defines model for HintatiedotTransaction.
type HintatiedotTransaction struct {
	Area                float64                 `json:"area"`
	BuildYear           int32                   `json:"build_year"`
	Category            string                  `json:"category"`
	Condition           string                  `json:"condition"`
	Description         string                  `json:"description"`
	Elevator            bool                    `json:"elevator"`
	EnergyClass         *string                 `json:"energy_class"`
	FirstSeenAt         time.Time               `json:"first_seen_at"`
	Floor               string                  `json:"floor"`
	Id                  openapi_types.UUID      `json:"id"`
	LastSeenAt          time.Time               `json:"last_seen_at"`
	Neighborhood        TransactionNeighborhood `json:"neighborhood"`
	Plot                string                  `json:"plot"`
	Price               int32                   `json:"price"`
	PricePerSquareMeter int32                   `json:"price_per_square_meter"`
	Type                string                  `json:"type"`
}

// Neighborhood defines model for Neighborhood.
type Neighborhood struct {
	Id         openapi_types.UUID `json:"id"`
	Name       string             `json:"name"`
	PostalCode *string            `json:"postal_code"`
}

// PingRequest defines model for PingRequest.
type PingRequest struct {
	Message string `json:"message"`
}

// PingResponse defines model for PingResponse.
type PingResponse struct {
	Echo string `json:"echo"`
}

// SyncHintatiedotRequest defines model for SyncHintatiedotRequest.
type SyncHintatiedotRequest struct {
	City string `json:"city"`
}

// SyncHintatiedotResponse defines model for SyncHintatiedotResponse.
type SyncHintatiedotResponse struct {
	City   string `json:"city"`
	Status string `json:"status"`
}

// TransactionNeighborhood defines model for TransactionNeighborhood.
type TransactionNeighborhood struct {
	Code       openapi_types.UUID `json:"code"`
	Name       string             `json:"name"`
	PostalCode *string            `json:"postal_code"`
}

// ListTransactionsParams defines parameters for ListTransactions.
type ListTransactionsParams struct {
	// Neighborhoods Comma-separated list of neighborhood IDs
	Neighborhoods []openapi_types.UUID `form:"neighborhoods" json:"neighborhoods"`
}

// SyncHintatiedotCityJSONRequestBody defines body for SyncHintatiedotCity for application/json ContentType.
type SyncHintatiedotCityJSONRequestBody = SyncHintatiedotRequest

// PingJSONRequestBody defines body for Ping for application/json ContentType.
type PingJSONRequestBody = PingRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List cities with neighborhoods
	// (GET /api/v1/cities)
	ListCities(w http.ResponseWriter, r *http.Request)
	// Fetch cities from Hintatiedot
	// (GET /api/v1/hintatiedot/cities)
	FetchHintatiedotCities(w http.ResponseWriter, r *http.Request)
	// Sync a city from Hintatiedot
	// (POST /api/v1/hintatiedot/sync)
	SyncHintatiedotCity(w http.ResponseWriter, r *http.Request)
	// Echo a message
	// (POST /api/v1/ping)
	Ping(w http.ResponseWriter, r *http.Request)
	// List transactions for neighborhoods
	// (GET /api/v1/transactions)
	ListTransactions(w http.ResponseWriter, r *http.Request, params ListTransactionsParams)
	// Fetch transactions from Hintatiedot for Helsinki
	// (POST /api/v1/transactions/fetch)
	FetchTransactions(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /healthz)
	Healthz(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListCities operation middleware
func (siw *ServerInterfaceWrapper) ListCities(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FetchHintatiedotCities operation middleware
func (siw *ServerInterfaceWrapper) FetchHintatiedotCities(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FetchHintatiedotCities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SyncHintatiedotCity operation middleware
func (siw *ServerInterfaceWrapper) SyncHintatiedotCity(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SyncHintatiedotCity(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Ping operation middleware
func (siw *ServerInterfaceWrapper) Ping(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Ping(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTransactions operation middleware
func (siw *ServerInterfaceWrapper) ListTransactions(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTransactionsParams

	// ------------- Required query parameter "neighborhoods" -------------

	if paramValue := r.URL.Query().Get("neighborhoods"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "neighborhoods"})
		return
	}

	err = runtime.BindQueryParameter("form", false, true, "neighborhoods", r.URL.Query(), &params.Neighborhoods)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "neighborhoods", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTransactions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FetchTransactions operation middleware
func (siw *ServerInterfaceWrapper) FetchTransactions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FetchTransactions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Healthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/v1/cities", wrapper.ListCities)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/hintatiedot/cities", wrapper.FetchHintatiedotCities)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/hintatiedot/sync", wrapper.SyncHintatiedotCity)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/ping", wrapper.Ping)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/transactions", wrapper.ListTransactions)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/transactions/fetch", wrapper.FetchTransactions)
	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.Healthz)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RYUXPbNgz+Kzxuj27sNtuL3rpuueS29Xpd33o5H0xBFluKVEjIq5bzf9+RkmKJkmxv",
	"i7OXNmeCwAfgIz7Yj1yYojQaNTmePHInciwg/PlOUu3/L60p0ZLE8KlM/b+ZsQUQT3hVyZQvONUl8oQ7",
	"slJv+X7BNRToDccHKLf5xtjcmLRxSFiEP763mPGEf7c8IFq2cJbve7e8l9YtWAs13+8X3OJDJS2mPPnM",
	"A6IAIA53/3TTbL6gIO/qFkFR/hFdabTDccKOgCo3kUsUtbWbDCE1AUlMDb2T3u98NCGfCt3VZVTCo8m3",
	"Dk7A+GRBOxAkjR5jAIswaHJqqo3CQ5t1VWzQepebSqp0XSPYwQWp6frNwV5qwm1zQQDh1th6MjFhdCo7",
	"TKPTFJ2wspw9R4U7IGN7hxtjFIIOpxrttl4LBS4kqSulwGeVkK1wgsGZtI7WDlGvfU79cgDhK5IFThE/",
	"U2YA4XBy5stR8G/C9nl+6jH1mh+/q1IZmgRfWinwzB4H23WJdu0eKrC4LpDwXII0n5x6bM0T74Mf8qP1",
	"s2i43MGfhTYgctfDHqP61GyLFDEq5kvUxx7xp17m+6h7zztyS+MI1FqYFM9g/pFh2nc0lcYHqbcf8aFC",
	"R+MsCnQOtmf0tjOcjzA3PFHk5rT/YDXl/I9ai96MnM1EtMJ4PEywOivMES2YnpP/UJIW81jmRsEYS0ue",
	"/4mF4dbQRxtqnJW/K3XWMEGSD8F/Nakko9nbD3d8wXdoXVARvrp6fbXy6EyJGkrJE359tbq69rGA8pD6",
	"Ekq53L1eHqR5i4EVvj7gS3eX8oT/Jl2r7txjb5oazN+sVk0JNaEON6EslRTh7vKLa/Ssmc5nb0RhOxsv",
	"A7FOhi2OKelCu38cISH8RstSgYwwxO0Y+b0BqTBlZFiGJHLWVscbuqoowEt8qEl7wv6UlLPhOuaNu+rm",
	"hxdxqtI3PuBop/qvVT9W7PkFbqIyb3cgA7WfavLyhb/pHbHMmoL1Upitu6u1CE/fuImyR3MrELB5pejo",
	"J5PWz1bumUG8H04FPzf2F2z63Jye6Ik3Za4SAjHFsEj98HwNv9M7UDJltivDs9IpQM8CpyIOhRPwJKqP",
	"U6j0rmdp4yX7Qjzp7xsvTI7BIjJR1l9EbjBl3S5zUUawEmplIO6fh8DgAKHXMTrI/nFB+9Q39JpoIWzM",
	"jiefH2OlMUUBrxx6I8I0iA4z2WDms7ufvR/8VqqwB2SgHHq55gl/qNDWnawn0Tf3uLeLKb08uZwMxdIv",
	"UnVYD/xFvr9/Cd2e+RJ+hpL/DiRyqbds0L3LMGvUs8tq2DCj8QrRP2eZsUf2iL7pMnifH01BJSOKTzEg",
	"Ah8gOwJLo5l5M0pnNDoD/ltUTuqvsoGeh5+g/pp9ibft+SU3nOGvYFNCgXYnBTLpWIO3jnJvXDCRo/ja",
	"OHBod92sqKziCV/y/f3+7wAAAP//DML65HQUAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
