// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PricesCity struct {
	PricesCitiesID        pgtype.UUID        `db:"prices_cities_id" json:"prices_cities_id"`
	PricesCitiesName      string             `db:"prices_cities_name" json:"prices_cities_name"`
	PricesCitiesCreatedAt pgtype.Timestamptz `db:"prices_cities_created_at" json:"prices_cities_created_at"`
	PricesCitiesUpdatedAt pgtype.Timestamptz `db:"prices_cities_updated_at" json:"prices_cities_updated_at"`
}

type PricesNeighborhood struct {
	PricesNeighborhoodsID           pgtype.UUID        `db:"prices_neighborhoods_id" json:"prices_neighborhoods_id"`
	PricesNeighborhoodsName         string             `db:"prices_neighborhoods_name" json:"prices_neighborhoods_name"`
	PricesNeighborhoodsCityID       pgtype.UUID        `db:"prices_neighborhoods_city_id" json:"prices_neighborhoods_city_id"`
	PricesNeighborhoodsPostalCodeID pgtype.UUID        `db:"prices_neighborhoods_postal_code_id" json:"prices_neighborhoods_postal_code_id"`
	PricesNeighborhoodsCreatedAt    pgtype.Timestamptz `db:"prices_neighborhoods_created_at" json:"prices_neighborhoods_created_at"`
	PricesNeighborhoodsUpdatedAt    pgtype.Timestamptz `db:"prices_neighborhoods_updated_at" json:"prices_neighborhoods_updated_at"`
}

type PricesPostalCode struct {
	PricesPostalCodesID        pgtype.UUID        `db:"prices_postal_codes_id" json:"prices_postal_codes_id"`
	PricesPostalCodesCode      string             `db:"prices_postal_codes_code" json:"prices_postal_codes_code"`
	PricesPostalCodesCityID    pgtype.UUID        `db:"prices_postal_codes_city_id" json:"prices_postal_codes_city_id"`
	PricesPostalCodesCreatedAt pgtype.Timestamptz `db:"prices_postal_codes_created_at" json:"prices_postal_codes_created_at"`
	PricesPostalCodesUpdatedAt pgtype.Timestamptz `db:"prices_postal_codes_updated_at" json:"prices_postal_codes_updated_at"`
}

type PricesTransaction struct {
	PricesTransactionsID                  pgtype.UUID        `db:"prices_transactions_id" json:"prices_transactions_id"`
	PricesTransactionsNeighborhood        string             `db:"prices_transactions_neighborhood" json:"prices_transactions_neighborhood"`
	PricesTransactionsDescription         string             `db:"prices_transactions_description" json:"prices_transactions_description"`
	PricesTransactionsType                string             `db:"prices_transactions_type" json:"prices_transactions_type"`
	PricesTransactionsArea                float64            `db:"prices_transactions_area" json:"prices_transactions_area"`
	PricesTransactionsPrice               int32              `db:"prices_transactions_price" json:"prices_transactions_price"`
	PricesTransactionsPricePerSquareMeter int32              `db:"prices_transactions_price_per_square_meter" json:"prices_transactions_price_per_square_meter"`
	PricesTransactionsBuildYear           int32              `db:"prices_transactions_build_year" json:"prices_transactions_build_year"`
	PricesTransactionsFloor               *string            `db:"prices_transactions_floor" json:"prices_transactions_floor"`
	PricesTransactionsElevator            bool               `db:"prices_transactions_elevator" json:"prices_transactions_elevator"`
	PricesTransactionsCondition           *string            `db:"prices_transactions_condition" json:"prices_transactions_condition"`
	PricesTransactionsPlot                *string            `db:"prices_transactions_plot" json:"prices_transactions_plot"`
	PricesTransactionsEnergyClass         *string            `db:"prices_transactions_energy_class" json:"prices_transactions_energy_class"`
	PricesTransactionsPeriodIdentifier    string             `db:"prices_transactions_period_identifier" json:"prices_transactions_period_identifier"`
	PricesTransactionsCreatedAt           pgtype.Timestamptz `db:"prices_transactions_created_at" json:"prices_transactions_created_at"`
	PricesTransactionsUpdatedAt           pgtype.Timestamptz `db:"prices_transactions_updated_at" json:"prices_transactions_updated_at"`
	PricesTransactionsCategory            string             `db:"prices_transactions_category" json:"prices_transactions_category"`
	PricesNeighborhoodsID                 pgtype.UUID        `db:"prices_neighborhoods_id" json:"prices_neighborhoods_id"`
}
