receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
          system.cpu.logical.count:
            enabled: true
      disk:
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true
      load:
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      network:
      processes:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  otlp_http/traceway:
    endpoint: http://traceway/api/otel
    headers:
      Authorization: Bearer ${env:TRACEWAY_PROJECT_TOKEN}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_http/traceway]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch]
      exporters: [otlp_http/traceway]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_http/traceway]
