ALTER TABLE hintatiedot_transactions
DROP COLUMN hintatiedot_transactions_city;

ALTER TABLE hintatiedot_transactions
DROP COLUMN hintatiedot_transactions_neighborhood;

ALTER TABLE hintatiedot_transactions
DROP COLUMN hintatiedot_neighborhoods_postal_code

ALTER TABLE hintatiedot_transactions
RENAME COLUMN hintatiedot_transactions_first_seen_at TO created_at;

ALTER TABLE hintatiedot_transactions
RENAME COLUMN hintatiedot_transactions_last_seen_at TO updated_at;
