ALTER TABLE public.sale_listings
ADD COLUMN IF NOT EXISTS sale_listing_availability_text text,
ADD COLUMN IF NOT EXISTS sale_listing_renovations_done_text text,
ADD COLUMN IF NOT EXISTS sale_listing_renovations_planned_text text,
ADD COLUMN IF NOT EXISTS sale_listing_additional_info_text text,
ADD COLUMN IF NOT EXISTS sale_listing_charges_text text,
ADD COLUMN IF NOT EXISTS sale_listing_maintenance_charge_monthly double precision,
ADD COLUMN IF NOT EXISTS sale_listing_total_charge_monthly double precision,
ADD COLUMN IF NOT EXISTS sale_listing_water_charge double precision;

CREATE OR REPLACE FUNCTION public.fnc__sync_sale_listing_from_shortcut_ad()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        DELETE FROM public.sale_listings WHERE shortcut_ad_id = OLD.shortcut_ad_id;
        RETURN OLD;
    END IF;
    IF NEW.shortcut_ad_type <> 'listing' THEN
        DELETE FROM public.sale_listings WHERE shortcut_ad_id = NEW.shortcut_ad_id;
        RETURN NEW;
    END IF;
    INSERT INTO public.sale_listings (
        shortcut_ad_id,
        sale_listing_source_provider,
        sale_listing_source_kind,
        sale_listing_native_id,
        sale_listing_canonical_id,
        sale_listing_url,
        sale_listing_headline,
        sale_listing_street_address,
        sale_listing_street_name,
        sale_listing_street_number,
        sale_listing_building_letter,
        sale_listing_city,
        sale_listing_postal,
        sale_listing_asking_price,
        sale_listing_area_value,
        sale_listing_room_layout,
        sale_listing_last_seen_at,
        sale_listing_published_at,
        sale_listing_search_text,
        sale_listing_price_per_m2,
        sale_listing_debt_free_price,
        sale_listing_debt_share_amount,
        sale_listing_rooms_count,
        sale_listing_floor_level,
        sale_listing_total_floors,
        sale_listing_build_year,
        sale_listing_condition,
        sale_listing_energy_class,
        sale_listing_description_text,
        sale_listing_availability_text,
        sale_listing_renovations_done_text,
        sale_listing_renovations_planned_text,
        sale_listing_additional_info_text,
        sale_listing_charges_text,
        sale_listing_maintenance_charge_monthly,
        sale_listing_total_charge_monthly,
        sale_listing_water_charge,
        sale_listing_updated_at
    )
    SELECT
        NEW.shortcut_ad_id,
        'shortcut',
        'ad',
        NEW.shortcut_ad_id::text,
        'shortcut:ad:' || NEW.shortcut_ad_id::text,
        NEW.shortcut_ad_url,
        COALESCE(NEW.shortcut_ad_street_address, sb.shortcut_building_address, NEW.shortcut_ad_id::text),
        COALESCE(NEW.shortcut_ad_street_address, sb.shortcut_building_address),
        NULLIF(trim(NEW.shortcut_ad_data #>> '{address,street,name}'), ''),
        NULLIF(trim(NEW.shortcut_ad_data #>> '{address,streetNumber}'), ''),
        NULLIF(trim(NEW.shortcut_ad_data #>> '{address,buildingLetter}'), ''),
        NEW.shortcut_ad_city,
        NEW.shortcut_ad_postal,
        NEW.shortcut_ad_price,
        NEW.shortcut_ad_area_value,
        NEW.shortcut_ad_data #>> '{adData,roomConfiguration}',
        NEW.shortcut_ad_last_seen_at,
        (NEW.shortcut_ad_data #>> '{adData,published}')::timestamptz,
        concat_ws(' ', NEW.shortcut_ad_search_text, sb.shortcut_building_address, sb.shortcut_building_housing_company),
        public.fnc__derived_price_per_m2(NEW.shortcut_ad_price, NEW.shortcut_ad_area_value, NEW.shortcut_ad_price_per_m2),
        NEW.shortcut_ad_debt_free_price,
        NEW.shortcut_ad_debt_share_amount,
        NEW.shortcut_ad_rooms_count,
        NEW.shortcut_ad_floor_level,
        NEW.shortcut_ad_total_floors,
        COALESCE(NEW.shortcut_ad_build_year, sb.shortcut_building_construction_year),
        NEW.shortcut_ad_condition,
        NEW.shortcut_ad_energy_class,
        NEW.shortcut_ad_description_text,
        NEW.shortcut_ad_availability_text,
        NEW.shortcut_ad_renovations_done_text,
        NEW.shortcut_ad_renovations_planned_text,
        NEW.shortcut_ad_additional_info_text,
        NEW.shortcut_ad_charges_text,
        NEW.shortcut_ad_maintenance_charge_monthly,
        NEW.shortcut_ad_total_charge_monthly,
        NEW.shortcut_ad_water_charge,
        now()
    FROM (SELECT 1) seed
    LEFT JOIN public.shortcut_buildings sb ON sb.shortcut_building_id = NEW.shortcut_building_id
    ON CONFLICT (sale_listing_canonical_id) DO UPDATE SET
        shortcut_ad_id = EXCLUDED.shortcut_ad_id,
        sale_listing_source_provider = EXCLUDED.sale_listing_source_provider,
        sale_listing_source_kind = EXCLUDED.sale_listing_source_kind,
        sale_listing_native_id = EXCLUDED.sale_listing_native_id,
        sale_listing_url = EXCLUDED.sale_listing_url,
        sale_listing_headline = EXCLUDED.sale_listing_headline,
        sale_listing_street_address = EXCLUDED.sale_listing_street_address,
        sale_listing_street_name = EXCLUDED.sale_listing_street_name,
        sale_listing_street_number = EXCLUDED.sale_listing_street_number,
        sale_listing_building_letter = EXCLUDED.sale_listing_building_letter,
        sale_listing_city = EXCLUDED.sale_listing_city,
        sale_listing_postal = EXCLUDED.sale_listing_postal,
        sale_listing_asking_price = EXCLUDED.sale_listing_asking_price,
        sale_listing_area_value = EXCLUDED.sale_listing_area_value,
        sale_listing_room_layout = EXCLUDED.sale_listing_room_layout,
        sale_listing_last_seen_at = EXCLUDED.sale_listing_last_seen_at,
        sale_listing_published_at = EXCLUDED.sale_listing_published_at,
        sale_listing_search_text = EXCLUDED.sale_listing_search_text,
        sale_listing_price_per_m2 = EXCLUDED.sale_listing_price_per_m2,
        sale_listing_debt_free_price = EXCLUDED.sale_listing_debt_free_price,
        sale_listing_debt_share_amount = EXCLUDED.sale_listing_debt_share_amount,
        sale_listing_rooms_count = EXCLUDED.sale_listing_rooms_count,
        sale_listing_floor_level = EXCLUDED.sale_listing_floor_level,
        sale_listing_total_floors = EXCLUDED.sale_listing_total_floors,
        sale_listing_build_year = EXCLUDED.sale_listing_build_year,
        sale_listing_condition = EXCLUDED.sale_listing_condition,
        sale_listing_energy_class = EXCLUDED.sale_listing_energy_class,
        sale_listing_description_text = EXCLUDED.sale_listing_description_text,
        sale_listing_availability_text = EXCLUDED.sale_listing_availability_text,
        sale_listing_renovations_done_text = EXCLUDED.sale_listing_renovations_done_text,
        sale_listing_renovations_planned_text = EXCLUDED.sale_listing_renovations_planned_text,
        sale_listing_additional_info_text = EXCLUDED.sale_listing_additional_info_text,
        sale_listing_charges_text = EXCLUDED.sale_listing_charges_text,
        sale_listing_maintenance_charge_monthly = EXCLUDED.sale_listing_maintenance_charge_monthly,
        sale_listing_total_charge_monthly = EXCLUDED.sale_listing_total_charge_monthly,
        sale_listing_water_charge = EXCLUDED.sale_listing_water_charge,
        sale_listing_updated_at = now();
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.fnc__sync_sale_listing_from_frontdoor_ad()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        DELETE FROM public.sale_listings WHERE frontdoor_ad_id = OLD.frontdoor_ad_id;
        RETURN OLD;
    END IF;
    INSERT INTO public.sale_listings (
        frontdoor_ad_id,
        sale_listing_source_provider,
        sale_listing_source_kind,
        sale_listing_native_id,
        sale_listing_canonical_id,
        sale_listing_url,
        sale_listing_headline,
        sale_listing_street_address,
        sale_listing_city,
        sale_listing_postal,
        sale_listing_asking_price,
        sale_listing_area_value,
        sale_listing_room_layout,
        sale_listing_last_seen_at,
        sale_listing_published_at,
        sale_listing_search_text,
        sale_listing_price_per_m2,
        sale_listing_debt_free_price,
        sale_listing_debt_share_amount,
        sale_listing_rooms_count,
        sale_listing_floor_level,
        sale_listing_total_floors,
        sale_listing_build_year,
        sale_listing_condition,
        sale_listing_energy_class,
        sale_listing_description_text,
        sale_listing_availability_text,
        sale_listing_renovations_done_text,
        sale_listing_renovations_planned_text,
        sale_listing_additional_info_text,
        sale_listing_charges_text,
        sale_listing_maintenance_charge_monthly,
        sale_listing_total_charge_monthly,
        sale_listing_water_charge,
        sale_listing_updated_at
    )
    VALUES (
        NEW.frontdoor_ad_id,
        'frontdoor',
        'ad',
        NEW.frontdoor_ad_external_id,
        'frontdoor:ad:' || NEW.frontdoor_ad_external_id,
        NEW.frontdoor_ad_url,
        COALESCE(NEW.frontdoor_ad_street_address, NEW.frontdoor_ad_external_id),
        NEW.frontdoor_ad_street_address,
        NEW.frontdoor_ad_city,
        NEW.frontdoor_ad_postal,
        NEW.frontdoor_ad_price,
        NEW.frontdoor_ad_area_value,
        NEW.frontdoor_ad_data #>> '{residenceDetailsDTO,roomStructure}',
        NEW.frontdoor_ad_last_seen_at,
        NEW.frontdoor_ad_publishing_time,
        NEW.frontdoor_ad_search_text,
        public.fnc__derived_price_per_m2(NEW.frontdoor_ad_price, NEW.frontdoor_ad_area_value, NEW.frontdoor_ad_price_per_m2),
        NEW.frontdoor_ad_debt_free_price,
        NEW.frontdoor_ad_debt_share_amount,
        NEW.frontdoor_ad_rooms_count,
        NEW.frontdoor_ad_floor_level,
        NEW.frontdoor_ad_total_floors,
        NEW.frontdoor_ad_build_year,
        NEW.frontdoor_ad_condition,
        NEW.frontdoor_ad_energy_class,
        NEW.frontdoor_ad_description_text,
        NEW.frontdoor_ad_availability_text,
        NEW.frontdoor_ad_renovations_done_text,
        NEW.frontdoor_ad_renovations_planned_text,
        NEW.frontdoor_ad_additional_info_text,
        NEW.frontdoor_ad_charges_text,
        NEW.frontdoor_ad_maintenance_charge_monthly,
        NEW.frontdoor_ad_total_charge_monthly,
        NEW.frontdoor_ad_water_charge,
        now()
    )
    ON CONFLICT (sale_listing_canonical_id) DO UPDATE SET
        frontdoor_ad_id = EXCLUDED.frontdoor_ad_id,
        sale_listing_source_provider = EXCLUDED.sale_listing_source_provider,
        sale_listing_source_kind = EXCLUDED.sale_listing_source_kind,
        sale_listing_native_id = EXCLUDED.sale_listing_native_id,
        sale_listing_url = EXCLUDED.sale_listing_url,
        sale_listing_headline = EXCLUDED.sale_listing_headline,
        sale_listing_street_address = EXCLUDED.sale_listing_street_address,
        sale_listing_city = EXCLUDED.sale_listing_city,
        sale_listing_postal = EXCLUDED.sale_listing_postal,
        sale_listing_asking_price = EXCLUDED.sale_listing_asking_price,
        sale_listing_area_value = EXCLUDED.sale_listing_area_value,
        sale_listing_room_layout = EXCLUDED.sale_listing_room_layout,
        sale_listing_last_seen_at = EXCLUDED.sale_listing_last_seen_at,
        sale_listing_published_at = EXCLUDED.sale_listing_published_at,
        sale_listing_search_text = EXCLUDED.sale_listing_search_text,
        sale_listing_price_per_m2 = EXCLUDED.sale_listing_price_per_m2,
        sale_listing_debt_free_price = EXCLUDED.sale_listing_debt_free_price,
        sale_listing_debt_share_amount = EXCLUDED.sale_listing_debt_share_amount,
        sale_listing_rooms_count = EXCLUDED.sale_listing_rooms_count,
        sale_listing_floor_level = EXCLUDED.sale_listing_floor_level,
        sale_listing_total_floors = EXCLUDED.sale_listing_total_floors,
        sale_listing_build_year = EXCLUDED.sale_listing_build_year,
        sale_listing_condition = EXCLUDED.sale_listing_condition,
        sale_listing_energy_class = EXCLUDED.sale_listing_energy_class,
        sale_listing_description_text = EXCLUDED.sale_listing_description_text,
        sale_listing_availability_text = EXCLUDED.sale_listing_availability_text,
        sale_listing_renovations_done_text = EXCLUDED.sale_listing_renovations_done_text,
        sale_listing_renovations_planned_text = EXCLUDED.sale_listing_renovations_planned_text,
        sale_listing_additional_info_text = EXCLUDED.sale_listing_additional_info_text,
        sale_listing_charges_text = EXCLUDED.sale_listing_charges_text,
        sale_listing_maintenance_charge_monthly = EXCLUDED.sale_listing_maintenance_charge_monthly,
        sale_listing_total_charge_monthly = EXCLUDED.sale_listing_total_charge_monthly,
        sale_listing_water_charge = EXCLUDED.sale_listing_water_charge,
        sale_listing_updated_at = now();
    RETURN NEW;
END;
$$;
