ALTER TABLE public.property_source_offerings
    ADD COLUMN IF NOT EXISTS sale_listing_living_area_value double precision,
    ADD COLUMN IF NOT EXISTS sale_listing_total_area_value double precision,
    ADD COLUMN IF NOT EXISTS sale_listing_other_area_value double precision,
    ADD COLUMN IF NOT EXISTS sale_listing_bedrooms_count integer,
    ADD COLUMN IF NOT EXISTS sale_listing_sauna boolean,
    ADD COLUMN IF NOT EXISTS sale_listing_balcony boolean,
    ADD COLUMN IF NOT EXISTS sale_listing_parking_text text,
    ADD COLUMN IF NOT EXISTS sale_listing_kitchen_description_text text,
    ADD COLUMN IF NOT EXISTS sale_listing_bathroom_description_text text,
    ADD COLUMN IF NOT EXISTS sale_listing_storage_description_text text,
    ADD COLUMN IF NOT EXISTS sale_listing_floor_materials_description_text text,
    ADD COLUMN IF NOT EXISTS sale_listing_wall_materials_description_text text,
    ADD COLUMN IF NOT EXISTS sale_listing_balcony_description_text text,
    ADD COLUMN IF NOT EXISTS sale_listing_sauna_description_text text,
    ADD COLUMN IF NOT EXISTS sale_listing_views_description_text text,
    ADD COLUMN IF NOT EXISTS sale_listing_appliances text[],
    ADD COLUMN IF NOT EXISTS sale_listing_features text[],
    ADD COLUMN IF NOT EXISTS sale_listing_plot_area_value double precision,
    ADD COLUMN IF NOT EXISTS sale_listing_services_text text,
    ADD COLUMN IF NOT EXISTS sale_listing_transport_text text,
    ADD COLUMN IF NOT EXISTS sale_listing_previous_asking_price bigint,
    ADD COLUMN IF NOT EXISTS sale_listing_previous_debt_free_price bigint,
    ADD COLUMN IF NOT EXISTS sale_listing_new_development boolean;
