create or replace function pg_temp.safe_pg_get_expr(expr pg_node_tree, rel oid)
returns text language plpgsql as $$
begin
  return pg_get_expr(expr, rel);
exception when others then
  return null;
end;
$$;

create or replace function pg_temp.safe_pg_get_constraintdef(con_oid oid)
returns text language plpgsql as $$
begin
  return pg_get_constraintdef(con_oid);
exception when others then
  return null;
end;
$$;

create or replace function pg_temp.safe_pg_get_indexdef(idx_oid oid)
returns text language plpgsql as $$
begin
  return pg_get_indexdef(idx_oid);
exception when others then
  return null;
end;
$$;

with tables as (
  select
    c.oid as table_oid,
    n.nspname as schema_name,
    c.relname as table_name
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relkind in ('r', 'p')
    and c.relname not like 'supabase_%'
    and not exists (
      select 1 from pg_roles r
      where r.oid = c.relowner
        and r.rolname like 'supabase_%'
    )
  order by c.relname
),
columns as (
  select
    a.attrelid as table_oid,
    a.attnum,
    quote_ident(a.attname) as column_name,
    format_type(a.atttypid, a.atttypmod) as column_type,
    regexp_replace(pg_temp.safe_pg_get_expr(ad.adbin, ad.adrelid), '\s+', ' ', 'g') as column_expr,
    a.attnotnull as not_null,
    a.attidentity as identity_type,
    a.attgenerated as generated_type
  from pg_attribute a
  join pg_class c on c.oid = a.attrelid
  join pg_namespace n on n.oid = c.relnamespace
  left join pg_attrdef ad on ad.adrelid = a.attrelid and ad.adnum = a.attnum
  where n.nspname = 'public'
    and c.relkind in ('r', 'p')
    and a.attnum > 0
    and not a.attisdropped
),
constraints as (
  select
    con.conrelid as table_oid,
    con.conname,
    con.contype,
    pg_temp.safe_pg_get_constraintdef(con.oid) as condef,
    case con.contype
      when 'p' then 1
      when 'u' then 2
      when 'f' then 3
      when 'c' then 4
      else 5
    end as sort_order
  from pg_constraint con
  join pg_class c on c.oid = con.conrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relkind in ('r', 'p')
),
indexes as (
  select
    i.indrelid as table_oid,
    ci.relname as index_name,
    pg_temp.safe_pg_get_indexdef(i.indexrelid) as index_def
  from pg_index i
  join pg_class c on c.oid = i.indrelid
  join pg_class ci on ci.oid = i.indexrelid
  join pg_namespace n on n.oid = c.relnamespace
  left join pg_constraint con on con.conindid = i.indexrelid
  where n.nspname = 'public'
    and c.relkind in ('r', 'p')
    and con.oid is null
)
select
  'create table ' || quote_ident(t.schema_name) || '.' || quote_ident(t.table_name) || E' (\n  ' ||
  (
    select string_agg(
      c.column_name || ' ' || c.column_type ||
      case
        when c.identity_type = 'a' then ' generated always as identity'
        when c.identity_type = 'd' then ' generated by default as identity'
        else ''
      end ||
      case
        when c.generated_type = 's' then ' generated always as (' || c.column_expr || ') stored'
        when c.generated_type = 'v' then ' generated always as (' || c.column_expr || ') virtual'
        when c.column_expr is not null and c.identity_type = '' then ' default ' || c.column_expr
        else ''
      end ||
      case
        when c.not_null then ' not null'
        else ''
      end,
      E',\n  ' order by c.attnum
    )
    from columns c
    where c.table_oid = t.table_oid
  ) ||
  coalesce(
    (
      select E',\n  ' || string_agg(
        'constraint ' || quote_ident(con.conname) || ' ' || con.condef,
        E',\n  ' order by con.sort_order, con.conname
      )
      from constraints con
      where con.table_oid = t.table_oid
    ),
    ''
  ) ||
  E'\n);\n' ||
  coalesce(
    (
      select E'\n' || string_agg(i.index_def || ';', E'\n' order by i.index_name)
      from indexes i
      where i.table_oid = t.table_oid
    ),
    ''
  ) ||
  E'\n'
from tables t;
