// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ads.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const backfillFrontdoorAdDataHash = `-- name: BackfillFrontdoorAdDataHash :exec
UPDATE public.frontdoor_ads
SET frontdoor_ad_data = $1::jsonb,
    frontdoor_ad_data_hash = $2,
    frontdoor_ad_data_hash_algorithm = $3,
    frontdoor_ad_data_changed_at = COALESCE(frontdoor_ad_data_changed_at, frontdoor_ad_updated_at, frontdoor_ad_processed_at, now())
WHERE frontdoor_ad_external_id = $4
`

type BackfillFrontdoorAdDataHashParams struct {
	FrontdoorAdData              json.RawMessage `json:"frontdoor_ad_data"`
	FrontdoorAdDataHash          *string         `json:"frontdoor_ad_data_hash"`
	FrontdoorAdDataHashAlgorithm *string         `json:"frontdoor_ad_data_hash_algorithm"`
	FrontdoorAdExternalID        *string         `json:"frontdoor_ad_external_id"`
}

func (q *Queries) BackfillFrontdoorAdDataHash(ctx context.Context, arg BackfillFrontdoorAdDataHashParams) error {
	_, err := q.db.Exec(ctx, backfillFrontdoorAdDataHash,
		arg.FrontdoorAdData,
		arg.FrontdoorAdDataHash,
		arg.FrontdoorAdDataHashAlgorithm,
		arg.FrontdoorAdExternalID,
	)
	return err
}

const backfillShortcutAdDataHash = `-- name: BackfillShortcutAdDataHash :exec
UPDATE public.shortcut_ads
SET shortcut_ad_data = $1::jsonb,
    shortcut_ad_data_hash = $2,
    shortcut_ad_data_hash_algorithm = $3,
    shortcut_ad_data_changed_at = COALESCE(shortcut_ad_data_changed_at, shortcut_ad_updated_at, shortcut_ad_last_seen_at, now())
WHERE shortcut_ad_id = $4
`

type BackfillShortcutAdDataHashParams struct {
	ShortcutAdData              json.RawMessage `json:"shortcut_ad_data"`
	ShortcutAdDataHash          *string         `json:"shortcut_ad_data_hash"`
	ShortcutAdDataHashAlgorithm *string         `json:"shortcut_ad_data_hash_algorithm"`
	ShortcutAdID                *int64          `json:"shortcut_ad_id"`
}

func (q *Queries) BackfillShortcutAdDataHash(ctx context.Context, arg BackfillShortcutAdDataHashParams) error {
	_, err := q.db.Exec(ctx, backfillShortcutAdDataHash,
		arg.ShortcutAdData,
		arg.ShortcutAdDataHash,
		arg.ShortcutAdDataHashAlgorithm,
		arg.ShortcutAdID,
	)
	return err
}

const batchUpsertFrontdoorAdsFromSitemap = `-- name: BatchUpsertFrontdoorAdsFromSitemap :many
INSERT INTO public.frontdoor_ads (
    frontdoor_ad_external_id,
    frontdoor_ad_url,
    frontdoor_ad_first_seen_at,
    frontdoor_ad_last_seen_at,
    frontdoor_ad_updated_at
)
SELECT UNNEST($1::text[]), UNNEST($2::text[]), now(), now(), now()
ON CONFLICT (frontdoor_ad_external_id) DO UPDATE
SET frontdoor_ad_last_seen_at = now(),
    frontdoor_ad_url = COALESCE(EXCLUDED.frontdoor_ad_url, frontdoor_ads.frontdoor_ad_url)
RETURNING frontdoor_ad_id, frontdoor_ad_external_id, frontdoor_ad_url, frontdoor_ad_first_seen_at, frontdoor_ad_last_seen_at, frontdoor_ad_updated_at, frontdoor_ad_data, frontdoor_ad_processed_at, frontdoor_ad_page_not_found, frontdoor_ad_data_hash, frontdoor_ad_data_hash_algorithm, frontdoor_ad_data_changed_at, frontdoor_ad_data_normalized_at, frontdoor_ad_data_normalized_version
`

type BatchUpsertFrontdoorAdsFromSitemapParams struct {
	Column1 []string `json:"column_1"`
	Column2 []string `json:"column_2"`
}

type BatchUpsertFrontdoorAdsFromSitemapRow struct {
	FrontdoorAdID                    uuid.UUID       `json:"frontdoor_ad_id"`
	FrontdoorAdExternalID            string          `json:"frontdoor_ad_external_id"`
	FrontdoorAdUrl                   string          `json:"frontdoor_ad_url"`
	FrontdoorAdFirstSeenAt           time.Time       `json:"frontdoor_ad_first_seen_at"`
	FrontdoorAdLastSeenAt            time.Time       `json:"frontdoor_ad_last_seen_at"`
	FrontdoorAdUpdatedAt             time.Time       `json:"frontdoor_ad_updated_at"`
	FrontdoorAdData                  json.RawMessage `json:"frontdoor_ad_data"`
	FrontdoorAdProcessedAt           *time.Time      `json:"frontdoor_ad_processed_at"`
	FrontdoorAdPageNotFound          bool            `json:"frontdoor_ad_page_not_found"`
	FrontdoorAdDataHash              *string         `json:"frontdoor_ad_data_hash"`
	FrontdoorAdDataHashAlgorithm     string          `json:"frontdoor_ad_data_hash_algorithm"`
	FrontdoorAdDataChangedAt         *time.Time      `json:"frontdoor_ad_data_changed_at"`
	FrontdoorAdDataNormalizedAt      *time.Time      `json:"frontdoor_ad_data_normalized_at"`
	FrontdoorAdDataNormalizedVersion int32           `json:"frontdoor_ad_data_normalized_version"`
}

func (q *Queries) BatchUpsertFrontdoorAdsFromSitemap(ctx context.Context, arg BatchUpsertFrontdoorAdsFromSitemapParams) ([]BatchUpsertFrontdoorAdsFromSitemapRow, error) {
	rows, err := q.db.Query(ctx, batchUpsertFrontdoorAdsFromSitemap, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchUpsertFrontdoorAdsFromSitemapRow{}
	for rows.Next() {
		var i BatchUpsertFrontdoorAdsFromSitemapRow
		if err := rows.Scan(
			&i.FrontdoorAdID,
			&i.FrontdoorAdExternalID,
			&i.FrontdoorAdUrl,
			&i.FrontdoorAdFirstSeenAt,
			&i.FrontdoorAdLastSeenAt,
			&i.FrontdoorAdUpdatedAt,
			&i.FrontdoorAdData,
			&i.FrontdoorAdProcessedAt,
			&i.FrontdoorAdPageNotFound,
			&i.FrontdoorAdDataHash,
			&i.FrontdoorAdDataHashAlgorithm,
			&i.FrontdoorAdDataChangedAt,
			&i.FrontdoorAdDataNormalizedAt,
			&i.FrontdoorAdDataNormalizedVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const batchUpsertShortcutAdsFromSitemap = `-- name: BatchUpsertShortcutAdsFromSitemap :many
INSERT INTO public.shortcut_ads (
    shortcut_ad_id,
    shortcut_ad_url,
    shortcut_ad_type,
    shortcut_ad_last_seen_at
)
SELECT UNNEST($1::bigint[]), UNNEST($2::text[]), UNNEST($3::text[]), now()
ON CONFLICT (shortcut_ad_id) DO UPDATE SET
    shortcut_ad_url = EXCLUDED.shortcut_ad_url,
    shortcut_ad_type = EXCLUDED.shortcut_ad_type,
    shortcut_ad_last_seen_at = now()
RETURNING shortcut_ad_id, shortcut_ad_url, shortcut_ad_type, shortcut_ad_first_seen_at, shortcut_ad_last_seen_at, shortcut_ad_data, shortcut_ad_updated_at, shortcut_building_id, shortcut_ad_data_schema_version, shortcut_ad_data_hash, shortcut_ad_data_hash_algorithm, shortcut_ad_data_changed_at, shortcut_ad_data_normalized_at, shortcut_ad_data_normalized_version
`

type BatchUpsertShortcutAdsFromSitemapParams struct {
	Column1 []int64  `json:"column_1"`
	Column2 []string `json:"column_2"`
	Column3 []string `json:"column_3"`
}

type BatchUpsertShortcutAdsFromSitemapRow struct {
	ShortcutAdID                    int64           `json:"shortcut_ad_id"`
	ShortcutAdUrl                   string          `json:"shortcut_ad_url"`
	ShortcutAdType                  string          `json:"shortcut_ad_type"`
	ShortcutAdFirstSeenAt           time.Time       `json:"shortcut_ad_first_seen_at"`
	ShortcutAdLastSeenAt            time.Time       `json:"shortcut_ad_last_seen_at"`
	ShortcutAdData                  json.RawMessage `json:"shortcut_ad_data"`
	ShortcutAdUpdatedAt             *time.Time      `json:"shortcut_ad_updated_at"`
	ShortcutBuildingID              *uuid.UUID      `json:"shortcut_building_id"`
	ShortcutAdDataSchemaVersion     int16           `json:"shortcut_ad_data_schema_version"`
	ShortcutAdDataHash              *string         `json:"shortcut_ad_data_hash"`
	ShortcutAdDataHashAlgorithm     string          `json:"shortcut_ad_data_hash_algorithm"`
	ShortcutAdDataChangedAt         *time.Time      `json:"shortcut_ad_data_changed_at"`
	ShortcutAdDataNormalizedAt      *time.Time      `json:"shortcut_ad_data_normalized_at"`
	ShortcutAdDataNormalizedVersion int32           `json:"shortcut_ad_data_normalized_version"`
}

func (q *Queries) BatchUpsertShortcutAdsFromSitemap(ctx context.Context, arg BatchUpsertShortcutAdsFromSitemapParams) ([]BatchUpsertShortcutAdsFromSitemapRow, error) {
	rows, err := q.db.Query(ctx, batchUpsertShortcutAdsFromSitemap, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchUpsertShortcutAdsFromSitemapRow{}
	for rows.Next() {
		var i BatchUpsertShortcutAdsFromSitemapRow
		if err := rows.Scan(
			&i.ShortcutAdID,
			&i.ShortcutAdUrl,
			&i.ShortcutAdType,
			&i.ShortcutAdFirstSeenAt,
			&i.ShortcutAdLastSeenAt,
			&i.ShortcutAdData,
			&i.ShortcutAdUpdatedAt,
			&i.ShortcutBuildingID,
			&i.ShortcutAdDataSchemaVersion,
			&i.ShortcutAdDataHash,
			&i.ShortcutAdDataHashAlgorithm,
			&i.ShortcutAdDataChangedAt,
			&i.ShortcutAdDataNormalizedAt,
			&i.ShortcutAdDataNormalizedVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFrontdoorAdByExternalID = `-- name: GetFrontdoorAdByExternalID :one
SELECT frontdoor_ad_id, frontdoor_ad_external_id, frontdoor_ad_url, frontdoor_ad_first_seen_at, frontdoor_ad_last_seen_at, frontdoor_ad_updated_at, frontdoor_ad_data, frontdoor_ad_processed_at, frontdoor_ad_page_not_found, frontdoor_ad_data_hash, frontdoor_ad_data_hash_algorithm, frontdoor_ad_data_changed_at, frontdoor_ad_data_normalized_at, frontdoor_ad_data_normalized_version FROM public.frontdoor_ads
WHERE frontdoor_ad_external_id = $1
`

type GetFrontdoorAdByExternalIDRow struct {
	FrontdoorAdID                    uuid.UUID       `json:"frontdoor_ad_id"`
	FrontdoorAdExternalID            string          `json:"frontdoor_ad_external_id"`
	FrontdoorAdUrl                   string          `json:"frontdoor_ad_url"`
	FrontdoorAdFirstSeenAt           time.Time       `json:"frontdoor_ad_first_seen_at"`
	FrontdoorAdLastSeenAt            time.Time       `json:"frontdoor_ad_last_seen_at"`
	FrontdoorAdUpdatedAt             time.Time       `json:"frontdoor_ad_updated_at"`
	FrontdoorAdData                  json.RawMessage `json:"frontdoor_ad_data"`
	FrontdoorAdProcessedAt           *time.Time      `json:"frontdoor_ad_processed_at"`
	FrontdoorAdPageNotFound          bool            `json:"frontdoor_ad_page_not_found"`
	FrontdoorAdDataHash              *string         `json:"frontdoor_ad_data_hash"`
	FrontdoorAdDataHashAlgorithm     string          `json:"frontdoor_ad_data_hash_algorithm"`
	FrontdoorAdDataChangedAt         *time.Time      `json:"frontdoor_ad_data_changed_at"`
	FrontdoorAdDataNormalizedAt      *time.Time      `json:"frontdoor_ad_data_normalized_at"`
	FrontdoorAdDataNormalizedVersion int32           `json:"frontdoor_ad_data_normalized_version"`
}

func (q *Queries) GetFrontdoorAdByExternalID(ctx context.Context, dollar_1 *string) (GetFrontdoorAdByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getFrontdoorAdByExternalID, dollar_1)
	var i GetFrontdoorAdByExternalIDRow
	err := row.Scan(
		&i.FrontdoorAdID,
		&i.FrontdoorAdExternalID,
		&i.FrontdoorAdUrl,
		&i.FrontdoorAdFirstSeenAt,
		&i.FrontdoorAdLastSeenAt,
		&i.FrontdoorAdUpdatedAt,
		&i.FrontdoorAdData,
		&i.FrontdoorAdProcessedAt,
		&i.FrontdoorAdPageNotFound,
		&i.FrontdoorAdDataHash,
		&i.FrontdoorAdDataHashAlgorithm,
		&i.FrontdoorAdDataChangedAt,
		&i.FrontdoorAdDataNormalizedAt,
		&i.FrontdoorAdDataNormalizedVersion,
	)
	return i, err
}

const getFrontdoorAdByID = `-- name: GetFrontdoorAdByID :one
SELECT frontdoor_ad_id, frontdoor_ad_external_id, frontdoor_ad_url, frontdoor_ad_first_seen_at, frontdoor_ad_last_seen_at, frontdoor_ad_updated_at, frontdoor_ad_data, frontdoor_ad_processed_at, frontdoor_ad_page_not_found, frontdoor_ad_data_hash, frontdoor_ad_data_hash_algorithm, frontdoor_ad_data_changed_at, frontdoor_ad_data_normalized_at, frontdoor_ad_data_normalized_version FROM public.frontdoor_ads
WHERE frontdoor_ad_id = $1
`

type GetFrontdoorAdByIDRow struct {
	FrontdoorAdID                    uuid.UUID       `json:"frontdoor_ad_id"`
	FrontdoorAdExternalID            string          `json:"frontdoor_ad_external_id"`
	FrontdoorAdUrl                   string          `json:"frontdoor_ad_url"`
	FrontdoorAdFirstSeenAt           time.Time       `json:"frontdoor_ad_first_seen_at"`
	FrontdoorAdLastSeenAt            time.Time       `json:"frontdoor_ad_last_seen_at"`
	FrontdoorAdUpdatedAt             time.Time       `json:"frontdoor_ad_updated_at"`
	FrontdoorAdData                  json.RawMessage `json:"frontdoor_ad_data"`
	FrontdoorAdProcessedAt           *time.Time      `json:"frontdoor_ad_processed_at"`
	FrontdoorAdPageNotFound          bool            `json:"frontdoor_ad_page_not_found"`
	FrontdoorAdDataHash              *string         `json:"frontdoor_ad_data_hash"`
	FrontdoorAdDataHashAlgorithm     string          `json:"frontdoor_ad_data_hash_algorithm"`
	FrontdoorAdDataChangedAt         *time.Time      `json:"frontdoor_ad_data_changed_at"`
	FrontdoorAdDataNormalizedAt      *time.Time      `json:"frontdoor_ad_data_normalized_at"`
	FrontdoorAdDataNormalizedVersion int32           `json:"frontdoor_ad_data_normalized_version"`
}

func (q *Queries) GetFrontdoorAdByID(ctx context.Context, dollar_1 *uuid.UUID) (GetFrontdoorAdByIDRow, error) {
	row := q.db.QueryRow(ctx, getFrontdoorAdByID, dollar_1)
	var i GetFrontdoorAdByIDRow
	err := row.Scan(
		&i.FrontdoorAdID,
		&i.FrontdoorAdExternalID,
		&i.FrontdoorAdUrl,
		&i.FrontdoorAdFirstSeenAt,
		&i.FrontdoorAdLastSeenAt,
		&i.FrontdoorAdUpdatedAt,
		&i.FrontdoorAdData,
		&i.FrontdoorAdProcessedAt,
		&i.FrontdoorAdPageNotFound,
		&i.FrontdoorAdDataHash,
		&i.FrontdoorAdDataHashAlgorithm,
		&i.FrontdoorAdDataChangedAt,
		&i.FrontdoorAdDataNormalizedAt,
		&i.FrontdoorAdDataNormalizedVersion,
	)
	return i, err
}

const getShortcutAdByID = `-- name: GetShortcutAdByID :one
SELECT shortcut_ad_id, shortcut_ad_url, shortcut_ad_type, shortcut_ad_first_seen_at, shortcut_ad_last_seen_at, shortcut_ad_data, shortcut_ad_updated_at, shortcut_building_id, shortcut_ad_data_schema_version, shortcut_ad_data_hash, shortcut_ad_data_hash_algorithm, shortcut_ad_data_changed_at, shortcut_ad_data_normalized_at, shortcut_ad_data_normalized_version FROM public.shortcut_ads
WHERE shortcut_ad_id = $1
`

type GetShortcutAdByIDRow struct {
	ShortcutAdID                    int64           `json:"shortcut_ad_id"`
	ShortcutAdUrl                   string          `json:"shortcut_ad_url"`
	ShortcutAdType                  string          `json:"shortcut_ad_type"`
	ShortcutAdFirstSeenAt           time.Time       `json:"shortcut_ad_first_seen_at"`
	ShortcutAdLastSeenAt            time.Time       `json:"shortcut_ad_last_seen_at"`
	ShortcutAdData                  json.RawMessage `json:"shortcut_ad_data"`
	ShortcutAdUpdatedAt             *time.Time      `json:"shortcut_ad_updated_at"`
	ShortcutBuildingID              *uuid.UUID      `json:"shortcut_building_id"`
	ShortcutAdDataSchemaVersion     int16           `json:"shortcut_ad_data_schema_version"`
	ShortcutAdDataHash              *string         `json:"shortcut_ad_data_hash"`
	ShortcutAdDataHashAlgorithm     string          `json:"shortcut_ad_data_hash_algorithm"`
	ShortcutAdDataChangedAt         *time.Time      `json:"shortcut_ad_data_changed_at"`
	ShortcutAdDataNormalizedAt      *time.Time      `json:"shortcut_ad_data_normalized_at"`
	ShortcutAdDataNormalizedVersion int32           `json:"shortcut_ad_data_normalized_version"`
}

func (q *Queries) GetShortcutAdByID(ctx context.Context, dollar_1 *int64) (GetShortcutAdByIDRow, error) {
	row := q.db.QueryRow(ctx, getShortcutAdByID, dollar_1)
	var i GetShortcutAdByIDRow
	err := row.Scan(
		&i.ShortcutAdID,
		&i.ShortcutAdUrl,
		&i.ShortcutAdType,
		&i.ShortcutAdFirstSeenAt,
		&i.ShortcutAdLastSeenAt,
		&i.ShortcutAdData,
		&i.ShortcutAdUpdatedAt,
		&i.ShortcutBuildingID,
		&i.ShortcutAdDataSchemaVersion,
		&i.ShortcutAdDataHash,
		&i.ShortcutAdDataHashAlgorithm,
		&i.ShortcutAdDataChangedAt,
		&i.ShortcutAdDataNormalizedAt,
		&i.ShortcutAdDataNormalizedVersion,
	)
	return i, err
}

const listFrontdoorAds = `-- name: ListFrontdoorAds :many
SELECT frontdoor_ad_id, frontdoor_ad_external_id, frontdoor_ad_url, frontdoor_ad_first_seen_at, frontdoor_ad_last_seen_at, frontdoor_ad_updated_at, frontdoor_ad_data, frontdoor_ad_processed_at, frontdoor_ad_page_not_found, frontdoor_ad_data_hash, frontdoor_ad_data_hash_algorithm, frontdoor_ad_data_changed_at, frontdoor_ad_data_normalized_at, frontdoor_ad_data_normalized_version FROM public.frontdoor_ads
ORDER BY frontdoor_ad_last_seen_at DESC
LIMIT $1 OFFSET $2
`

type ListFrontdoorAdsParams struct {
	Column1 *int64 `json:"column_1"`
	Column2 *int64 `json:"column_2"`
}

type ListFrontdoorAdsRow struct {
	FrontdoorAdID                    uuid.UUID       `json:"frontdoor_ad_id"`
	FrontdoorAdExternalID            string          `json:"frontdoor_ad_external_id"`
	FrontdoorAdUrl                   string          `json:"frontdoor_ad_url"`
	FrontdoorAdFirstSeenAt           time.Time       `json:"frontdoor_ad_first_seen_at"`
	FrontdoorAdLastSeenAt            time.Time       `json:"frontdoor_ad_last_seen_at"`
	FrontdoorAdUpdatedAt             time.Time       `json:"frontdoor_ad_updated_at"`
	FrontdoorAdData                  json.RawMessage `json:"frontdoor_ad_data"`
	FrontdoorAdProcessedAt           *time.Time      `json:"frontdoor_ad_processed_at"`
	FrontdoorAdPageNotFound          bool            `json:"frontdoor_ad_page_not_found"`
	FrontdoorAdDataHash              *string         `json:"frontdoor_ad_data_hash"`
	FrontdoorAdDataHashAlgorithm     string          `json:"frontdoor_ad_data_hash_algorithm"`
	FrontdoorAdDataChangedAt         *time.Time      `json:"frontdoor_ad_data_changed_at"`
	FrontdoorAdDataNormalizedAt      *time.Time      `json:"frontdoor_ad_data_normalized_at"`
	FrontdoorAdDataNormalizedVersion int32           `json:"frontdoor_ad_data_normalized_version"`
}

func (q *Queries) ListFrontdoorAds(ctx context.Context, arg ListFrontdoorAdsParams) ([]ListFrontdoorAdsRow, error) {
	rows, err := q.db.Query(ctx, listFrontdoorAds, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFrontdoorAdsRow{}
	for rows.Next() {
		var i ListFrontdoorAdsRow
		if err := rows.Scan(
			&i.FrontdoorAdID,
			&i.FrontdoorAdExternalID,
			&i.FrontdoorAdUrl,
			&i.FrontdoorAdFirstSeenAt,
			&i.FrontdoorAdLastSeenAt,
			&i.FrontdoorAdUpdatedAt,
			&i.FrontdoorAdData,
			&i.FrontdoorAdProcessedAt,
			&i.FrontdoorAdPageNotFound,
			&i.FrontdoorAdDataHash,
			&i.FrontdoorAdDataHashAlgorithm,
			&i.FrontdoorAdDataChangedAt,
			&i.FrontdoorAdDataNormalizedAt,
			&i.FrontdoorAdDataNormalizedVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFrontdoorAdsMissingDataHash = `-- name: ListFrontdoorAdsMissingDataHash :many
SELECT frontdoor_ad_external_id, frontdoor_ad_data
FROM public.frontdoor_ads
WHERE frontdoor_ad_data IS NOT NULL
  AND frontdoor_ad_data_hash IS NULL
ORDER BY frontdoor_ad_updated_at ASC NULLS FIRST, frontdoor_ad_first_seen_at ASC
LIMIT $1
`

type ListFrontdoorAdsMissingDataHashRow struct {
	FrontdoorAdExternalID string          `json:"frontdoor_ad_external_id"`
	FrontdoorAdData       json.RawMessage `json:"frontdoor_ad_data"`
}

func (q *Queries) ListFrontdoorAdsMissingDataHash(ctx context.Context, dollar_1 *int64) ([]ListFrontdoorAdsMissingDataHashRow, error) {
	rows, err := q.db.Query(ctx, listFrontdoorAdsMissingDataHash, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFrontdoorAdsMissingDataHashRow{}
	for rows.Next() {
		var i ListFrontdoorAdsMissingDataHashRow
		if err := rows.Scan(&i.FrontdoorAdExternalID, &i.FrontdoorAdData); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShortcutAds = `-- name: ListShortcutAds :many
SELECT shortcut_ad_id, shortcut_ad_url, shortcut_ad_type, shortcut_ad_first_seen_at, shortcut_ad_last_seen_at, shortcut_ad_data, shortcut_ad_updated_at, shortcut_building_id, shortcut_ad_data_schema_version, shortcut_ad_data_hash, shortcut_ad_data_hash_algorithm, shortcut_ad_data_changed_at, shortcut_ad_data_normalized_at, shortcut_ad_data_normalized_version FROM public.shortcut_ads
ORDER BY shortcut_ad_last_seen_at DESC
LIMIT $1 OFFSET $2
`

type ListShortcutAdsParams struct {
	Column1 *int64 `json:"column_1"`
	Column2 *int64 `json:"column_2"`
}

type ListShortcutAdsRow struct {
	ShortcutAdID                    int64           `json:"shortcut_ad_id"`
	ShortcutAdUrl                   string          `json:"shortcut_ad_url"`
	ShortcutAdType                  string          `json:"shortcut_ad_type"`
	ShortcutAdFirstSeenAt           time.Time       `json:"shortcut_ad_first_seen_at"`
	ShortcutAdLastSeenAt            time.Time       `json:"shortcut_ad_last_seen_at"`
	ShortcutAdData                  json.RawMessage `json:"shortcut_ad_data"`
	ShortcutAdUpdatedAt             *time.Time      `json:"shortcut_ad_updated_at"`
	ShortcutBuildingID              *uuid.UUID      `json:"shortcut_building_id"`
	ShortcutAdDataSchemaVersion     int16           `json:"shortcut_ad_data_schema_version"`
	ShortcutAdDataHash              *string         `json:"shortcut_ad_data_hash"`
	ShortcutAdDataHashAlgorithm     string          `json:"shortcut_ad_data_hash_algorithm"`
	ShortcutAdDataChangedAt         *time.Time      `json:"shortcut_ad_data_changed_at"`
	ShortcutAdDataNormalizedAt      *time.Time      `json:"shortcut_ad_data_normalized_at"`
	ShortcutAdDataNormalizedVersion int32           `json:"shortcut_ad_data_normalized_version"`
}

func (q *Queries) ListShortcutAds(ctx context.Context, arg ListShortcutAdsParams) ([]ListShortcutAdsRow, error) {
	rows, err := q.db.Query(ctx, listShortcutAds, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShortcutAdsRow{}
	for rows.Next() {
		var i ListShortcutAdsRow
		if err := rows.Scan(
			&i.ShortcutAdID,
			&i.ShortcutAdUrl,
			&i.ShortcutAdType,
			&i.ShortcutAdFirstSeenAt,
			&i.ShortcutAdLastSeenAt,
			&i.ShortcutAdData,
			&i.ShortcutAdUpdatedAt,
			&i.ShortcutBuildingID,
			&i.ShortcutAdDataSchemaVersion,
			&i.ShortcutAdDataHash,
			&i.ShortcutAdDataHashAlgorithm,
			&i.ShortcutAdDataChangedAt,
			&i.ShortcutAdDataNormalizedAt,
			&i.ShortcutAdDataNormalizedVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShortcutAdsMissingDataHash = `-- name: ListShortcutAdsMissingDataHash :many
SELECT shortcut_ad_id, shortcut_ad_data
FROM public.shortcut_ads
WHERE shortcut_ad_data IS NOT NULL
  AND shortcut_ad_data_hash IS NULL
ORDER BY shortcut_ad_updated_at ASC NULLS FIRST, shortcut_ad_first_seen_at ASC
LIMIT $1
`

type ListShortcutAdsMissingDataHashRow struct {
	ShortcutAdID   int64           `json:"shortcut_ad_id"`
	ShortcutAdData json.RawMessage `json:"shortcut_ad_data"`
}

func (q *Queries) ListShortcutAdsMissingDataHash(ctx context.Context, dollar_1 *int64) ([]ListShortcutAdsMissingDataHashRow, error) {
	rows, err := q.db.Query(ctx, listShortcutAdsMissingDataHash, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShortcutAdsMissingDataHashRow{}
	for rows.Next() {
		var i ListShortcutAdsMissingDataHashRow
		if err := rows.Scan(&i.ShortcutAdID, &i.ShortcutAdData); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnprocessedFrontdoorAds = `-- name: ListUnprocessedFrontdoorAds :many
SELECT frontdoor_ad_id, frontdoor_ad_external_id, frontdoor_ad_url, frontdoor_ad_first_seen_at, frontdoor_ad_last_seen_at, frontdoor_ad_updated_at, frontdoor_ad_data, frontdoor_ad_processed_at, frontdoor_ad_page_not_found, frontdoor_ad_data_hash, frontdoor_ad_data_hash_algorithm, frontdoor_ad_data_changed_at, frontdoor_ad_data_normalized_at, frontdoor_ad_data_normalized_version FROM public.frontdoor_ads
WHERE frontdoor_ad_processed_at IS NULL AND frontdoor_ad_page_not_found = false
ORDER BY frontdoor_ad_first_seen_at ASC
LIMIT $1
`

type ListUnprocessedFrontdoorAdsRow struct {
	FrontdoorAdID                    uuid.UUID       `json:"frontdoor_ad_id"`
	FrontdoorAdExternalID            string          `json:"frontdoor_ad_external_id"`
	FrontdoorAdUrl                   string          `json:"frontdoor_ad_url"`
	FrontdoorAdFirstSeenAt           time.Time       `json:"frontdoor_ad_first_seen_at"`
	FrontdoorAdLastSeenAt            time.Time       `json:"frontdoor_ad_last_seen_at"`
	FrontdoorAdUpdatedAt             time.Time       `json:"frontdoor_ad_updated_at"`
	FrontdoorAdData                  json.RawMessage `json:"frontdoor_ad_data"`
	FrontdoorAdProcessedAt           *time.Time      `json:"frontdoor_ad_processed_at"`
	FrontdoorAdPageNotFound          bool            `json:"frontdoor_ad_page_not_found"`
	FrontdoorAdDataHash              *string         `json:"frontdoor_ad_data_hash"`
	FrontdoorAdDataHashAlgorithm     string          `json:"frontdoor_ad_data_hash_algorithm"`
	FrontdoorAdDataChangedAt         *time.Time      `json:"frontdoor_ad_data_changed_at"`
	FrontdoorAdDataNormalizedAt      *time.Time      `json:"frontdoor_ad_data_normalized_at"`
	FrontdoorAdDataNormalizedVersion int32           `json:"frontdoor_ad_data_normalized_version"`
}

func (q *Queries) ListUnprocessedFrontdoorAds(ctx context.Context, dollar_1 *int64) ([]ListUnprocessedFrontdoorAdsRow, error) {
	rows, err := q.db.Query(ctx, listUnprocessedFrontdoorAds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnprocessedFrontdoorAdsRow{}
	for rows.Next() {
		var i ListUnprocessedFrontdoorAdsRow
		if err := rows.Scan(
			&i.FrontdoorAdID,
			&i.FrontdoorAdExternalID,
			&i.FrontdoorAdUrl,
			&i.FrontdoorAdFirstSeenAt,
			&i.FrontdoorAdLastSeenAt,
			&i.FrontdoorAdUpdatedAt,
			&i.FrontdoorAdData,
			&i.FrontdoorAdProcessedAt,
			&i.FrontdoorAdPageNotFound,
			&i.FrontdoorAdDataHash,
			&i.FrontdoorAdDataHashAlgorithm,
			&i.FrontdoorAdDataChangedAt,
			&i.FrontdoorAdDataNormalizedAt,
			&i.FrontdoorAdDataNormalizedVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFrontdoorAdDataNormalized = `-- name: MarkFrontdoorAdDataNormalized :exec
UPDATE public.frontdoor_ads
SET frontdoor_ad_data_normalized_at = now(),
    frontdoor_ad_data_normalized_version = $1
WHERE frontdoor_ad_external_id = $2
  AND frontdoor_ad_data_hash IS NOT DISTINCT FROM $3
`

type MarkFrontdoorAdDataNormalizedParams struct {
	FrontdoorAdDataNormalizedVersion *int32  `json:"frontdoor_ad_data_normalized_version"`
	FrontdoorAdExternalID            *string `json:"frontdoor_ad_external_id"`
	FrontdoorAdDataHash              *string `json:"frontdoor_ad_data_hash"`
}

func (q *Queries) MarkFrontdoorAdDataNormalized(ctx context.Context, arg MarkFrontdoorAdDataNormalizedParams) error {
	_, err := q.db.Exec(ctx, markFrontdoorAdDataNormalized, arg.FrontdoorAdDataNormalizedVersion, arg.FrontdoorAdExternalID, arg.FrontdoorAdDataHash)
	return err
}

const markFrontdoorAdNotFound = `-- name: MarkFrontdoorAdNotFound :exec
UPDATE public.frontdoor_ads
SET frontdoor_ad_page_not_found = true, frontdoor_ad_updated_at = now()
WHERE frontdoor_ad_id = $1
`

func (q *Queries) MarkFrontdoorAdNotFound(ctx context.Context, dollar_1 *uuid.UUID) error {
	_, err := q.db.Exec(ctx, markFrontdoorAdNotFound, dollar_1)
	return err
}

const markFrontdoorAdNotFoundByExternalID = `-- name: MarkFrontdoorAdNotFoundByExternalID :exec
UPDATE public.frontdoor_ads
SET frontdoor_ad_page_not_found = true,
    frontdoor_ad_processed_at = NOW(),
    frontdoor_ad_updated_at = NOW()
WHERE frontdoor_ad_external_id = $1
`

func (q *Queries) MarkFrontdoorAdNotFoundByExternalID(ctx context.Context, dollar_1 *string) error {
	_, err := q.db.Exec(ctx, markFrontdoorAdNotFoundByExternalID, dollar_1)
	return err
}

const markFrontdoorAdProcessed = `-- name: MarkFrontdoorAdProcessed :exec
UPDATE public.frontdoor_ads
SET frontdoor_ad_processed_at = now(), frontdoor_ad_updated_at = now()
WHERE frontdoor_ad_id = $1
`

func (q *Queries) MarkFrontdoorAdProcessed(ctx context.Context, dollar_1 *uuid.UUID) error {
	_, err := q.db.Exec(ctx, markFrontdoorAdProcessed, dollar_1)
	return err
}

const markShortcutAdDataNormalized = `-- name: MarkShortcutAdDataNormalized :exec
UPDATE public.shortcut_ads
SET shortcut_ad_data_normalized_at = now(),
    shortcut_ad_data_normalized_version = $1
WHERE shortcut_ad_id = $2
  AND shortcut_ad_data_hash IS NOT DISTINCT FROM $3
`

type MarkShortcutAdDataNormalizedParams struct {
	ShortcutAdDataNormalizedVersion *int32  `json:"shortcut_ad_data_normalized_version"`
	ShortcutAdID                    *int64  `json:"shortcut_ad_id"`
	ShortcutAdDataHash              *string `json:"shortcut_ad_data_hash"`
}

func (q *Queries) MarkShortcutAdDataNormalized(ctx context.Context, arg MarkShortcutAdDataNormalizedParams) error {
	_, err := q.db.Exec(ctx, markShortcutAdDataNormalized, arg.ShortcutAdDataNormalizedVersion, arg.ShortcutAdID, arg.ShortcutAdDataHash)
	return err
}

const updateFrontdoorAdData = `-- name: UpdateFrontdoorAdData :exec
UPDATE public.frontdoor_ads
SET frontdoor_ad_data = $1::jsonb,
    frontdoor_ad_data_hash = $2,
    frontdoor_ad_data_hash_algorithm = $3,
    frontdoor_ad_data_changed_at = CASE WHEN frontdoor_ad_data_hash IS DISTINCT FROM $2 THEN now() ELSE frontdoor_ad_data_changed_at END,
    frontdoor_ad_data_normalized_at = CASE WHEN frontdoor_ad_data_hash IS DISTINCT FROM $2 THEN NULL ELSE frontdoor_ad_data_normalized_at END,
    frontdoor_ad_data_normalized_version = CASE WHEN frontdoor_ad_data_hash IS DISTINCT FROM $2 THEN 0 ELSE frontdoor_ad_data_normalized_version END,
    frontdoor_ad_processed_at = NOW(),
    frontdoor_ad_updated_at = NOW(),
    frontdoor_ad_page_not_found = false
WHERE frontdoor_ad_external_id = $4
`

type UpdateFrontdoorAdDataParams struct {
	FrontdoorAdData              json.RawMessage `json:"frontdoor_ad_data"`
	FrontdoorAdDataHash          *string         `json:"frontdoor_ad_data_hash"`
	FrontdoorAdDataHashAlgorithm *string         `json:"frontdoor_ad_data_hash_algorithm"`
	FrontdoorAdExternalID        *string         `json:"frontdoor_ad_external_id"`
}

func (q *Queries) UpdateFrontdoorAdData(ctx context.Context, arg UpdateFrontdoorAdDataParams) error {
	_, err := q.db.Exec(ctx, updateFrontdoorAdData,
		arg.FrontdoorAdData,
		arg.FrontdoorAdDataHash,
		arg.FrontdoorAdDataHashAlgorithm,
		arg.FrontdoorAdExternalID,
	)
	return err
}

const upsertFrontdoorAdFromSitemap = `-- name: UpsertFrontdoorAdFromSitemap :one
INSERT INTO public.frontdoor_ads (
    frontdoor_ad_external_id,
    frontdoor_ad_url,
    frontdoor_ad_first_seen_at,
    frontdoor_ad_last_seen_at,
    frontdoor_ad_updated_at
) VALUES ($1, $2, now(), now(), now())
ON CONFLICT (frontdoor_ad_external_id) DO UPDATE
SET frontdoor_ad_last_seen_at = now(),
    frontdoor_ad_url = COALESCE(EXCLUDED.frontdoor_ad_url, frontdoor_ads.frontdoor_ad_url)
RETURNING frontdoor_ad_id, frontdoor_ad_external_id, frontdoor_ad_url, frontdoor_ad_first_seen_at, frontdoor_ad_last_seen_at, frontdoor_ad_updated_at, frontdoor_ad_data, frontdoor_ad_processed_at, frontdoor_ad_page_not_found, frontdoor_ad_data_hash, frontdoor_ad_data_hash_algorithm, frontdoor_ad_data_changed_at, frontdoor_ad_data_normalized_at, frontdoor_ad_data_normalized_version
`

type UpsertFrontdoorAdFromSitemapParams struct {
	Column1 *string `json:"column_1"`
	Column2 *string `json:"column_2"`
}

type UpsertFrontdoorAdFromSitemapRow struct {
	FrontdoorAdID                    uuid.UUID       `json:"frontdoor_ad_id"`
	FrontdoorAdExternalID            string          `json:"frontdoor_ad_external_id"`
	FrontdoorAdUrl                   string          `json:"frontdoor_ad_url"`
	FrontdoorAdFirstSeenAt           time.Time       `json:"frontdoor_ad_first_seen_at"`
	FrontdoorAdLastSeenAt            time.Time       `json:"frontdoor_ad_last_seen_at"`
	FrontdoorAdUpdatedAt             time.Time       `json:"frontdoor_ad_updated_at"`
	FrontdoorAdData                  json.RawMessage `json:"frontdoor_ad_data"`
	FrontdoorAdProcessedAt           *time.Time      `json:"frontdoor_ad_processed_at"`
	FrontdoorAdPageNotFound          bool            `json:"frontdoor_ad_page_not_found"`
	FrontdoorAdDataHash              *string         `json:"frontdoor_ad_data_hash"`
	FrontdoorAdDataHashAlgorithm     string          `json:"frontdoor_ad_data_hash_algorithm"`
	FrontdoorAdDataChangedAt         *time.Time      `json:"frontdoor_ad_data_changed_at"`
	FrontdoorAdDataNormalizedAt      *time.Time      `json:"frontdoor_ad_data_normalized_at"`
	FrontdoorAdDataNormalizedVersion int32           `json:"frontdoor_ad_data_normalized_version"`
}

func (q *Queries) UpsertFrontdoorAdFromSitemap(ctx context.Context, arg UpsertFrontdoorAdFromSitemapParams) (UpsertFrontdoorAdFromSitemapRow, error) {
	row := q.db.QueryRow(ctx, upsertFrontdoorAdFromSitemap, arg.Column1, arg.Column2)
	var i UpsertFrontdoorAdFromSitemapRow
	err := row.Scan(
		&i.FrontdoorAdID,
		&i.FrontdoorAdExternalID,
		&i.FrontdoorAdUrl,
		&i.FrontdoorAdFirstSeenAt,
		&i.FrontdoorAdLastSeenAt,
		&i.FrontdoorAdUpdatedAt,
		&i.FrontdoorAdData,
		&i.FrontdoorAdProcessedAt,
		&i.FrontdoorAdPageNotFound,
		&i.FrontdoorAdDataHash,
		&i.FrontdoorAdDataHashAlgorithm,
		&i.FrontdoorAdDataChangedAt,
		&i.FrontdoorAdDataNormalizedAt,
		&i.FrontdoorAdDataNormalizedVersion,
	)
	return i, err
}

const upsertFrontdoorAds = `-- name: UpsertFrontdoorAds :exec
INSERT INTO public.frontdoor_ads (frontdoor_ad_external_id)
SELECT unnest($1::text[])
ON CONFLICT (frontdoor_ad_external_id) DO UPDATE SET
    frontdoor_ad_last_seen_at = NOW(),
    frontdoor_ad_updated_at = NOW()
`

func (q *Queries) UpsertFrontdoorAds(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, upsertFrontdoorAds, dollar_1)
	return err
}

const upsertShortcutAd = `-- name: UpsertShortcutAd :one
INSERT INTO public.shortcut_ads (
    shortcut_ad_id,
    shortcut_ad_url,
    shortcut_ad_type,
    shortcut_ad_data,
    shortcut_ad_data_hash,
    shortcut_ad_data_hash_algorithm,
    shortcut_ad_data_changed_at,
    shortcut_ad_data_schema_version,
    shortcut_building_id,
    shortcut_ad_last_seen_at
) VALUES (
    $1, $2, $3, $4::jsonb, $5, $6, now(), $7, $8, now()
)
ON CONFLICT (shortcut_ad_id) DO UPDATE SET
    shortcut_ad_url = EXCLUDED.shortcut_ad_url,
    shortcut_ad_type = EXCLUDED.shortcut_ad_type,
    shortcut_ad_data = EXCLUDED.shortcut_ad_data,
    shortcut_ad_data_hash = EXCLUDED.shortcut_ad_data_hash,
    shortcut_ad_data_hash_algorithm = EXCLUDED.shortcut_ad_data_hash_algorithm,
    shortcut_ad_data_changed_at = CASE WHEN shortcut_ads.shortcut_ad_data_hash IS DISTINCT FROM EXCLUDED.shortcut_ad_data_hash THEN now() ELSE shortcut_ads.shortcut_ad_data_changed_at END,
    shortcut_ad_data_normalized_at = CASE WHEN shortcut_ads.shortcut_ad_data_hash IS DISTINCT FROM EXCLUDED.shortcut_ad_data_hash THEN NULL ELSE shortcut_ads.shortcut_ad_data_normalized_at END,
    shortcut_ad_data_normalized_version = CASE WHEN shortcut_ads.shortcut_ad_data_hash IS DISTINCT FROM EXCLUDED.shortcut_ad_data_hash THEN 0 ELSE shortcut_ads.shortcut_ad_data_normalized_version END,
    shortcut_ad_data_schema_version = EXCLUDED.shortcut_ad_data_schema_version,
    shortcut_building_id = EXCLUDED.shortcut_building_id,
    shortcut_ad_last_seen_at = now(),
    shortcut_ad_updated_at = CURRENT_TIMESTAMP
RETURNING shortcut_ad_id, shortcut_ad_url, shortcut_ad_type, shortcut_ad_first_seen_at, shortcut_ad_last_seen_at, shortcut_ad_data, shortcut_ad_updated_at, shortcut_building_id, shortcut_ad_data_schema_version, shortcut_ad_data_hash, shortcut_ad_data_hash_algorithm, shortcut_ad_data_changed_at, shortcut_ad_data_normalized_at, shortcut_ad_data_normalized_version
`

type UpsertShortcutAdParams struct {
	ShortcutAdID                *int64          `json:"shortcut_ad_id"`
	ShortcutAdUrl               *string         `json:"shortcut_ad_url"`
	ShortcutAdType              *string         `json:"shortcut_ad_type"`
	ShortcutAdData              json.RawMessage `json:"shortcut_ad_data"`
	ShortcutAdDataHash          *string         `json:"shortcut_ad_data_hash"`
	ShortcutAdDataHashAlgorithm *string         `json:"shortcut_ad_data_hash_algorithm"`
	ShortcutAdDataSchemaVersion *int16          `json:"shortcut_ad_data_schema_version"`
	ShortcutBuildingID          *uuid.UUID      `json:"shortcut_building_id"`
}

type UpsertShortcutAdRow struct {
	ShortcutAdID                    int64           `json:"shortcut_ad_id"`
	ShortcutAdUrl                   string          `json:"shortcut_ad_url"`
	ShortcutAdType                  string          `json:"shortcut_ad_type"`
	ShortcutAdFirstSeenAt           time.Time       `json:"shortcut_ad_first_seen_at"`
	ShortcutAdLastSeenAt            time.Time       `json:"shortcut_ad_last_seen_at"`
	ShortcutAdData                  json.RawMessage `json:"shortcut_ad_data"`
	ShortcutAdUpdatedAt             *time.Time      `json:"shortcut_ad_updated_at"`
	ShortcutBuildingID              *uuid.UUID      `json:"shortcut_building_id"`
	ShortcutAdDataSchemaVersion     int16           `json:"shortcut_ad_data_schema_version"`
	ShortcutAdDataHash              *string         `json:"shortcut_ad_data_hash"`
	ShortcutAdDataHashAlgorithm     string          `json:"shortcut_ad_data_hash_algorithm"`
	ShortcutAdDataChangedAt         *time.Time      `json:"shortcut_ad_data_changed_at"`
	ShortcutAdDataNormalizedAt      *time.Time      `json:"shortcut_ad_data_normalized_at"`
	ShortcutAdDataNormalizedVersion int32           `json:"shortcut_ad_data_normalized_version"`
}

func (q *Queries) UpsertShortcutAd(ctx context.Context, arg UpsertShortcutAdParams) (UpsertShortcutAdRow, error) {
	row := q.db.QueryRow(ctx, upsertShortcutAd,
		arg.ShortcutAdID,
		arg.ShortcutAdUrl,
		arg.ShortcutAdType,
		arg.ShortcutAdData,
		arg.ShortcutAdDataHash,
		arg.ShortcutAdDataHashAlgorithm,
		arg.ShortcutAdDataSchemaVersion,
		arg.ShortcutBuildingID,
	)
	var i UpsertShortcutAdRow
	err := row.Scan(
		&i.ShortcutAdID,
		&i.ShortcutAdUrl,
		&i.ShortcutAdType,
		&i.ShortcutAdFirstSeenAt,
		&i.ShortcutAdLastSeenAt,
		&i.ShortcutAdData,
		&i.ShortcutAdUpdatedAt,
		&i.ShortcutBuildingID,
		&i.ShortcutAdDataSchemaVersion,
		&i.ShortcutAdDataHash,
		&i.ShortcutAdDataHashAlgorithm,
		&i.ShortcutAdDataChangedAt,
		&i.ShortcutAdDataNormalizedAt,
		&i.ShortcutAdDataNormalizedVersion,
	)
	return i, err
}

const upsertShortcutAdFromSitemap = `-- name: UpsertShortcutAdFromSitemap :one
INSERT INTO public.shortcut_ads (
    shortcut_ad_id,
    shortcut_ad_url,
    shortcut_ad_type,
    shortcut_ad_last_seen_at
) VALUES (
    $1, $2, $3, now()
)
ON CONFLICT (shortcut_ad_id) DO UPDATE SET
    shortcut_ad_url = EXCLUDED.shortcut_ad_url,
    shortcut_ad_type = EXCLUDED.shortcut_ad_type,
    shortcut_ad_last_seen_at = now()
RETURNING shortcut_ad_id, shortcut_ad_url, shortcut_ad_type, shortcut_ad_first_seen_at, shortcut_ad_last_seen_at, shortcut_ad_data, shortcut_ad_updated_at, shortcut_building_id, shortcut_ad_data_schema_version, shortcut_ad_data_hash, shortcut_ad_data_hash_algorithm, shortcut_ad_data_changed_at, shortcut_ad_data_normalized_at, shortcut_ad_data_normalized_version
`

type UpsertShortcutAdFromSitemapParams struct {
	Column1 *int64  `json:"column_1"`
	Column2 *string `json:"column_2"`
	Column3 *string `json:"column_3"`
}

type UpsertShortcutAdFromSitemapRow struct {
	ShortcutAdID                    int64           `json:"shortcut_ad_id"`
	ShortcutAdUrl                   string          `json:"shortcut_ad_url"`
	ShortcutAdType                  string          `json:"shortcut_ad_type"`
	ShortcutAdFirstSeenAt           time.Time       `json:"shortcut_ad_first_seen_at"`
	ShortcutAdLastSeenAt            time.Time       `json:"shortcut_ad_last_seen_at"`
	ShortcutAdData                  json.RawMessage `json:"shortcut_ad_data"`
	ShortcutAdUpdatedAt             *time.Time      `json:"shortcut_ad_updated_at"`
	ShortcutBuildingID              *uuid.UUID      `json:"shortcut_building_id"`
	ShortcutAdDataSchemaVersion     int16           `json:"shortcut_ad_data_schema_version"`
	ShortcutAdDataHash              *string         `json:"shortcut_ad_data_hash"`
	ShortcutAdDataHashAlgorithm     string          `json:"shortcut_ad_data_hash_algorithm"`
	ShortcutAdDataChangedAt         *time.Time      `json:"shortcut_ad_data_changed_at"`
	ShortcutAdDataNormalizedAt      *time.Time      `json:"shortcut_ad_data_normalized_at"`
	ShortcutAdDataNormalizedVersion int32           `json:"shortcut_ad_data_normalized_version"`
}

func (q *Queries) UpsertShortcutAdFromSitemap(ctx context.Context, arg UpsertShortcutAdFromSitemapParams) (UpsertShortcutAdFromSitemapRow, error) {
	row := q.db.QueryRow(ctx, upsertShortcutAdFromSitemap, arg.Column1, arg.Column2, arg.Column3)
	var i UpsertShortcutAdFromSitemapRow
	err := row.Scan(
		&i.ShortcutAdID,
		&i.ShortcutAdUrl,
		&i.ShortcutAdType,
		&i.ShortcutAdFirstSeenAt,
		&i.ShortcutAdLastSeenAt,
		&i.ShortcutAdData,
		&i.ShortcutAdUpdatedAt,
		&i.ShortcutBuildingID,
		&i.ShortcutAdDataSchemaVersion,
		&i.ShortcutAdDataHash,
		&i.ShortcutAdDataHashAlgorithm,
		&i.ShortcutAdDataChangedAt,
		&i.ShortcutAdDataNormalizedAt,
		&i.ShortcutAdDataNormalizedVersion,
	)
	return i, err
}
