// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: announcements.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getFrontdoorBuildingAnnouncementByID = `-- name: GetFrontdoorBuildingAnnouncementByID :one
SELECT frontdoor_building_announcement_id, frontdoor_building_announcement_external_id, frontdoor_building_announcement_friendly_id, frontdoor_building_announcement_unpublishing_time, frontdoor_building_announcement_address_line1, frontdoor_building_announcement_address_line2, frontdoor_building_announcement_location, frontdoor_building_announcement_search_price, frontdoor_building_announcement_notify_price_changed, frontdoor_building_announcement_property_type, frontdoor_building_announcement_property_subtype, frontdoor_building_announcement_construction_finished_year, frontdoor_building_announcement_main_image_uri, frontdoor_building_announcement_has_open_bidding, frontdoor_building_announcement_room_structure, frontdoor_building_announcement_area, frontdoor_building_announcement_total_area, frontdoor_building_announcement_price_per_square, frontdoor_building_announcement_days_on_market, frontdoor_building_announcement_new_building, frontdoor_building_announcement_main_image_hidden, frontdoor_building_announcement_is_company_announcement, frontdoor_building_announcement_show_bidding_indicators, frontdoor_building_announcement_published, frontdoor_building_announcement_rent_period, frontdoor_building_announcement_rental_unique_no, frontdoor_building_id, frontdoor_building_announcement_first_seen_at, frontdoor_building_announcement_last_seen_at, frontdoor_building_announcement_unpublishing_time_date FROM public.frontdoor_building_announcements
WHERE frontdoor_building_announcement_id = $1
`

func (q *Queries) GetFrontdoorBuildingAnnouncementByID(ctx context.Context, frontdoorBuildingAnnouncementID uuid.UUID) (FrontdoorBuildingAnnouncement, error) {
	row := q.db.QueryRow(ctx, getFrontdoorBuildingAnnouncementByID, frontdoorBuildingAnnouncementID)
	var i FrontdoorBuildingAnnouncement
	err := row.Scan(
		&i.FrontdoorBuildingAnnouncementID,
		&i.FrontdoorBuildingAnnouncementExternalID,
		&i.FrontdoorBuildingAnnouncementFriendlyID,
		&i.FrontdoorBuildingAnnouncementUnpublishingTime,
		&i.FrontdoorBuildingAnnouncementAddressLine1,
		&i.FrontdoorBuildingAnnouncementAddressLine2,
		&i.FrontdoorBuildingAnnouncementLocation,
		&i.FrontdoorBuildingAnnouncementSearchPrice,
		&i.FrontdoorBuildingAnnouncementNotifyPriceChanged,
		&i.FrontdoorBuildingAnnouncementPropertyType,
		&i.FrontdoorBuildingAnnouncementPropertySubtype,
		&i.FrontdoorBuildingAnnouncementConstructionFinishedYear,
		&i.FrontdoorBuildingAnnouncementMainImageUri,
		&i.FrontdoorBuildingAnnouncementHasOpenBidding,
		&i.FrontdoorBuildingAnnouncementRoomStructure,
		&i.FrontdoorBuildingAnnouncementArea,
		&i.FrontdoorBuildingAnnouncementTotalArea,
		&i.FrontdoorBuildingAnnouncementPricePerSquare,
		&i.FrontdoorBuildingAnnouncementDaysOnMarket,
		&i.FrontdoorBuildingAnnouncementNewBuilding,
		&i.FrontdoorBuildingAnnouncementMainImageHidden,
		&i.FrontdoorBuildingAnnouncementIsCompanyAnnouncement,
		&i.FrontdoorBuildingAnnouncementShowBiddingIndicators,
		&i.FrontdoorBuildingAnnouncementPublished,
		&i.FrontdoorBuildingAnnouncementRentPeriod,
		&i.FrontdoorBuildingAnnouncementRentalUniqueNo,
		&i.FrontdoorBuildingID,
		&i.FrontdoorBuildingAnnouncementFirstSeenAt,
		&i.FrontdoorBuildingAnnouncementLastSeenAt,
		&i.FrontdoorBuildingAnnouncementUnpublishingTimeDate,
	)
	return i, err
}

const listFrontdoorBuildingAnnouncements = `-- name: ListFrontdoorBuildingAnnouncements :many
SELECT frontdoor_building_announcement_id, frontdoor_building_announcement_external_id, frontdoor_building_announcement_friendly_id, frontdoor_building_announcement_unpublishing_time, frontdoor_building_announcement_address_line1, frontdoor_building_announcement_address_line2, frontdoor_building_announcement_location, frontdoor_building_announcement_search_price, frontdoor_building_announcement_notify_price_changed, frontdoor_building_announcement_property_type, frontdoor_building_announcement_property_subtype, frontdoor_building_announcement_construction_finished_year, frontdoor_building_announcement_main_image_uri, frontdoor_building_announcement_has_open_bidding, frontdoor_building_announcement_room_structure, frontdoor_building_announcement_area, frontdoor_building_announcement_total_area, frontdoor_building_announcement_price_per_square, frontdoor_building_announcement_days_on_market, frontdoor_building_announcement_new_building, frontdoor_building_announcement_main_image_hidden, frontdoor_building_announcement_is_company_announcement, frontdoor_building_announcement_show_bidding_indicators, frontdoor_building_announcement_published, frontdoor_building_announcement_rent_period, frontdoor_building_announcement_rental_unique_no, frontdoor_building_id, frontdoor_building_announcement_first_seen_at, frontdoor_building_announcement_last_seen_at, frontdoor_building_announcement_unpublishing_time_date FROM public.frontdoor_building_announcements
WHERE frontdoor_building_id = $1
ORDER BY frontdoor_building_announcement_last_seen_at DESC
`

func (q *Queries) ListFrontdoorBuildingAnnouncements(ctx context.Context, frontdoorBuildingID uuid.UUID) ([]FrontdoorBuildingAnnouncement, error) {
	rows, err := q.db.Query(ctx, listFrontdoorBuildingAnnouncements, frontdoorBuildingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FrontdoorBuildingAnnouncement{}
	for rows.Next() {
		var i FrontdoorBuildingAnnouncement
		if err := rows.Scan(
			&i.FrontdoorBuildingAnnouncementID,
			&i.FrontdoorBuildingAnnouncementExternalID,
			&i.FrontdoorBuildingAnnouncementFriendlyID,
			&i.FrontdoorBuildingAnnouncementUnpublishingTime,
			&i.FrontdoorBuildingAnnouncementAddressLine1,
			&i.FrontdoorBuildingAnnouncementAddressLine2,
			&i.FrontdoorBuildingAnnouncementLocation,
			&i.FrontdoorBuildingAnnouncementSearchPrice,
			&i.FrontdoorBuildingAnnouncementNotifyPriceChanged,
			&i.FrontdoorBuildingAnnouncementPropertyType,
			&i.FrontdoorBuildingAnnouncementPropertySubtype,
			&i.FrontdoorBuildingAnnouncementConstructionFinishedYear,
			&i.FrontdoorBuildingAnnouncementMainImageUri,
			&i.FrontdoorBuildingAnnouncementHasOpenBidding,
			&i.FrontdoorBuildingAnnouncementRoomStructure,
			&i.FrontdoorBuildingAnnouncementArea,
			&i.FrontdoorBuildingAnnouncementTotalArea,
			&i.FrontdoorBuildingAnnouncementPricePerSquare,
			&i.FrontdoorBuildingAnnouncementDaysOnMarket,
			&i.FrontdoorBuildingAnnouncementNewBuilding,
			&i.FrontdoorBuildingAnnouncementMainImageHidden,
			&i.FrontdoorBuildingAnnouncementIsCompanyAnnouncement,
			&i.FrontdoorBuildingAnnouncementShowBiddingIndicators,
			&i.FrontdoorBuildingAnnouncementPublished,
			&i.FrontdoorBuildingAnnouncementRentPeriod,
			&i.FrontdoorBuildingAnnouncementRentalUniqueNo,
			&i.FrontdoorBuildingID,
			&i.FrontdoorBuildingAnnouncementFirstSeenAt,
			&i.FrontdoorBuildingAnnouncementLastSeenAt,
			&i.FrontdoorBuildingAnnouncementUnpublishingTimeDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFrontdoorBuildingAnnouncement = `-- name: UpsertFrontdoorBuildingAnnouncement :one
INSERT INTO public.frontdoor_building_announcements (
    frontdoor_building_announcement_external_id,
    frontdoor_building_announcement_friendly_id,
    frontdoor_building_announcement_unpublishing_time,
    frontdoor_building_announcement_address_line1,
    frontdoor_building_announcement_address_line2,
    frontdoor_building_announcement_location,
    frontdoor_building_announcement_search_price,
    frontdoor_building_announcement_notify_price_changed,
    frontdoor_building_announcement_property_type,
    frontdoor_building_announcement_property_subtype,
    frontdoor_building_announcement_construction_finished_year,
    frontdoor_building_announcement_main_image_uri,
    frontdoor_building_announcement_has_open_bidding,
    frontdoor_building_announcement_room_structure,
    frontdoor_building_announcement_area,
    frontdoor_building_announcement_total_area,
    frontdoor_building_announcement_price_per_square,
    frontdoor_building_announcement_days_on_market,
    frontdoor_building_announcement_new_building,
    frontdoor_building_announcement_main_image_hidden,
    frontdoor_building_announcement_is_company_announcement,
    frontdoor_building_announcement_show_bidding_indicators,
    frontdoor_building_announcement_published,
    frontdoor_building_announcement_rent_period,
    frontdoor_building_announcement_rental_unique_no,
    frontdoor_building_id,
    frontdoor_building_announcement_first_seen_at,
    frontdoor_building_announcement_last_seen_at,
    frontdoor_building_announcement_unpublishing_time_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, now(), now(), $27
)
ON CONFLICT (frontdoor_building_announcement_external_id, frontdoor_building_announcement_unpublishing_time, frontdoor_building_announcement_search_price) DO UPDATE
SET frontdoor_building_announcement_last_seen_at = now(),
    frontdoor_building_announcement_friendly_id = COALESCE(EXCLUDED.frontdoor_building_announcement_friendly_id, frontdoor_building_announcements.frontdoor_building_announcement_friendly_id),
    frontdoor_building_announcement_address_line1 = COALESCE(EXCLUDED.frontdoor_building_announcement_address_line1, frontdoor_building_announcements.frontdoor_building_announcement_address_line1),
    frontdoor_building_announcement_address_line2 = COALESCE(EXCLUDED.frontdoor_building_announcement_address_line2, frontdoor_building_announcements.frontdoor_building_announcement_address_line2),
    frontdoor_building_announcement_location = COALESCE(EXCLUDED.frontdoor_building_announcement_location, frontdoor_building_announcements.frontdoor_building_announcement_location),
    frontdoor_building_announcement_notify_price_changed = COALESCE(EXCLUDED.frontdoor_building_announcement_notify_price_changed, frontdoor_building_announcements.frontdoor_building_announcement_notify_price_changed),
    frontdoor_building_announcement_property_type = COALESCE(EXCLUDED.frontdoor_building_announcement_property_type, frontdoor_building_announcements.frontdoor_building_announcement_property_type),
    frontdoor_building_announcement_property_subtype = COALESCE(EXCLUDED.frontdoor_building_announcement_property_subtype, frontdoor_building_announcements.frontdoor_building_announcement_property_subtype),
    frontdoor_building_announcement_construction_finished_year = COALESCE(EXCLUDED.frontdoor_building_announcement_construction_finished_year, frontdoor_building_announcements.frontdoor_building_announcement_construction_finished_year),
    frontdoor_building_announcement_main_image_uri = COALESCE(EXCLUDED.frontdoor_building_announcement_main_image_uri, frontdoor_building_announcements.frontdoor_building_announcement_main_image_uri),
    frontdoor_building_announcement_has_open_bidding = COALESCE(EXCLUDED.frontdoor_building_announcement_has_open_bidding, frontdoor_building_announcements.frontdoor_building_announcement_has_open_bidding),
    frontdoor_building_announcement_room_structure = COALESCE(EXCLUDED.frontdoor_building_announcement_room_structure, frontdoor_building_announcements.frontdoor_building_announcement_room_structure),
    frontdoor_building_announcement_area = COALESCE(EXCLUDED.frontdoor_building_announcement_area, frontdoor_building_announcements.frontdoor_building_announcement_area),
    frontdoor_building_announcement_total_area = COALESCE(EXCLUDED.frontdoor_building_announcement_total_area, frontdoor_building_announcements.frontdoor_building_announcement_total_area),
    frontdoor_building_announcement_price_per_square = COALESCE(EXCLUDED.frontdoor_building_announcement_price_per_square, frontdoor_building_announcements.frontdoor_building_announcement_price_per_square),
    frontdoor_building_announcement_days_on_market = COALESCE(EXCLUDED.frontdoor_building_announcement_days_on_market, frontdoor_building_announcements.frontdoor_building_announcement_days_on_market),
    frontdoor_building_announcement_new_building = COALESCE(EXCLUDED.frontdoor_building_announcement_new_building, frontdoor_building_announcements.frontdoor_building_announcement_new_building),
    frontdoor_building_announcement_main_image_hidden = COALESCE(EXCLUDED.frontdoor_building_announcement_main_image_hidden, frontdoor_building_announcements.frontdoor_building_announcement_main_image_hidden),
    frontdoor_building_announcement_is_company_announcement = COALESCE(EXCLUDED.frontdoor_building_announcement_is_company_announcement, frontdoor_building_announcements.frontdoor_building_announcement_is_company_announcement),
    frontdoor_building_announcement_show_bidding_indicators = COALESCE(EXCLUDED.frontdoor_building_announcement_show_bidding_indicators, frontdoor_building_announcements.frontdoor_building_announcement_show_bidding_indicators),
    frontdoor_building_announcement_published = COALESCE(EXCLUDED.frontdoor_building_announcement_published, frontdoor_building_announcements.frontdoor_building_announcement_published),
    frontdoor_building_announcement_rent_period = COALESCE(EXCLUDED.frontdoor_building_announcement_rent_period, frontdoor_building_announcements.frontdoor_building_announcement_rent_period),
    frontdoor_building_announcement_rental_unique_no = COALESCE(EXCLUDED.frontdoor_building_announcement_rental_unique_no, frontdoor_building_announcements.frontdoor_building_announcement_rental_unique_no),
    frontdoor_building_announcement_unpublishing_time_date = COALESCE(EXCLUDED.frontdoor_building_announcement_unpublishing_time_date, frontdoor_building_announcements.frontdoor_building_announcement_unpublishing_time_date)
RETURNING frontdoor_building_announcement_id, frontdoor_building_announcement_external_id, frontdoor_building_announcement_friendly_id, frontdoor_building_announcement_unpublishing_time, frontdoor_building_announcement_address_line1, frontdoor_building_announcement_address_line2, frontdoor_building_announcement_location, frontdoor_building_announcement_search_price, frontdoor_building_announcement_notify_price_changed, frontdoor_building_announcement_property_type, frontdoor_building_announcement_property_subtype, frontdoor_building_announcement_construction_finished_year, frontdoor_building_announcement_main_image_uri, frontdoor_building_announcement_has_open_bidding, frontdoor_building_announcement_room_structure, frontdoor_building_announcement_area, frontdoor_building_announcement_total_area, frontdoor_building_announcement_price_per_square, frontdoor_building_announcement_days_on_market, frontdoor_building_announcement_new_building, frontdoor_building_announcement_main_image_hidden, frontdoor_building_announcement_is_company_announcement, frontdoor_building_announcement_show_bidding_indicators, frontdoor_building_announcement_published, frontdoor_building_announcement_rent_period, frontdoor_building_announcement_rental_unique_no, frontdoor_building_id, frontdoor_building_announcement_first_seen_at, frontdoor_building_announcement_last_seen_at, frontdoor_building_announcement_unpublishing_time_date
`

type UpsertFrontdoorBuildingAnnouncementParams struct {
	FrontdoorBuildingAnnouncementExternalID               *int32     `json:"frontdoor_building_announcement_external_id"`
	FrontdoorBuildingAnnouncementFriendlyID               *string    `json:"frontdoor_building_announcement_friendly_id"`
	FrontdoorBuildingAnnouncementUnpublishingTime         *float64   `json:"frontdoor_building_announcement_unpublishing_time"`
	FrontdoorBuildingAnnouncementAddressLine1             *string    `json:"frontdoor_building_announcement_address_line1"`
	FrontdoorBuildingAnnouncementAddressLine2             *string    `json:"frontdoor_building_announcement_address_line2"`
	FrontdoorBuildingAnnouncementLocation                 *string    `json:"frontdoor_building_announcement_location"`
	FrontdoorBuildingAnnouncementSearchPrice              *float64   `json:"frontdoor_building_announcement_search_price"`
	FrontdoorBuildingAnnouncementNotifyPriceChanged       *bool      `json:"frontdoor_building_announcement_notify_price_changed"`
	FrontdoorBuildingAnnouncementPropertyType             *string    `json:"frontdoor_building_announcement_property_type"`
	FrontdoorBuildingAnnouncementPropertySubtype          *string    `json:"frontdoor_building_announcement_property_subtype"`
	FrontdoorBuildingAnnouncementConstructionFinishedYear *int32     `json:"frontdoor_building_announcement_construction_finished_year"`
	FrontdoorBuildingAnnouncementMainImageUri             *string    `json:"frontdoor_building_announcement_main_image_uri"`
	FrontdoorBuildingAnnouncementHasOpenBidding           *bool      `json:"frontdoor_building_announcement_has_open_bidding"`
	FrontdoorBuildingAnnouncementRoomStructure            *string    `json:"frontdoor_building_announcement_room_structure"`
	FrontdoorBuildingAnnouncementArea                     *float64   `json:"frontdoor_building_announcement_area"`
	FrontdoorBuildingAnnouncementTotalArea                *float64   `json:"frontdoor_building_announcement_total_area"`
	FrontdoorBuildingAnnouncementPricePerSquare           *float64   `json:"frontdoor_building_announcement_price_per_square"`
	FrontdoorBuildingAnnouncementDaysOnMarket             *int32     `json:"frontdoor_building_announcement_days_on_market"`
	FrontdoorBuildingAnnouncementNewBuilding              *bool      `json:"frontdoor_building_announcement_new_building"`
	FrontdoorBuildingAnnouncementMainImageHidden          *bool      `json:"frontdoor_building_announcement_main_image_hidden"`
	FrontdoorBuildingAnnouncementIsCompanyAnnouncement    *bool      `json:"frontdoor_building_announcement_is_company_announcement"`
	FrontdoorBuildingAnnouncementShowBiddingIndicators    *bool      `json:"frontdoor_building_announcement_show_bidding_indicators"`
	FrontdoorBuildingAnnouncementPublished                *bool      `json:"frontdoor_building_announcement_published"`
	FrontdoorBuildingAnnouncementRentPeriod               *string    `json:"frontdoor_building_announcement_rent_period"`
	FrontdoorBuildingAnnouncementRentalUniqueNo           *int32     `json:"frontdoor_building_announcement_rental_unique_no"`
	FrontdoorBuildingID                                   uuid.UUID  `json:"frontdoor_building_id"`
	FrontdoorBuildingAnnouncementUnpublishingTimeDate     *time.Time `json:"frontdoor_building_announcement_unpublishing_time_date"`
}

func (q *Queries) UpsertFrontdoorBuildingAnnouncement(ctx context.Context, arg UpsertFrontdoorBuildingAnnouncementParams) (FrontdoorBuildingAnnouncement, error) {
	row := q.db.QueryRow(ctx, upsertFrontdoorBuildingAnnouncement,
		arg.FrontdoorBuildingAnnouncementExternalID,
		arg.FrontdoorBuildingAnnouncementFriendlyID,
		arg.FrontdoorBuildingAnnouncementUnpublishingTime,
		arg.FrontdoorBuildingAnnouncementAddressLine1,
		arg.FrontdoorBuildingAnnouncementAddressLine2,
		arg.FrontdoorBuildingAnnouncementLocation,
		arg.FrontdoorBuildingAnnouncementSearchPrice,
		arg.FrontdoorBuildingAnnouncementNotifyPriceChanged,
		arg.FrontdoorBuildingAnnouncementPropertyType,
		arg.FrontdoorBuildingAnnouncementPropertySubtype,
		arg.FrontdoorBuildingAnnouncementConstructionFinishedYear,
		arg.FrontdoorBuildingAnnouncementMainImageUri,
		arg.FrontdoorBuildingAnnouncementHasOpenBidding,
		arg.FrontdoorBuildingAnnouncementRoomStructure,
		arg.FrontdoorBuildingAnnouncementArea,
		arg.FrontdoorBuildingAnnouncementTotalArea,
		arg.FrontdoorBuildingAnnouncementPricePerSquare,
		arg.FrontdoorBuildingAnnouncementDaysOnMarket,
		arg.FrontdoorBuildingAnnouncementNewBuilding,
		arg.FrontdoorBuildingAnnouncementMainImageHidden,
		arg.FrontdoorBuildingAnnouncementIsCompanyAnnouncement,
		arg.FrontdoorBuildingAnnouncementShowBiddingIndicators,
		arg.FrontdoorBuildingAnnouncementPublished,
		arg.FrontdoorBuildingAnnouncementRentPeriod,
		arg.FrontdoorBuildingAnnouncementRentalUniqueNo,
		arg.FrontdoorBuildingID,
		arg.FrontdoorBuildingAnnouncementUnpublishingTimeDate,
	)
	var i FrontdoorBuildingAnnouncement
	err := row.Scan(
		&i.FrontdoorBuildingAnnouncementID,
		&i.FrontdoorBuildingAnnouncementExternalID,
		&i.FrontdoorBuildingAnnouncementFriendlyID,
		&i.FrontdoorBuildingAnnouncementUnpublishingTime,
		&i.FrontdoorBuildingAnnouncementAddressLine1,
		&i.FrontdoorBuildingAnnouncementAddressLine2,
		&i.FrontdoorBuildingAnnouncementLocation,
		&i.FrontdoorBuildingAnnouncementSearchPrice,
		&i.FrontdoorBuildingAnnouncementNotifyPriceChanged,
		&i.FrontdoorBuildingAnnouncementPropertyType,
		&i.FrontdoorBuildingAnnouncementPropertySubtype,
		&i.FrontdoorBuildingAnnouncementConstructionFinishedYear,
		&i.FrontdoorBuildingAnnouncementMainImageUri,
		&i.FrontdoorBuildingAnnouncementHasOpenBidding,
		&i.FrontdoorBuildingAnnouncementRoomStructure,
		&i.FrontdoorBuildingAnnouncementArea,
		&i.FrontdoorBuildingAnnouncementTotalArea,
		&i.FrontdoorBuildingAnnouncementPricePerSquare,
		&i.FrontdoorBuildingAnnouncementDaysOnMarket,
		&i.FrontdoorBuildingAnnouncementNewBuilding,
		&i.FrontdoorBuildingAnnouncementMainImageHidden,
		&i.FrontdoorBuildingAnnouncementIsCompanyAnnouncement,
		&i.FrontdoorBuildingAnnouncementShowBiddingIndicators,
		&i.FrontdoorBuildingAnnouncementPublished,
		&i.FrontdoorBuildingAnnouncementRentPeriod,
		&i.FrontdoorBuildingAnnouncementRentalUniqueNo,
		&i.FrontdoorBuildingID,
		&i.FrontdoorBuildingAnnouncementFirstSeenAt,
		&i.FrontdoorBuildingAnnouncementLastSeenAt,
		&i.FrontdoorBuildingAnnouncementUnpublishingTimeDate,
	)
	return i, err
}
