// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attempts.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const finalizeRunningSyncJobAttemptsForJobs = `-- name: FinalizeRunningSyncJobAttemptsForJobs :execrows
UPDATE public.sync_job_attempts
SET sync_job_attempt_status = 'retry',
    sync_job_attempt_error_code = 'stale_claim_recovered',
    sync_job_attempt_error_detail = 'stale in_progress sync job claim was reset',
    sync_job_attempt_finished_at = now()
WHERE sync_job_id = ANY($1::uuid[])
  AND sync_job_attempt_status = 'running'
`

func (q *Queries) FinalizeRunningSyncJobAttemptsForJobs(ctx context.Context, syncJobIds []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, finalizeRunningSyncJobAttemptsForJobs, syncJobIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finalizeSyncJobAttempt = `-- name: FinalizeSyncJobAttempt :exec
UPDATE public.sync_job_attempts
SET sync_job_attempt_status = $1,
    sync_job_attempt_error_code = $2,
    sync_job_attempt_error_detail = $3,
    sync_job_attempt_finished_at = now()
WHERE sync_job_attempt_id = $4
`

type FinalizeSyncJobAttemptParams struct {
	SyncJobAttemptStatus      string  `json:"sync_job_attempt_status"`
	SyncJobAttemptErrorCode   *string `json:"sync_job_attempt_error_code"`
	SyncJobAttemptErrorDetail *string `json:"sync_job_attempt_error_detail"`
	SyncJobAttemptID          int64   `json:"sync_job_attempt_id"`
}

func (q *Queries) FinalizeSyncJobAttempt(ctx context.Context, arg FinalizeSyncJobAttemptParams) error {
	_, err := q.db.Exec(ctx, finalizeSyncJobAttempt,
		arg.SyncJobAttemptStatus,
		arg.SyncJobAttemptErrorCode,
		arg.SyncJobAttemptErrorDetail,
		arg.SyncJobAttemptID,
	)
	return err
}

const insertSyncJobAttemptRunning = `-- name: InsertSyncJobAttemptRunning :one
INSERT INTO public.sync_job_attempts (
    sync_job_id,
    sync_job_attempt_queue_name,
    sync_job_attempt_msg_id,
    sync_job_attempt_no,
    sync_job_attempt_status,
    sync_job_attempt_payload_snapshot
) VALUES (
    $1,
    $2,
    $3,
    $4,
    'running',
    $5
)
RETURNING sync_job_attempt_id
`

type InsertSyncJobAttemptRunningParams struct {
	SyncJobID                     uuid.UUID       `json:"sync_job_id"`
	SyncJobAttemptQueueName       string          `json:"sync_job_attempt_queue_name"`
	SyncJobAttemptMsgID           *int64          `json:"sync_job_attempt_msg_id"`
	SyncJobAttemptNo              int32           `json:"sync_job_attempt_no"`
	SyncJobAttemptPayloadSnapshot json.RawMessage `json:"sync_job_attempt_payload_snapshot"`
}

func (q *Queries) InsertSyncJobAttemptRunning(ctx context.Context, arg InsertSyncJobAttemptRunningParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertSyncJobAttemptRunning,
		arg.SyncJobID,
		arg.SyncJobAttemptQueueName,
		arg.SyncJobAttemptMsgID,
		arg.SyncJobAttemptNo,
		arg.SyncJobAttemptPayloadSnapshot,
	)
	var sync_job_attempt_id int64
	err := row.Scan(&sync_job_attempt_id)
	return sync_job_attempt_id, err
}

const listSyncJobAttempts = `-- name: ListSyncJobAttempts :many
SELECT sync_job_attempt_id,
       sync_job_id,
       sync_job_attempt_queue_name,
       sync_job_attempt_msg_id,
       sync_job_attempt_no,
       sync_job_attempt_status,
       sync_job_attempt_error_code,
       sync_job_attempt_error_detail,
       sync_job_attempt_payload_snapshot,
       sync_job_attempt_created_at,
       sync_job_attempt_finished_at
FROM public.sync_job_attempts
WHERE sync_job_id = $1
ORDER BY sync_job_attempt_created_at DESC, sync_job_attempt_id DESC
`

func (q *Queries) ListSyncJobAttempts(ctx context.Context, syncJobID uuid.UUID) ([]SyncJobAttempt, error) {
	rows, err := q.db.Query(ctx, listSyncJobAttempts, syncJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncJobAttempt{}
	for rows.Next() {
		var i SyncJobAttempt
		if err := rows.Scan(
			&i.SyncJobAttemptID,
			&i.SyncJobID,
			&i.SyncJobAttemptQueueName,
			&i.SyncJobAttemptMsgID,
			&i.SyncJobAttemptNo,
			&i.SyncJobAttemptStatus,
			&i.SyncJobAttemptErrorCode,
			&i.SyncJobAttemptErrorDetail,
			&i.SyncJobAttemptPayloadSnapshot,
			&i.SyncJobAttemptCreatedAt,
			&i.SyncJobAttemptFinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
