// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO auth.devices (
    user_id,
    device_name,
    device_os,
    device_app_version,
    device_push_token,
    device_push_token_type,
    device_push_token_updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING device_id, user_id, device_name, device_os, device_app_version, device_push_token, device_push_token_type, device_push_token_updated_at, device_created_at, device_updated_at, device_last_seen_at
`

type CreateDeviceParams struct {
	UserID                   pgtype.UUID           `db:"user_id" json:"user_id"`
	DeviceName               *string               `db:"device_name" json:"device_name"`
	DeviceOs                 *string               `db:"device_os" json:"device_os"`
	DeviceAppVersion         *string               `db:"device_app_version" json:"device_app_version"`
	DevicePushToken          *string               `db:"device_push_token" json:"device_push_token"`
	DevicePushTokenType      NullAuthPushTokenType `db:"device_push_token_type" json:"device_push_token_type"`
	DevicePushTokenUpdatedAt *time.Time            `db:"device_push_token_updated_at" json:"device_push_token_updated_at"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg *CreateDeviceParams) (AuthDevice, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.UserID,
		arg.DeviceName,
		arg.DeviceOs,
		arg.DeviceAppVersion,
		arg.DevicePushToken,
		arg.DevicePushTokenType,
		arg.DevicePushTokenUpdatedAt,
	)
	var i AuthDevice
	err := row.Scan(
		&i.DeviceID,
		&i.UserID,
		&i.DeviceName,
		&i.DeviceOs,
		&i.DeviceAppVersion,
		&i.DevicePushToken,
		&i.DevicePushTokenType,
		&i.DevicePushTokenUpdatedAt,
		&i.DeviceCreatedAt,
		&i.DeviceUpdatedAt,
		&i.DeviceLastSeenAt,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM auth.devices
WHERE device_id = $1
`

func (q *Queries) DeleteDevice(ctx context.Context, deviceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDevice, deviceID)
	return err
}

const deleteDevicesByUserID = `-- name: DeleteDevicesByUserID :exec
DELETE FROM auth.devices
WHERE user_id = $1
`

func (q *Queries) DeleteDevicesByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDevicesByUserID, userID)
	return err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT device_id, user_id, device_name, device_os, device_app_version, device_push_token, device_push_token_type, device_push_token_updated_at, device_created_at, device_updated_at, device_last_seen_at FROM auth.devices
WHERE device_id = $1
`

func (q *Queries) GetDeviceByID(ctx context.Context, deviceID pgtype.UUID) (AuthDevice, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, deviceID)
	var i AuthDevice
	err := row.Scan(
		&i.DeviceID,
		&i.UserID,
		&i.DeviceName,
		&i.DeviceOs,
		&i.DeviceAppVersion,
		&i.DevicePushToken,
		&i.DevicePushTokenType,
		&i.DevicePushTokenUpdatedAt,
		&i.DeviceCreatedAt,
		&i.DeviceUpdatedAt,
		&i.DeviceLastSeenAt,
	)
	return i, err
}

const getDevicesByUserID = `-- name: GetDevicesByUserID :many
SELECT device_id, user_id, device_name, device_os, device_app_version, device_push_token, device_push_token_type, device_push_token_updated_at, device_created_at, device_updated_at, device_last_seen_at FROM auth.devices
WHERE user_id = $1
ORDER BY device_last_seen_at DESC
`

func (q *Queries) GetDevicesByUserID(ctx context.Context, userID pgtype.UUID) ([]AuthDevice, error) {
	rows, err := q.db.Query(ctx, getDevicesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthDevice{}
	for rows.Next() {
		var i AuthDevice
		if err := rows.Scan(
			&i.DeviceID,
			&i.UserID,
			&i.DeviceName,
			&i.DeviceOs,
			&i.DeviceAppVersion,
			&i.DevicePushToken,
			&i.DevicePushTokenType,
			&i.DevicePushTokenUpdatedAt,
			&i.DeviceCreatedAt,
			&i.DeviceUpdatedAt,
			&i.DeviceLastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE auth.devices
SET
    device_name = COALESCE($2, device_name),
    device_os = COALESCE($3, device_os),
    device_app_version = COALESCE($4, device_app_version),
    device_updated_at = now()
WHERE device_id = $1
RETURNING device_id, user_id, device_name, device_os, device_app_version, device_push_token, device_push_token_type, device_push_token_updated_at, device_created_at, device_updated_at, device_last_seen_at
`

type UpdateDeviceParams struct {
	DeviceID         pgtype.UUID `db:"device_id" json:"device_id"`
	DeviceName       *string     `db:"device_name" json:"device_name"`
	DeviceOs         *string     `db:"device_os" json:"device_os"`
	DeviceAppVersion *string     `db:"device_app_version" json:"device_app_version"`
}

func (q *Queries) UpdateDevice(ctx context.Context, arg *UpdateDeviceParams) (AuthDevice, error) {
	row := q.db.QueryRow(ctx, updateDevice,
		arg.DeviceID,
		arg.DeviceName,
		arg.DeviceOs,
		arg.DeviceAppVersion,
	)
	var i AuthDevice
	err := row.Scan(
		&i.DeviceID,
		&i.UserID,
		&i.DeviceName,
		&i.DeviceOs,
		&i.DeviceAppVersion,
		&i.DevicePushToken,
		&i.DevicePushTokenType,
		&i.DevicePushTokenUpdatedAt,
		&i.DeviceCreatedAt,
		&i.DeviceUpdatedAt,
		&i.DeviceLastSeenAt,
	)
	return i, err
}

const updateDeviceLastSeen = `-- name: UpdateDeviceLastSeen :exec
UPDATE auth.devices
SET device_last_seen_at = now()
WHERE device_id = $1
`

func (q *Queries) UpdateDeviceLastSeen(ctx context.Context, deviceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateDeviceLastSeen, deviceID)
	return err
}

const updateDevicePushToken = `-- name: UpdateDevicePushToken :one
UPDATE auth.devices
SET
    device_push_token = $2,
    device_push_token_type = $3,
    device_push_token_updated_at = now(),
    device_updated_at = now()
WHERE device_id = $1
RETURNING device_id, user_id, device_name, device_os, device_app_version, device_push_token, device_push_token_type, device_push_token_updated_at, device_created_at, device_updated_at, device_last_seen_at
`

type UpdateDevicePushTokenParams struct {
	DeviceID            pgtype.UUID           `db:"device_id" json:"device_id"`
	DevicePushToken     *string               `db:"device_push_token" json:"device_push_token"`
	DevicePushTokenType NullAuthPushTokenType `db:"device_push_token_type" json:"device_push_token_type"`
}

func (q *Queries) UpdateDevicePushToken(ctx context.Context, arg *UpdateDevicePushTokenParams) (AuthDevice, error) {
	row := q.db.QueryRow(ctx, updateDevicePushToken, arg.DeviceID, arg.DevicePushToken, arg.DevicePushTokenType)
	var i AuthDevice
	err := row.Scan(
		&i.DeviceID,
		&i.UserID,
		&i.DeviceName,
		&i.DeviceOs,
		&i.DeviceAppVersion,
		&i.DevicePushToken,
		&i.DevicePushTokenType,
		&i.DevicePushTokenUpdatedAt,
		&i.DeviceCreatedAt,
		&i.DeviceUpdatedAt,
		&i.DeviceLastSeenAt,
	)
	return i, err
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO auth.devices (
    device_id,
    user_id,
    device_name,
    device_os,
    device_app_version
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (device_id) DO UPDATE SET
    device_last_seen_at = now(),
    device_updated_at = now()
RETURNING device_id, user_id, device_name, device_os, device_app_version, device_push_token, device_push_token_type, device_push_token_updated_at, device_created_at, device_updated_at, device_last_seen_at
`

type UpsertDeviceParams struct {
	DeviceID         pgtype.UUID `db:"device_id" json:"device_id"`
	UserID           pgtype.UUID `db:"user_id" json:"user_id"`
	DeviceName       *string     `db:"device_name" json:"device_name"`
	DeviceOs         *string     `db:"device_os" json:"device_os"`
	DeviceAppVersion *string     `db:"device_app_version" json:"device_app_version"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg *UpsertDeviceParams) (AuthDevice, error) {
	row := q.db.QueryRow(ctx, upsertDevice,
		arg.DeviceID,
		arg.UserID,
		arg.DeviceName,
		arg.DeviceOs,
		arg.DeviceAppVersion,
	)
	var i AuthDevice
	err := row.Scan(
		&i.DeviceID,
		&i.UserID,
		&i.DeviceName,
		&i.DeviceOs,
		&i.DeviceAppVersion,
		&i.DevicePushToken,
		&i.DevicePushTokenType,
		&i.DevicePushTokenUpdatedAt,
		&i.DeviceCreatedAt,
		&i.DeviceUpdatedAt,
		&i.DeviceLastSeenAt,
	)
	return i, err
}
