// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_change_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeActiveEmailChangeTokenByHash = `-- name: ConsumeActiveEmailChangeTokenByHash :one
with consumed as (
  update
    public.user_email_change_tokens
  set
    user_email_change_consumed_at = now()
  where
    user_email_change_token_hash = $1
    and user_email_change_consumed_at is null
    and user_email_change_expires_at > now()
  returning
    user_id,
    user_email_change_target_email
),
updated_user as (
  update
    public.users u
  set
    user_email = lower(btrim(c.user_email_change_target_email))
  from
    consumed c
  where
    u.user_id = c.user_id
  returning
    u.user_id,
    u.user_email
),
updated_identity as (
  update
    public.user_identities ui
  set
    user_identity_external_id = lower(btrim(c.user_email_change_target_email)),
    user_identity_email = lower(btrim(c.user_email_change_target_email)),
    user_identity_email_verified = true,
    user_identity_updated_at = now()
  from
    consumed c
  where
    ui.user_id = c.user_id
    and ui.user_identity_provider = 'email'
  returning
    ui.user_identity_id
),
inserted_identity as (
  insert into public.user_identities (
    user_id,
    user_identity_provider,
    user_identity_external_id,
    user_identity_email,
    user_identity_email_verified,
    user_identity_data
  )
  select
    c.user_id,
    'email',
    lower(btrim(c.user_email_change_target_email)),
    lower(btrim(c.user_email_change_target_email)),
    true,
    jsonb_build_object('email', lower(btrim(c.user_email_change_target_email)))
  from
    consumed c
  where
    not exists(select 1 from updated_identity)
)
select
  uu.user_id,
  uu.user_email
from
  updated_user uu
`

type ConsumeActiveEmailChangeTokenByHashRow struct {
	UserID    int64   `json:"user_id"`
	UserEmail *string `json:"user_email"`
}

func (q *Queries) ConsumeActiveEmailChangeTokenByHash(ctx context.Context, userEmailChangeTokenHash *string) (ConsumeActiveEmailChangeTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, consumeActiveEmailChangeTokenByHash, userEmailChangeTokenHash)
	var i ConsumeActiveEmailChangeTokenByHashRow
	err := row.Scan(&i.UserID, &i.UserEmail)
	return i, err
}

const createEmailChangeToken = `-- name: CreateEmailChangeToken :one
insert into public.user_email_change_tokens (user_id, user_email_change_target_email, user_email_change_token_hash, user_email_change_expires_at)
  values ($1, $2, $3, $4)
returning
  user_email_change_token_uuid,
  user_email_change_expires_at
`

type CreateEmailChangeTokenParams struct {
	UserID                     *int64             `json:"user_id"`
	UserEmailChangeTargetEmail *string            `json:"user_email_change_target_email"`
	UserEmailChangeTokenHash   *string            `json:"user_email_change_token_hash"`
	UserEmailChangeExpiresAt   pgtype.Timestamptz `json:"user_email_change_expires_at"`
}

type CreateEmailChangeTokenRow struct {
	UserEmailChangeTokenUuid uuid.UUID `json:"user_email_change_token_uuid"`
	UserEmailChangeExpiresAt time.Time `json:"user_email_change_expires_at"`
}

func (q *Queries) CreateEmailChangeToken(ctx context.Context, arg CreateEmailChangeTokenParams) (CreateEmailChangeTokenRow, error) {
	row := q.db.QueryRow(ctx, createEmailChangeToken,
		arg.UserID,
		arg.UserEmailChangeTargetEmail,
		arg.UserEmailChangeTokenHash,
		arg.UserEmailChangeExpiresAt,
	)
	var i CreateEmailChangeTokenRow
	err := row.Scan(&i.UserEmailChangeTokenUuid, &i.UserEmailChangeExpiresAt)
	return i, err
}

const getEmailChangeTokenStatusByHash = `-- name: GetEmailChangeTokenStatusByHash :one
select
  case
  when user_email_change_consumed_at is not null then
    'consumed'
  when user_email_change_expires_at <= now() then
    'expired'
  else
    'active'
  end as token_status
from
  public.user_email_change_tokens
where
  user_email_change_token_hash = $1
order by
  user_email_change_created_at desc
limit 1
`

func (q *Queries) GetEmailChangeTokenStatusByHash(ctx context.Context, userEmailChangeTokenHash *string) (*string, error) {
	row := q.db.QueryRow(ctx, getEmailChangeTokenStatusByHash, userEmailChangeTokenHash)
	var token_status *string
	err := row.Scan(&token_status)
	return token_status, err
}

const invalidateActiveEmailChangeTokensForUser = `-- name: InvalidateActiveEmailChangeTokensForUser :exec
update
  public.user_email_change_tokens
set
  user_email_change_consumed_at = now()
where
  user_id = $1
  and user_email_change_consumed_at is null
`

func (q *Queries) InvalidateActiveEmailChangeTokensForUser(ctx context.Context, userID *int64) error {
	_, err := q.db.Exec(ctx, invalidateActiveEmailChangeTokensForUser, userID)
	return err
}
