// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entities.sql

package db

import (
	"context"
	"encoding/json"
)

const countEntitiesByStatus = `-- name: CountEntitiesByStatus :one
SELECT COUNT(*) AS count
FROM task_queue.entity_registry
WHERE status = $1
`

func (q *Queries) CountEntitiesByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countEntitiesByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEntity = `-- name: DeleteEntity :exec
DELETE FROM task_queue.entity_registry
WHERE entity_id = $1
`

func (q *Queries) DeleteEntity(ctx context.Context, entityID string) error {
	_, err := q.db.Exec(ctx, deleteEntity, entityID)
	return err
}

const getEntity = `-- name: GetEntity :one
SELECT
    entity_id,
    entity_type,
    status,
    scheduling_strategy,
    metadata,
    created_at,
    updated_at
FROM task_queue.entity_registry
WHERE entity_id = $1
`

func (q *Queries) GetEntity(ctx context.Context, entityID string) (TaskQueueEntityRegistry, error) {
	row := q.db.QueryRow(ctx, getEntity, entityID)
	var i TaskQueueEntityRegistry
	err := row.Scan(
		&i.EntityID,
		&i.EntityType,
		&i.Status,
		&i.SchedulingStrategy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveEntities = `-- name: ListActiveEntities :many
SELECT
    entity_id,
    entity_type,
    status,
    scheduling_strategy,
    metadata,
    created_at,
    updated_at
FROM task_queue.entity_registry
WHERE status = 'active'
ORDER BY entity_id
`

func (q *Queries) ListActiveEntities(ctx context.Context) ([]TaskQueueEntityRegistry, error) {
	rows, err := q.db.Query(ctx, listActiveEntities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskQueueEntityRegistry{}
	for rows.Next() {
		var i TaskQueueEntityRegistry
		if err := rows.Scan(
			&i.EntityID,
			&i.EntityType,
			&i.Status,
			&i.SchedulingStrategy,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntities = `-- name: ListEntities :many
SELECT
    entity_id,
    entity_type,
    status,
    scheduling_strategy,
    metadata,
    created_at,
    updated_at
FROM task_queue.entity_registry
ORDER BY entity_id
`

func (q *Queries) ListEntities(ctx context.Context) ([]TaskQueueEntityRegistry, error) {
	rows, err := q.db.Query(ctx, listEntities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskQueueEntityRegistry{}
	for rows.Next() {
		var i TaskQueueEntityRegistry
		if err := rows.Scan(
			&i.EntityID,
			&i.EntityType,
			&i.Status,
			&i.SchedulingStrategy,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntityStatus = `-- name: UpdateEntityStatus :exec
UPDATE task_queue.entity_registry
SET
    status = $2,
    updated_at = NOW()
WHERE entity_id = $1
`

type UpdateEntityStatusParams struct {
	EntityID string `json:"entity_id"`
	Status   string `json:"status"`
}

func (q *Queries) UpdateEntityStatus(ctx context.Context, arg UpdateEntityStatusParams) error {
	_, err := q.db.Exec(ctx, updateEntityStatus, arg.EntityID, arg.Status)
	return err
}

const upsertEntity = `-- name: UpsertEntity :one
INSERT INTO task_queue.entity_registry (
    entity_id,
    entity_type,
    status,
    scheduling_strategy,
    metadata,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    COALESCE($3, 'active'),
    COALESCE($4, 'manual'),
    COALESCE($5, '{}'::jsonb),
    NOW(),
    NOW()
)
ON CONFLICT (entity_id) DO UPDATE
SET
    entity_type = EXCLUDED.entity_type,
    status = EXCLUDED.status,
    scheduling_strategy = EXCLUDED.scheduling_strategy,
    metadata = EXCLUDED.metadata,
    updated_at = NOW()
RETURNING entity_id, entity_type, status, scheduling_strategy, metadata, created_at, updated_at
`

type UpsertEntityParams struct {
	EntityID   string          `json:"entity_id"`
	EntityType string          `json:"entity_type"`
	Column3    *string         `json:"column_3"`
	Column4    *string         `json:"column_4"`
	Column5    json.RawMessage `json:"column_5"`
}

func (q *Queries) UpsertEntity(ctx context.Context, arg UpsertEntityParams) (TaskQueueEntityRegistry, error) {
	row := q.db.QueryRow(ctx, upsertEntity,
		arg.EntityID,
		arg.EntityType,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var i TaskQueueEntityRegistry
	err := row.Scan(
		&i.EntityID,
		&i.EntityType,
		&i.Status,
		&i.SchedulingStrategy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
