// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identities.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO auth.identities (
    user_id,
    identity_provider,
    identity_external_id,
    identity_email,
    identity_email_verified,
    identity_data
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING identity_id, user_id, identity_provider, identity_external_id, identity_email, identity_email_verified, identity_data, identity_created_at, identity_updated_at
`

type CreateIdentityParams struct {
	UserID                pgtype.UUID      `db:"user_id" json:"user_id"`
	IdentityProvider      AuthAuthProvider `db:"identity_provider" json:"identity_provider"`
	IdentityExternalID    string           `db:"identity_external_id" json:"identity_external_id"`
	IdentityEmail         *string          `db:"identity_email" json:"identity_email"`
	IdentityEmailVerified pgtype.Bool      `db:"identity_email_verified" json:"identity_email_verified"`
	IdentityData          json.RawMessage  `db:"identity_data" json:"identity_data"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg *CreateIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.UserID,
		arg.IdentityProvider,
		arg.IdentityExternalID,
		arg.IdentityEmail,
		arg.IdentityEmailVerified,
		arg.IdentityData,
	)
	var i AuthIdentity
	err := row.Scan(
		&i.IdentityID,
		&i.UserID,
		&i.IdentityProvider,
		&i.IdentityExternalID,
		&i.IdentityEmail,
		&i.IdentityEmailVerified,
		&i.IdentityData,
		&i.IdentityCreatedAt,
		&i.IdentityUpdatedAt,
	)
	return i, err
}

const getIdentitiesByUserID = `-- name: GetIdentitiesByUserID :many
SELECT identity_id, user_id, identity_provider, identity_external_id, identity_email, identity_email_verified, identity_data, identity_created_at, identity_updated_at FROM auth.identities
WHERE user_id = $1
ORDER BY identity_created_at ASC
`

func (q *Queries) GetIdentitiesByUserID(ctx context.Context, userID pgtype.UUID) ([]AuthIdentity, error) {
	rows, err := q.db.Query(ctx, getIdentitiesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthIdentity{}
	for rows.Next() {
		var i AuthIdentity
		if err := rows.Scan(
			&i.IdentityID,
			&i.UserID,
			&i.IdentityProvider,
			&i.IdentityExternalID,
			&i.IdentityEmail,
			&i.IdentityEmailVerified,
			&i.IdentityData,
			&i.IdentityCreatedAt,
			&i.IdentityUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIdentityByProviderAndExternalID = `-- name: GetIdentityByProviderAndExternalID :one
SELECT identity_id, user_id, identity_provider, identity_external_id, identity_email, identity_email_verified, identity_data, identity_created_at, identity_updated_at FROM auth.identities
WHERE identity_provider = $1 AND identity_external_id = $2
`

type GetIdentityByProviderAndExternalIDParams struct {
	IdentityProvider   AuthAuthProvider `db:"identity_provider" json:"identity_provider"`
	IdentityExternalID string           `db:"identity_external_id" json:"identity_external_id"`
}

func (q *Queries) GetIdentityByProviderAndExternalID(ctx context.Context, arg *GetIdentityByProviderAndExternalIDParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, getIdentityByProviderAndExternalID, arg.IdentityProvider, arg.IdentityExternalID)
	var i AuthIdentity
	err := row.Scan(
		&i.IdentityID,
		&i.UserID,
		&i.IdentityProvider,
		&i.IdentityExternalID,
		&i.IdentityEmail,
		&i.IdentityEmailVerified,
		&i.IdentityData,
		&i.IdentityCreatedAt,
		&i.IdentityUpdatedAt,
	)
	return i, err
}

const updateIdentity = `-- name: UpdateIdentity :one
UPDATE auth.identities
SET
    identity_email = COALESCE($2, identity_email),
    identity_email_verified = COALESCE($3, identity_email_verified),
    identity_data = COALESCE($4, identity_data),
    identity_updated_at = now()
WHERE identity_id = $1
RETURNING identity_id, user_id, identity_provider, identity_external_id, identity_email, identity_email_verified, identity_data, identity_created_at, identity_updated_at
`

type UpdateIdentityParams struct {
	IdentityID            pgtype.UUID     `db:"identity_id" json:"identity_id"`
	IdentityEmail         *string         `db:"identity_email" json:"identity_email"`
	IdentityEmailVerified pgtype.Bool     `db:"identity_email_verified" json:"identity_email_verified"`
	IdentityData          json.RawMessage `db:"identity_data" json:"identity_data"`
}

func (q *Queries) UpdateIdentity(ctx context.Context, arg *UpdateIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, updateIdentity,
		arg.IdentityID,
		arg.IdentityEmail,
		arg.IdentityEmailVerified,
		arg.IdentityData,
	)
	var i AuthIdentity
	err := row.Scan(
		&i.IdentityID,
		&i.UserID,
		&i.IdentityProvider,
		&i.IdentityExternalID,
		&i.IdentityEmail,
		&i.IdentityEmailVerified,
		&i.IdentityData,
		&i.IdentityCreatedAt,
		&i.IdentityUpdatedAt,
	)
	return i, err
}
