// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lookups.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listAvailableMunicipalities = `-- name: ListAvailableMunicipalities :many
SELECT DISTINCT
    pm.postal_municipality_id,
    pm.postal_municipality_code,
    pm.postal_municipality_name_fi,
    pm.postal_municipality_name_sv
FROM public.prices_transactions AS pt
JOIN public.prices_neighborhoods AS pn
    ON pn.prices_neighborhood_id = pt.prices_neighborhood_id
JOIN public.postal_postal_codes AS ppc
    ON ppc.postal_postal_code_id = pn.prices_neighborhood_postal_postal_code_id
JOIN public.postal_municipalities AS pm
    ON pm.postal_municipality_id = ppc.postal_municipality_id
WHERE pn.prices_neighborhood_postal_postal_code_id IS NOT NULL
ORDER BY pm.postal_municipality_name_fi
`

type ListAvailableMunicipalitiesRow struct {
	PostalMunicipalityID     uuid.UUID `json:"postal_municipality_id"`
	PostalMunicipalityCode   string    `json:"postal_municipality_code"`
	PostalMunicipalityNameFi string    `json:"postal_municipality_name_fi"`
	PostalMunicipalityNameSv *string   `json:"postal_municipality_name_sv"`
}

func (q *Queries) ListAvailableMunicipalities(ctx context.Context) ([]ListAvailableMunicipalitiesRow, error) {
	rows, err := q.db.Query(ctx, listAvailableMunicipalities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailableMunicipalitiesRow{}
	for rows.Next() {
		var i ListAvailableMunicipalitiesRow
		if err := rows.Scan(
			&i.PostalMunicipalityID,
			&i.PostalMunicipalityCode,
			&i.PostalMunicipalityNameFi,
			&i.PostalMunicipalityNameSv,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailablePostalCodes = `-- name: ListAvailablePostalCodes :many
SELECT DISTINCT
    ppc.postal_postal_code_id,
    ppc.postal_postal_code_code,
    ppc.postal_postal_code_name_fi,
    ppc.postal_postal_code_name_sv,
    pm.postal_municipality_id,
    pm.postal_municipality_name_fi
FROM public.prices_transactions AS pt
JOIN public.prices_neighborhoods AS pn
    ON pn.prices_neighborhood_id = pt.prices_neighborhood_id
JOIN public.postal_postal_codes AS ppc
    ON ppc.postal_postal_code_id = pn.prices_neighborhood_postal_postal_code_id
JOIN public.postal_municipalities AS pm
    ON pm.postal_municipality_id = ppc.postal_municipality_id
WHERE pn.prices_neighborhood_postal_postal_code_id IS NOT NULL
ORDER BY ppc.postal_postal_code_code
`

type ListAvailablePostalCodesRow struct {
	PostalPostalCodeID       uuid.UUID `json:"postal_postal_code_id"`
	PostalPostalCodeCode     string    `json:"postal_postal_code_code"`
	PostalPostalCodeNameFi   string    `json:"postal_postal_code_name_fi"`
	PostalPostalCodeNameSv   *string   `json:"postal_postal_code_name_sv"`
	PostalMunicipalityID     uuid.UUID `json:"postal_municipality_id"`
	PostalMunicipalityNameFi string    `json:"postal_municipality_name_fi"`
}

func (q *Queries) ListAvailablePostalCodes(ctx context.Context) ([]ListAvailablePostalCodesRow, error) {
	rows, err := q.db.Query(ctx, listAvailablePostalCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailablePostalCodesRow{}
	for rows.Next() {
		var i ListAvailablePostalCodesRow
		if err := rows.Scan(
			&i.PostalPostalCodeID,
			&i.PostalPostalCodeCode,
			&i.PostalPostalCodeNameFi,
			&i.PostalPostalCodeNameSv,
			&i.PostalMunicipalityID,
			&i.PostalMunicipalityNameFi,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCitiesWithNeighborhoods = `-- name: ListCitiesWithNeighborhoods :many
SELECT
    hc.prices_city_id,
    hc.prices_city_name,
    hc.prices_city_created_at,
    hc.prices_city_updated_at,
    hn.prices_neighborhood_id,
    hn.prices_neighborhood_name,
    hn.prices_neighborhood_created_at,
    hn.prices_neighborhood_updated_at,
    hp.prices_postal_code_id,
    hp.prices_postal_code_code
FROM public.prices_cities AS hc
LEFT JOIN public.prices_neighborhoods AS hn
    ON hn.prices_city_id = hc.prices_city_id
LEFT JOIN public.prices_postal_codes AS hp
    ON hn.prices_postal_code_id = hp.prices_postal_code_id
ORDER BY hc.prices_city_name, hn.prices_neighborhood_name
`

type ListCitiesWithNeighborhoodsRow struct {
	PricesCityID                uuid.UUID  `json:"prices_city_id"`
	PricesCityName              string     `json:"prices_city_name"`
	PricesCityCreatedAt         time.Time  `json:"prices_city_created_at"`
	PricesCityUpdatedAt         time.Time  `json:"prices_city_updated_at"`
	PricesNeighborhoodID        *uuid.UUID `json:"prices_neighborhood_id"`
	PricesNeighborhoodName      *string    `json:"prices_neighborhood_name"`
	PricesNeighborhoodCreatedAt *time.Time `json:"prices_neighborhood_created_at"`
	PricesNeighborhoodUpdatedAt *time.Time `json:"prices_neighborhood_updated_at"`
	PricesPostalCodeID          *uuid.UUID `json:"prices_postal_code_id"`
	PricesPostalCodeCode        *string    `json:"prices_postal_code_code"`
}

func (q *Queries) ListCitiesWithNeighborhoods(ctx context.Context) ([]ListCitiesWithNeighborhoodsRow, error) {
	rows, err := q.db.Query(ctx, listCitiesWithNeighborhoods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCitiesWithNeighborhoodsRow{}
	for rows.Next() {
		var i ListCitiesWithNeighborhoodsRow
		if err := rows.Scan(
			&i.PricesCityID,
			&i.PricesCityName,
			&i.PricesCityCreatedAt,
			&i.PricesCityUpdatedAt,
			&i.PricesNeighborhoodID,
			&i.PricesNeighborhoodName,
			&i.PricesNeighborhoodCreatedAt,
			&i.PricesNeighborhoodUpdatedAt,
			&i.PricesPostalCodeID,
			&i.PricesPostalCodeCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctCategories = `-- name: ListDistinctCategories :many
SELECT DISTINCT prices_transaction_category AS category
FROM public.prices_transactions
ORDER BY prices_transaction_category
`

func (q *Queries) ListDistinctCategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctPlots = `-- name: ListDistinctPlots :many
SELECT DISTINCT prices_transaction_plot AS plot
FROM public.prices_transactions
WHERE prices_transaction_plot IS NOT NULL AND prices_transaction_plot != ''
ORDER BY prices_transaction_plot
`

func (q *Queries) ListDistinctPlots(ctx context.Context) ([]*string, error) {
	rows, err := q.db.Query(ctx, listDistinctPlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var plot *string
		if err := rows.Scan(&plot); err != nil {
			return nil, err
		}
		items = append(items, plot)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctTypes = `-- name: ListDistinctTypes :many
SELECT DISTINCT prices_transaction_type AS type
FROM public.prices_transactions
ORDER BY prices_transaction_type
`

func (q *Queries) ListDistinctTypes(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var type_ string
		if err := rows.Scan(&type_); err != nil {
			return nil, err
		}
		items = append(items, type_)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricesCities = `-- name: ListPricesCities :many
SELECT
    prices_city_id,
    prices_city_name,
    prices_city_created_at,
    prices_city_updated_at
FROM public.prices_cities
ORDER BY prices_city_name
`

func (q *Queries) ListPricesCities(ctx context.Context) ([]PricesCity, error) {
	rows, err := q.db.Query(ctx, listPricesCities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PricesCity{}
	for rows.Next() {
		var i PricesCity
		if err := rows.Scan(
			&i.PricesCityID,
			&i.PricesCityName,
			&i.PricesCityCreatedAt,
			&i.PricesCityUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricesPostalCodesByCity = `-- name: ListPricesPostalCodesByCity :many
SELECT
    prices_postal_code_id,
    prices_postal_code_code,
    prices_city_id,
    prices_postal_code_created_at,
    prices_postal_code_updated_at
FROM public.prices_postal_codes
WHERE prices_city_id = $1
ORDER BY prices_postal_code_code
`

func (q *Queries) ListPricesPostalCodesByCity(ctx context.Context, cityID uuid.UUID) ([]PricesPostalCode, error) {
	rows, err := q.db.Query(ctx, listPricesPostalCodesByCity, cityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PricesPostalCode{}
	for rows.Next() {
		var i PricesPostalCode
		if err := rows.Scan(
			&i.PricesPostalCodeID,
			&i.PricesPostalCodeCode,
			&i.PricesCityID,
			&i.PricesPostalCodeCreatedAt,
			&i.PricesPostalCodeUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
