// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_authorization_handoffs.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveOAuthAuthorizationHandoffByID = `-- name: ApproveOAuthAuthorizationHandoffByID :one
update oauth_authorization_handoffs
set
  user_uuid = $1,
  oauth_authorization_handoff_authorization_code = $2,
  oauth_authorization_handoff_redirect_url = $3,
  oauth_authorization_handoff_updated_at = now()
where
  oauth_authorization_handoff_id = $4
  and oauth_authorization_handoff_denied_at is null
  and oauth_authorization_handoff_completed_at is null
  and oauth_authorization_handoff_expires_at > now()
returning
  oauth_authorization_handoff_id,
  oauth_authorization_handoff_token_hash,
  oauth_authorization_handoff_user_code,
  oauth_client_id,
  oauth_authorization_handoff_redirect_uri,
  oauth_authorization_handoff_scopes,
  oauth_authorization_handoff_audience,
  oauth_authorization_handoff_state,
  oauth_authorization_handoff_code_challenge,
  oauth_authorization_handoff_code_challenge_method,
  user_uuid,
  oauth_authorization_handoff_authorization_code,
  oauth_authorization_handoff_redirect_url,
  oauth_authorization_handoff_denied_at,
  oauth_authorization_handoff_completed_at,
  oauth_authorization_handoff_expires_at,
  oauth_authorization_handoff_created_at,
  oauth_authorization_handoff_updated_at
`

type ApproveOAuthAuthorizationHandoffByIDParams struct {
	UserUuid                                   pgtype.UUID `json:"user_uuid"`
	OauthAuthorizationHandoffAuthorizationCode *string     `json:"oauth_authorization_handoff_authorization_code"`
	OauthAuthorizationHandoffRedirectUrl       *string     `json:"oauth_authorization_handoff_redirect_url"`
	OauthAuthorizationHandoffID                pgtype.UUID `json:"oauth_authorization_handoff_id"`
}

type ApproveOAuthAuthorizationHandoffByIDRow struct {
	OauthAuthorizationHandoffID                  uuid.UUID          `json:"oauth_authorization_handoff_id"`
	OauthAuthorizationHandoffTokenHash           string             `json:"oauth_authorization_handoff_token_hash"`
	OauthAuthorizationHandoffUserCode            string             `json:"oauth_authorization_handoff_user_code"`
	OauthClientID                                string             `json:"oauth_client_id"`
	OauthAuthorizationHandoffRedirectUri         string             `json:"oauth_authorization_handoff_redirect_uri"`
	OauthAuthorizationHandoffScopes              []string           `json:"oauth_authorization_handoff_scopes"`
	OauthAuthorizationHandoffAudience            string             `json:"oauth_authorization_handoff_audience"`
	OauthAuthorizationHandoffState               string             `json:"oauth_authorization_handoff_state"`
	OauthAuthorizationHandoffCodeChallenge       string             `json:"oauth_authorization_handoff_code_challenge"`
	OauthAuthorizationHandoffCodeChallengeMethod string             `json:"oauth_authorization_handoff_code_challenge_method"`
	UserUuid                                     pgtype.UUID        `json:"user_uuid"`
	OauthAuthorizationHandoffAuthorizationCode   *string            `json:"oauth_authorization_handoff_authorization_code"`
	OauthAuthorizationHandoffRedirectUrl         *string            `json:"oauth_authorization_handoff_redirect_url"`
	OauthAuthorizationHandoffDeniedAt            pgtype.Timestamptz `json:"oauth_authorization_handoff_denied_at"`
	OauthAuthorizationHandoffCompletedAt         pgtype.Timestamptz `json:"oauth_authorization_handoff_completed_at"`
	OauthAuthorizationHandoffExpiresAt           time.Time          `json:"oauth_authorization_handoff_expires_at"`
	OauthAuthorizationHandoffCreatedAt           time.Time          `json:"oauth_authorization_handoff_created_at"`
	OauthAuthorizationHandoffUpdatedAt           time.Time          `json:"oauth_authorization_handoff_updated_at"`
}

func (q *Queries) ApproveOAuthAuthorizationHandoffByID(ctx context.Context, arg ApproveOAuthAuthorizationHandoffByIDParams) (ApproveOAuthAuthorizationHandoffByIDRow, error) {
	row := q.db.QueryRow(ctx, approveOAuthAuthorizationHandoffByID,
		arg.UserUuid,
		arg.OauthAuthorizationHandoffAuthorizationCode,
		arg.OauthAuthorizationHandoffRedirectUrl,
		arg.OauthAuthorizationHandoffID,
	)
	var i ApproveOAuthAuthorizationHandoffByIDRow
	err := row.Scan(
		&i.OauthAuthorizationHandoffID,
		&i.OauthAuthorizationHandoffTokenHash,
		&i.OauthAuthorizationHandoffUserCode,
		&i.OauthClientID,
		&i.OauthAuthorizationHandoffRedirectUri,
		&i.OauthAuthorizationHandoffScopes,
		&i.OauthAuthorizationHandoffAudience,
		&i.OauthAuthorizationHandoffState,
		&i.OauthAuthorizationHandoffCodeChallenge,
		&i.OauthAuthorizationHandoffCodeChallengeMethod,
		&i.UserUuid,
		&i.OauthAuthorizationHandoffAuthorizationCode,
		&i.OauthAuthorizationHandoffRedirectUrl,
		&i.OauthAuthorizationHandoffDeniedAt,
		&i.OauthAuthorizationHandoffCompletedAt,
		&i.OauthAuthorizationHandoffExpiresAt,
		&i.OauthAuthorizationHandoffCreatedAt,
		&i.OauthAuthorizationHandoffUpdatedAt,
	)
	return i, err
}

const createOAuthAuthorizationHandoff = `-- name: CreateOAuthAuthorizationHandoff :one
insert into oauth_authorization_handoffs (
  oauth_authorization_handoff_token_hash,
  oauth_authorization_handoff_user_code,
  oauth_client_id,
  oauth_authorization_handoff_redirect_uri,
  oauth_authorization_handoff_scopes,
  oauth_authorization_handoff_audience,
  oauth_authorization_handoff_state,
  oauth_authorization_handoff_code_challenge,
  oauth_authorization_handoff_code_challenge_method,
  oauth_authorization_handoff_expires_at
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10
)
returning
  oauth_authorization_handoff_id,
  oauth_authorization_handoff_token_hash,
  oauth_authorization_handoff_user_code,
  oauth_client_id,
  oauth_authorization_handoff_redirect_uri,
  oauth_authorization_handoff_scopes,
  oauth_authorization_handoff_audience,
  oauth_authorization_handoff_state,
  oauth_authorization_handoff_code_challenge,
  oauth_authorization_handoff_code_challenge_method,
  user_uuid,
  oauth_authorization_handoff_authorization_code,
  oauth_authorization_handoff_redirect_url,
  oauth_authorization_handoff_denied_at,
  oauth_authorization_handoff_completed_at,
  oauth_authorization_handoff_expires_at,
  oauth_authorization_handoff_created_at,
  oauth_authorization_handoff_updated_at
`

type CreateOAuthAuthorizationHandoffParams struct {
	OauthAuthorizationHandoffTokenHash           *string            `json:"oauth_authorization_handoff_token_hash"`
	OauthAuthorizationHandoffUserCode            *string            `json:"oauth_authorization_handoff_user_code"`
	OauthClientID                                *string            `json:"oauth_client_id"`
	OauthAuthorizationHandoffRedirectUri         *string            `json:"oauth_authorization_handoff_redirect_uri"`
	OauthAuthorizationHandoffScopes              []string           `json:"oauth_authorization_handoff_scopes"`
	OauthAuthorizationHandoffAudience            *string            `json:"oauth_authorization_handoff_audience"`
	OauthAuthorizationHandoffState               *string            `json:"oauth_authorization_handoff_state"`
	OauthAuthorizationHandoffCodeChallenge       *string            `json:"oauth_authorization_handoff_code_challenge"`
	OauthAuthorizationHandoffCodeChallengeMethod *string            `json:"oauth_authorization_handoff_code_challenge_method"`
	OauthAuthorizationHandoffExpiresAt           pgtype.Timestamptz `json:"oauth_authorization_handoff_expires_at"`
}

type CreateOAuthAuthorizationHandoffRow struct {
	OauthAuthorizationHandoffID                  uuid.UUID          `json:"oauth_authorization_handoff_id"`
	OauthAuthorizationHandoffTokenHash           string             `json:"oauth_authorization_handoff_token_hash"`
	OauthAuthorizationHandoffUserCode            string             `json:"oauth_authorization_handoff_user_code"`
	OauthClientID                                string             `json:"oauth_client_id"`
	OauthAuthorizationHandoffRedirectUri         string             `json:"oauth_authorization_handoff_redirect_uri"`
	OauthAuthorizationHandoffScopes              []string           `json:"oauth_authorization_handoff_scopes"`
	OauthAuthorizationHandoffAudience            string             `json:"oauth_authorization_handoff_audience"`
	OauthAuthorizationHandoffState               string             `json:"oauth_authorization_handoff_state"`
	OauthAuthorizationHandoffCodeChallenge       string             `json:"oauth_authorization_handoff_code_challenge"`
	OauthAuthorizationHandoffCodeChallengeMethod string             `json:"oauth_authorization_handoff_code_challenge_method"`
	UserUuid                                     pgtype.UUID        `json:"user_uuid"`
	OauthAuthorizationHandoffAuthorizationCode   *string            `json:"oauth_authorization_handoff_authorization_code"`
	OauthAuthorizationHandoffRedirectUrl         *string            `json:"oauth_authorization_handoff_redirect_url"`
	OauthAuthorizationHandoffDeniedAt            pgtype.Timestamptz `json:"oauth_authorization_handoff_denied_at"`
	OauthAuthorizationHandoffCompletedAt         pgtype.Timestamptz `json:"oauth_authorization_handoff_completed_at"`
	OauthAuthorizationHandoffExpiresAt           time.Time          `json:"oauth_authorization_handoff_expires_at"`
	OauthAuthorizationHandoffCreatedAt           time.Time          `json:"oauth_authorization_handoff_created_at"`
	OauthAuthorizationHandoffUpdatedAt           time.Time          `json:"oauth_authorization_handoff_updated_at"`
}

func (q *Queries) CreateOAuthAuthorizationHandoff(ctx context.Context, arg CreateOAuthAuthorizationHandoffParams) (CreateOAuthAuthorizationHandoffRow, error) {
	row := q.db.QueryRow(ctx, createOAuthAuthorizationHandoff,
		arg.OauthAuthorizationHandoffTokenHash,
		arg.OauthAuthorizationHandoffUserCode,
		arg.OauthClientID,
		arg.OauthAuthorizationHandoffRedirectUri,
		arg.OauthAuthorizationHandoffScopes,
		arg.OauthAuthorizationHandoffAudience,
		arg.OauthAuthorizationHandoffState,
		arg.OauthAuthorizationHandoffCodeChallenge,
		arg.OauthAuthorizationHandoffCodeChallengeMethod,
		arg.OauthAuthorizationHandoffExpiresAt,
	)
	var i CreateOAuthAuthorizationHandoffRow
	err := row.Scan(
		&i.OauthAuthorizationHandoffID,
		&i.OauthAuthorizationHandoffTokenHash,
		&i.OauthAuthorizationHandoffUserCode,
		&i.OauthClientID,
		&i.OauthAuthorizationHandoffRedirectUri,
		&i.OauthAuthorizationHandoffScopes,
		&i.OauthAuthorizationHandoffAudience,
		&i.OauthAuthorizationHandoffState,
		&i.OauthAuthorizationHandoffCodeChallenge,
		&i.OauthAuthorizationHandoffCodeChallengeMethod,
		&i.UserUuid,
		&i.OauthAuthorizationHandoffAuthorizationCode,
		&i.OauthAuthorizationHandoffRedirectUrl,
		&i.OauthAuthorizationHandoffDeniedAt,
		&i.OauthAuthorizationHandoffCompletedAt,
		&i.OauthAuthorizationHandoffExpiresAt,
		&i.OauthAuthorizationHandoffCreatedAt,
		&i.OauthAuthorizationHandoffUpdatedAt,
	)
	return i, err
}

const denyOAuthAuthorizationHandoffByID = `-- name: DenyOAuthAuthorizationHandoffByID :one
update oauth_authorization_handoffs
set
  oauth_authorization_handoff_denied_at = now(),
  oauth_authorization_handoff_updated_at = now()
where
  oauth_authorization_handoff_id = $1
  and oauth_authorization_handoff_denied_at is null
  and oauth_authorization_handoff_completed_at is null
  and oauth_authorization_handoff_expires_at > now()
returning
  oauth_authorization_handoff_id,
  oauth_authorization_handoff_token_hash,
  oauth_authorization_handoff_user_code,
  oauth_client_id,
  oauth_authorization_handoff_redirect_uri,
  oauth_authorization_handoff_scopes,
  oauth_authorization_handoff_audience,
  oauth_authorization_handoff_state,
  oauth_authorization_handoff_code_challenge,
  oauth_authorization_handoff_code_challenge_method,
  user_uuid,
  oauth_authorization_handoff_authorization_code,
  oauth_authorization_handoff_redirect_url,
  oauth_authorization_handoff_denied_at,
  oauth_authorization_handoff_completed_at,
  oauth_authorization_handoff_expires_at,
  oauth_authorization_handoff_created_at,
  oauth_authorization_handoff_updated_at
`

type DenyOAuthAuthorizationHandoffByIDRow struct {
	OauthAuthorizationHandoffID                  uuid.UUID          `json:"oauth_authorization_handoff_id"`
	OauthAuthorizationHandoffTokenHash           string             `json:"oauth_authorization_handoff_token_hash"`
	OauthAuthorizationHandoffUserCode            string             `json:"oauth_authorization_handoff_user_code"`
	OauthClientID                                string             `json:"oauth_client_id"`
	OauthAuthorizationHandoffRedirectUri         string             `json:"oauth_authorization_handoff_redirect_uri"`
	OauthAuthorizationHandoffScopes              []string           `json:"oauth_authorization_handoff_scopes"`
	OauthAuthorizationHandoffAudience            string             `json:"oauth_authorization_handoff_audience"`
	OauthAuthorizationHandoffState               string             `json:"oauth_authorization_handoff_state"`
	OauthAuthorizationHandoffCodeChallenge       string             `json:"oauth_authorization_handoff_code_challenge"`
	OauthAuthorizationHandoffCodeChallengeMethod string             `json:"oauth_authorization_handoff_code_challenge_method"`
	UserUuid                                     pgtype.UUID        `json:"user_uuid"`
	OauthAuthorizationHandoffAuthorizationCode   *string            `json:"oauth_authorization_handoff_authorization_code"`
	OauthAuthorizationHandoffRedirectUrl         *string            `json:"oauth_authorization_handoff_redirect_url"`
	OauthAuthorizationHandoffDeniedAt            pgtype.Timestamptz `json:"oauth_authorization_handoff_denied_at"`
	OauthAuthorizationHandoffCompletedAt         pgtype.Timestamptz `json:"oauth_authorization_handoff_completed_at"`
	OauthAuthorizationHandoffExpiresAt           time.Time          `json:"oauth_authorization_handoff_expires_at"`
	OauthAuthorizationHandoffCreatedAt           time.Time          `json:"oauth_authorization_handoff_created_at"`
	OauthAuthorizationHandoffUpdatedAt           time.Time          `json:"oauth_authorization_handoff_updated_at"`
}

func (q *Queries) DenyOAuthAuthorizationHandoffByID(ctx context.Context, oauthAuthorizationHandoffID pgtype.UUID) (DenyOAuthAuthorizationHandoffByIDRow, error) {
	row := q.db.QueryRow(ctx, denyOAuthAuthorizationHandoffByID, oauthAuthorizationHandoffID)
	var i DenyOAuthAuthorizationHandoffByIDRow
	err := row.Scan(
		&i.OauthAuthorizationHandoffID,
		&i.OauthAuthorizationHandoffTokenHash,
		&i.OauthAuthorizationHandoffUserCode,
		&i.OauthClientID,
		&i.OauthAuthorizationHandoffRedirectUri,
		&i.OauthAuthorizationHandoffScopes,
		&i.OauthAuthorizationHandoffAudience,
		&i.OauthAuthorizationHandoffState,
		&i.OauthAuthorizationHandoffCodeChallenge,
		&i.OauthAuthorizationHandoffCodeChallengeMethod,
		&i.UserUuid,
		&i.OauthAuthorizationHandoffAuthorizationCode,
		&i.OauthAuthorizationHandoffRedirectUrl,
		&i.OauthAuthorizationHandoffDeniedAt,
		&i.OauthAuthorizationHandoffCompletedAt,
		&i.OauthAuthorizationHandoffExpiresAt,
		&i.OauthAuthorizationHandoffCreatedAt,
		&i.OauthAuthorizationHandoffUpdatedAt,
	)
	return i, err
}

const getOAuthAuthorizationHandoffByID = `-- name: GetOAuthAuthorizationHandoffByID :one
select
  oauth_authorization_handoff_id,
  oauth_authorization_handoff_token_hash,
  oauth_authorization_handoff_user_code,
  oauth_client_id,
  oauth_authorization_handoff_redirect_uri,
  oauth_authorization_handoff_scopes,
  oauth_authorization_handoff_audience,
  oauth_authorization_handoff_state,
  oauth_authorization_handoff_code_challenge,
  oauth_authorization_handoff_code_challenge_method,
  user_uuid,
  oauth_authorization_handoff_authorization_code,
  oauth_authorization_handoff_redirect_url,
  oauth_authorization_handoff_denied_at,
  oauth_authorization_handoff_completed_at,
  oauth_authorization_handoff_expires_at,
  oauth_authorization_handoff_created_at,
  oauth_authorization_handoff_updated_at
from oauth_authorization_handoffs
where oauth_authorization_handoff_id = $1
`

type GetOAuthAuthorizationHandoffByIDRow struct {
	OauthAuthorizationHandoffID                  uuid.UUID          `json:"oauth_authorization_handoff_id"`
	OauthAuthorizationHandoffTokenHash           string             `json:"oauth_authorization_handoff_token_hash"`
	OauthAuthorizationHandoffUserCode            string             `json:"oauth_authorization_handoff_user_code"`
	OauthClientID                                string             `json:"oauth_client_id"`
	OauthAuthorizationHandoffRedirectUri         string             `json:"oauth_authorization_handoff_redirect_uri"`
	OauthAuthorizationHandoffScopes              []string           `json:"oauth_authorization_handoff_scopes"`
	OauthAuthorizationHandoffAudience            string             `json:"oauth_authorization_handoff_audience"`
	OauthAuthorizationHandoffState               string             `json:"oauth_authorization_handoff_state"`
	OauthAuthorizationHandoffCodeChallenge       string             `json:"oauth_authorization_handoff_code_challenge"`
	OauthAuthorizationHandoffCodeChallengeMethod string             `json:"oauth_authorization_handoff_code_challenge_method"`
	UserUuid                                     pgtype.UUID        `json:"user_uuid"`
	OauthAuthorizationHandoffAuthorizationCode   *string            `json:"oauth_authorization_handoff_authorization_code"`
	OauthAuthorizationHandoffRedirectUrl         *string            `json:"oauth_authorization_handoff_redirect_url"`
	OauthAuthorizationHandoffDeniedAt            pgtype.Timestamptz `json:"oauth_authorization_handoff_denied_at"`
	OauthAuthorizationHandoffCompletedAt         pgtype.Timestamptz `json:"oauth_authorization_handoff_completed_at"`
	OauthAuthorizationHandoffExpiresAt           time.Time          `json:"oauth_authorization_handoff_expires_at"`
	OauthAuthorizationHandoffCreatedAt           time.Time          `json:"oauth_authorization_handoff_created_at"`
	OauthAuthorizationHandoffUpdatedAt           time.Time          `json:"oauth_authorization_handoff_updated_at"`
}

func (q *Queries) GetOAuthAuthorizationHandoffByID(ctx context.Context, oauthAuthorizationHandoffID pgtype.UUID) (GetOAuthAuthorizationHandoffByIDRow, error) {
	row := q.db.QueryRow(ctx, getOAuthAuthorizationHandoffByID, oauthAuthorizationHandoffID)
	var i GetOAuthAuthorizationHandoffByIDRow
	err := row.Scan(
		&i.OauthAuthorizationHandoffID,
		&i.OauthAuthorizationHandoffTokenHash,
		&i.OauthAuthorizationHandoffUserCode,
		&i.OauthClientID,
		&i.OauthAuthorizationHandoffRedirectUri,
		&i.OauthAuthorizationHandoffScopes,
		&i.OauthAuthorizationHandoffAudience,
		&i.OauthAuthorizationHandoffState,
		&i.OauthAuthorizationHandoffCodeChallenge,
		&i.OauthAuthorizationHandoffCodeChallengeMethod,
		&i.UserUuid,
		&i.OauthAuthorizationHandoffAuthorizationCode,
		&i.OauthAuthorizationHandoffRedirectUrl,
		&i.OauthAuthorizationHandoffDeniedAt,
		&i.OauthAuthorizationHandoffCompletedAt,
		&i.OauthAuthorizationHandoffExpiresAt,
		&i.OauthAuthorizationHandoffCreatedAt,
		&i.OauthAuthorizationHandoffUpdatedAt,
	)
	return i, err
}

const getOAuthAuthorizationHandoffByTokenHash = `-- name: GetOAuthAuthorizationHandoffByTokenHash :one
select
  oauth_authorization_handoff_id,
  oauth_authorization_handoff_token_hash,
  oauth_authorization_handoff_user_code,
  oauth_client_id,
  oauth_authorization_handoff_redirect_uri,
  oauth_authorization_handoff_scopes,
  oauth_authorization_handoff_audience,
  oauth_authorization_handoff_state,
  oauth_authorization_handoff_code_challenge,
  oauth_authorization_handoff_code_challenge_method,
  user_uuid,
  oauth_authorization_handoff_authorization_code,
  oauth_authorization_handoff_redirect_url,
  oauth_authorization_handoff_denied_at,
  oauth_authorization_handoff_completed_at,
  oauth_authorization_handoff_expires_at,
  oauth_authorization_handoff_created_at,
  oauth_authorization_handoff_updated_at
from oauth_authorization_handoffs
where oauth_authorization_handoff_token_hash = $1
`

type GetOAuthAuthorizationHandoffByTokenHashRow struct {
	OauthAuthorizationHandoffID                  uuid.UUID          `json:"oauth_authorization_handoff_id"`
	OauthAuthorizationHandoffTokenHash           string             `json:"oauth_authorization_handoff_token_hash"`
	OauthAuthorizationHandoffUserCode            string             `json:"oauth_authorization_handoff_user_code"`
	OauthClientID                                string             `json:"oauth_client_id"`
	OauthAuthorizationHandoffRedirectUri         string             `json:"oauth_authorization_handoff_redirect_uri"`
	OauthAuthorizationHandoffScopes              []string           `json:"oauth_authorization_handoff_scopes"`
	OauthAuthorizationHandoffAudience            string             `json:"oauth_authorization_handoff_audience"`
	OauthAuthorizationHandoffState               string             `json:"oauth_authorization_handoff_state"`
	OauthAuthorizationHandoffCodeChallenge       string             `json:"oauth_authorization_handoff_code_challenge"`
	OauthAuthorizationHandoffCodeChallengeMethod string             `json:"oauth_authorization_handoff_code_challenge_method"`
	UserUuid                                     pgtype.UUID        `json:"user_uuid"`
	OauthAuthorizationHandoffAuthorizationCode   *string            `json:"oauth_authorization_handoff_authorization_code"`
	OauthAuthorizationHandoffRedirectUrl         *string            `json:"oauth_authorization_handoff_redirect_url"`
	OauthAuthorizationHandoffDeniedAt            pgtype.Timestamptz `json:"oauth_authorization_handoff_denied_at"`
	OauthAuthorizationHandoffCompletedAt         pgtype.Timestamptz `json:"oauth_authorization_handoff_completed_at"`
	OauthAuthorizationHandoffExpiresAt           time.Time          `json:"oauth_authorization_handoff_expires_at"`
	OauthAuthorizationHandoffCreatedAt           time.Time          `json:"oauth_authorization_handoff_created_at"`
	OauthAuthorizationHandoffUpdatedAt           time.Time          `json:"oauth_authorization_handoff_updated_at"`
}

func (q *Queries) GetOAuthAuthorizationHandoffByTokenHash(ctx context.Context, oauthAuthorizationHandoffTokenHash *string) (GetOAuthAuthorizationHandoffByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getOAuthAuthorizationHandoffByTokenHash, oauthAuthorizationHandoffTokenHash)
	var i GetOAuthAuthorizationHandoffByTokenHashRow
	err := row.Scan(
		&i.OauthAuthorizationHandoffID,
		&i.OauthAuthorizationHandoffTokenHash,
		&i.OauthAuthorizationHandoffUserCode,
		&i.OauthClientID,
		&i.OauthAuthorizationHandoffRedirectUri,
		&i.OauthAuthorizationHandoffScopes,
		&i.OauthAuthorizationHandoffAudience,
		&i.OauthAuthorizationHandoffState,
		&i.OauthAuthorizationHandoffCodeChallenge,
		&i.OauthAuthorizationHandoffCodeChallengeMethod,
		&i.UserUuid,
		&i.OauthAuthorizationHandoffAuthorizationCode,
		&i.OauthAuthorizationHandoffRedirectUrl,
		&i.OauthAuthorizationHandoffDeniedAt,
		&i.OauthAuthorizationHandoffCompletedAt,
		&i.OauthAuthorizationHandoffExpiresAt,
		&i.OauthAuthorizationHandoffCreatedAt,
		&i.OauthAuthorizationHandoffUpdatedAt,
	)
	return i, err
}

const getOAuthAuthorizationHandoffByUserCode = `-- name: GetOAuthAuthorizationHandoffByUserCode :one
select
  oauth_authorization_handoff_id,
  oauth_authorization_handoff_token_hash,
  oauth_authorization_handoff_user_code,
  oauth_client_id,
  oauth_authorization_handoff_redirect_uri,
  oauth_authorization_handoff_scopes,
  oauth_authorization_handoff_audience,
  oauth_authorization_handoff_state,
  oauth_authorization_handoff_code_challenge,
  oauth_authorization_handoff_code_challenge_method,
  user_uuid,
  oauth_authorization_handoff_authorization_code,
  oauth_authorization_handoff_redirect_url,
  oauth_authorization_handoff_denied_at,
  oauth_authorization_handoff_completed_at,
  oauth_authorization_handoff_expires_at,
  oauth_authorization_handoff_created_at,
  oauth_authorization_handoff_updated_at
from oauth_authorization_handoffs
where oauth_authorization_handoff_user_code = $1
`

type GetOAuthAuthorizationHandoffByUserCodeRow struct {
	OauthAuthorizationHandoffID                  uuid.UUID          `json:"oauth_authorization_handoff_id"`
	OauthAuthorizationHandoffTokenHash           string             `json:"oauth_authorization_handoff_token_hash"`
	OauthAuthorizationHandoffUserCode            string             `json:"oauth_authorization_handoff_user_code"`
	OauthClientID                                string             `json:"oauth_client_id"`
	OauthAuthorizationHandoffRedirectUri         string             `json:"oauth_authorization_handoff_redirect_uri"`
	OauthAuthorizationHandoffScopes              []string           `json:"oauth_authorization_handoff_scopes"`
	OauthAuthorizationHandoffAudience            string             `json:"oauth_authorization_handoff_audience"`
	OauthAuthorizationHandoffState               string             `json:"oauth_authorization_handoff_state"`
	OauthAuthorizationHandoffCodeChallenge       string             `json:"oauth_authorization_handoff_code_challenge"`
	OauthAuthorizationHandoffCodeChallengeMethod string             `json:"oauth_authorization_handoff_code_challenge_method"`
	UserUuid                                     pgtype.UUID        `json:"user_uuid"`
	OauthAuthorizationHandoffAuthorizationCode   *string            `json:"oauth_authorization_handoff_authorization_code"`
	OauthAuthorizationHandoffRedirectUrl         *string            `json:"oauth_authorization_handoff_redirect_url"`
	OauthAuthorizationHandoffDeniedAt            pgtype.Timestamptz `json:"oauth_authorization_handoff_denied_at"`
	OauthAuthorizationHandoffCompletedAt         pgtype.Timestamptz `json:"oauth_authorization_handoff_completed_at"`
	OauthAuthorizationHandoffExpiresAt           time.Time          `json:"oauth_authorization_handoff_expires_at"`
	OauthAuthorizationHandoffCreatedAt           time.Time          `json:"oauth_authorization_handoff_created_at"`
	OauthAuthorizationHandoffUpdatedAt           time.Time          `json:"oauth_authorization_handoff_updated_at"`
}

func (q *Queries) GetOAuthAuthorizationHandoffByUserCode(ctx context.Context, oauthAuthorizationHandoffUserCode *string) (GetOAuthAuthorizationHandoffByUserCodeRow, error) {
	row := q.db.QueryRow(ctx, getOAuthAuthorizationHandoffByUserCode, oauthAuthorizationHandoffUserCode)
	var i GetOAuthAuthorizationHandoffByUserCodeRow
	err := row.Scan(
		&i.OauthAuthorizationHandoffID,
		&i.OauthAuthorizationHandoffTokenHash,
		&i.OauthAuthorizationHandoffUserCode,
		&i.OauthClientID,
		&i.OauthAuthorizationHandoffRedirectUri,
		&i.OauthAuthorizationHandoffScopes,
		&i.OauthAuthorizationHandoffAudience,
		&i.OauthAuthorizationHandoffState,
		&i.OauthAuthorizationHandoffCodeChallenge,
		&i.OauthAuthorizationHandoffCodeChallengeMethod,
		&i.UserUuid,
		&i.OauthAuthorizationHandoffAuthorizationCode,
		&i.OauthAuthorizationHandoffRedirectUrl,
		&i.OauthAuthorizationHandoffDeniedAt,
		&i.OauthAuthorizationHandoffCompletedAt,
		&i.OauthAuthorizationHandoffExpiresAt,
		&i.OauthAuthorizationHandoffCreatedAt,
		&i.OauthAuthorizationHandoffUpdatedAt,
	)
	return i, err
}

const markOAuthAuthorizationHandoffCompletedByID = `-- name: MarkOAuthAuthorizationHandoffCompletedByID :one
update oauth_authorization_handoffs
set
  oauth_authorization_handoff_completed_at = now(),
  oauth_authorization_handoff_updated_at = now()
where
  oauth_authorization_handoff_id = $1
  and oauth_authorization_handoff_completed_at is null
returning
  oauth_authorization_handoff_id,
  oauth_authorization_handoff_token_hash,
  oauth_authorization_handoff_user_code,
  oauth_client_id,
  oauth_authorization_handoff_redirect_uri,
  oauth_authorization_handoff_scopes,
  oauth_authorization_handoff_audience,
  oauth_authorization_handoff_state,
  oauth_authorization_handoff_code_challenge,
  oauth_authorization_handoff_code_challenge_method,
  user_uuid,
  oauth_authorization_handoff_authorization_code,
  oauth_authorization_handoff_redirect_url,
  oauth_authorization_handoff_denied_at,
  oauth_authorization_handoff_completed_at,
  oauth_authorization_handoff_expires_at,
  oauth_authorization_handoff_created_at,
  oauth_authorization_handoff_updated_at
`

type MarkOAuthAuthorizationHandoffCompletedByIDRow struct {
	OauthAuthorizationHandoffID                  uuid.UUID          `json:"oauth_authorization_handoff_id"`
	OauthAuthorizationHandoffTokenHash           string             `json:"oauth_authorization_handoff_token_hash"`
	OauthAuthorizationHandoffUserCode            string             `json:"oauth_authorization_handoff_user_code"`
	OauthClientID                                string             `json:"oauth_client_id"`
	OauthAuthorizationHandoffRedirectUri         string             `json:"oauth_authorization_handoff_redirect_uri"`
	OauthAuthorizationHandoffScopes              []string           `json:"oauth_authorization_handoff_scopes"`
	OauthAuthorizationHandoffAudience            string             `json:"oauth_authorization_handoff_audience"`
	OauthAuthorizationHandoffState               string             `json:"oauth_authorization_handoff_state"`
	OauthAuthorizationHandoffCodeChallenge       string             `json:"oauth_authorization_handoff_code_challenge"`
	OauthAuthorizationHandoffCodeChallengeMethod string             `json:"oauth_authorization_handoff_code_challenge_method"`
	UserUuid                                     pgtype.UUID        `json:"user_uuid"`
	OauthAuthorizationHandoffAuthorizationCode   *string            `json:"oauth_authorization_handoff_authorization_code"`
	OauthAuthorizationHandoffRedirectUrl         *string            `json:"oauth_authorization_handoff_redirect_url"`
	OauthAuthorizationHandoffDeniedAt            pgtype.Timestamptz `json:"oauth_authorization_handoff_denied_at"`
	OauthAuthorizationHandoffCompletedAt         pgtype.Timestamptz `json:"oauth_authorization_handoff_completed_at"`
	OauthAuthorizationHandoffExpiresAt           time.Time          `json:"oauth_authorization_handoff_expires_at"`
	OauthAuthorizationHandoffCreatedAt           time.Time          `json:"oauth_authorization_handoff_created_at"`
	OauthAuthorizationHandoffUpdatedAt           time.Time          `json:"oauth_authorization_handoff_updated_at"`
}

func (q *Queries) MarkOAuthAuthorizationHandoffCompletedByID(ctx context.Context, oauthAuthorizationHandoffID pgtype.UUID) (MarkOAuthAuthorizationHandoffCompletedByIDRow, error) {
	row := q.db.QueryRow(ctx, markOAuthAuthorizationHandoffCompletedByID, oauthAuthorizationHandoffID)
	var i MarkOAuthAuthorizationHandoffCompletedByIDRow
	err := row.Scan(
		&i.OauthAuthorizationHandoffID,
		&i.OauthAuthorizationHandoffTokenHash,
		&i.OauthAuthorizationHandoffUserCode,
		&i.OauthClientID,
		&i.OauthAuthorizationHandoffRedirectUri,
		&i.OauthAuthorizationHandoffScopes,
		&i.OauthAuthorizationHandoffAudience,
		&i.OauthAuthorizationHandoffState,
		&i.OauthAuthorizationHandoffCodeChallenge,
		&i.OauthAuthorizationHandoffCodeChallengeMethod,
		&i.UserUuid,
		&i.OauthAuthorizationHandoffAuthorizationCode,
		&i.OauthAuthorizationHandoffRedirectUrl,
		&i.OauthAuthorizationHandoffDeniedAt,
		&i.OauthAuthorizationHandoffCompletedAt,
		&i.OauthAuthorizationHandoffExpiresAt,
		&i.OauthAuthorizationHandoffCreatedAt,
		&i.OauthAuthorizationHandoffUpdatedAt,
	)
	return i, err
}
