// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_device_authorizations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const approveOAuthDeviceAuthorizationByUserCode = `-- name: ApproveOAuthDeviceAuthorizationByUserCode :one
update oauth_device_authorizations
set
  user_uuid = $1,
  oauth_device_authorization_approved_at = now(),
  oauth_device_authorization_updated_at = now()
where
  oauth_device_authorization_user_code = $2
  and oauth_device_authorization_approved_at is null
  and oauth_device_authorization_denied_at is null
  and oauth_device_authorization_consumed_at is null
  and oauth_device_authorization_expires_at > now()
returning
  oauth_device_authorization_id,
  oauth_device_authorization_device_code_hash,
  oauth_client_id,
  oauth_device_authorization_user_code,
  oauth_device_authorization_scopes,
  oauth_device_authorization_audience,
  user_uuid,
  oauth_device_authorization_expires_at,
  oauth_device_authorization_approved_at,
  oauth_device_authorization_denied_at,
  oauth_device_authorization_consumed_at,
  oauth_device_authorization_created_at,
  oauth_device_authorization_updated_at
`

type ApproveOAuthDeviceAuthorizationByUserCodeParams struct {
	UserUuid                         *uuid.UUID `json:"user_uuid"`
	OauthDeviceAuthorizationUserCode *string    `json:"oauth_device_authorization_user_code"`
}

type ApproveOAuthDeviceAuthorizationByUserCodeRow struct {
	OauthDeviceAuthorizationID             uuid.UUID  `json:"oauth_device_authorization_id"`
	OauthDeviceAuthorizationDeviceCodeHash string     `json:"oauth_device_authorization_device_code_hash"`
	OauthClientID                          string     `json:"oauth_client_id"`
	OauthDeviceAuthorizationUserCode       string     `json:"oauth_device_authorization_user_code"`
	OauthDeviceAuthorizationScopes         []string   `json:"oauth_device_authorization_scopes"`
	OauthDeviceAuthorizationAudience       string     `json:"oauth_device_authorization_audience"`
	UserUuid                               *uuid.UUID `json:"user_uuid"`
	OauthDeviceAuthorizationExpiresAt      time.Time  `json:"oauth_device_authorization_expires_at"`
	OauthDeviceAuthorizationApprovedAt     *time.Time `json:"oauth_device_authorization_approved_at"`
	OauthDeviceAuthorizationDeniedAt       *time.Time `json:"oauth_device_authorization_denied_at"`
	OauthDeviceAuthorizationConsumedAt     *time.Time `json:"oauth_device_authorization_consumed_at"`
	OauthDeviceAuthorizationCreatedAt      time.Time  `json:"oauth_device_authorization_created_at"`
	OauthDeviceAuthorizationUpdatedAt      time.Time  `json:"oauth_device_authorization_updated_at"`
}

func (q *Queries) ApproveOAuthDeviceAuthorizationByUserCode(ctx context.Context, arg ApproveOAuthDeviceAuthorizationByUserCodeParams) (ApproveOAuthDeviceAuthorizationByUserCodeRow, error) {
	row := q.db.QueryRow(ctx, approveOAuthDeviceAuthorizationByUserCode, arg.UserUuid, arg.OauthDeviceAuthorizationUserCode)
	var i ApproveOAuthDeviceAuthorizationByUserCodeRow
	err := row.Scan(
		&i.OauthDeviceAuthorizationID,
		&i.OauthDeviceAuthorizationDeviceCodeHash,
		&i.OauthClientID,
		&i.OauthDeviceAuthorizationUserCode,
		&i.OauthDeviceAuthorizationScopes,
		&i.OauthDeviceAuthorizationAudience,
		&i.UserUuid,
		&i.OauthDeviceAuthorizationExpiresAt,
		&i.OauthDeviceAuthorizationApprovedAt,
		&i.OauthDeviceAuthorizationDeniedAt,
		&i.OauthDeviceAuthorizationConsumedAt,
		&i.OauthDeviceAuthorizationCreatedAt,
		&i.OauthDeviceAuthorizationUpdatedAt,
	)
	return i, err
}

const consumeOAuthDeviceAuthorizationByID = `-- name: ConsumeOAuthDeviceAuthorizationByID :one
update oauth_device_authorizations
set
  oauth_device_authorization_consumed_at = now(),
  oauth_device_authorization_updated_at = now()
where
  oauth_device_authorization_id = $1
  and oauth_device_authorization_consumed_at is null
returning
  oauth_device_authorization_id,
  oauth_device_authorization_device_code_hash,
  oauth_client_id,
  oauth_device_authorization_user_code,
  oauth_device_authorization_scopes,
  user_uuid,
  oauth_device_authorization_expires_at,
  oauth_device_authorization_approved_at,
  oauth_device_authorization_denied_at,
  oauth_device_authorization_consumed_at,
  oauth_device_authorization_created_at,
  oauth_device_authorization_updated_at
`

type ConsumeOAuthDeviceAuthorizationByIDRow struct {
	OauthDeviceAuthorizationID             uuid.UUID  `json:"oauth_device_authorization_id"`
	OauthDeviceAuthorizationDeviceCodeHash string     `json:"oauth_device_authorization_device_code_hash"`
	OauthClientID                          string     `json:"oauth_client_id"`
	OauthDeviceAuthorizationUserCode       string     `json:"oauth_device_authorization_user_code"`
	OauthDeviceAuthorizationScopes         []string   `json:"oauth_device_authorization_scopes"`
	UserUuid                               *uuid.UUID `json:"user_uuid"`
	OauthDeviceAuthorizationExpiresAt      time.Time  `json:"oauth_device_authorization_expires_at"`
	OauthDeviceAuthorizationApprovedAt     *time.Time `json:"oauth_device_authorization_approved_at"`
	OauthDeviceAuthorizationDeniedAt       *time.Time `json:"oauth_device_authorization_denied_at"`
	OauthDeviceAuthorizationConsumedAt     *time.Time `json:"oauth_device_authorization_consumed_at"`
	OauthDeviceAuthorizationCreatedAt      time.Time  `json:"oauth_device_authorization_created_at"`
	OauthDeviceAuthorizationUpdatedAt      time.Time  `json:"oauth_device_authorization_updated_at"`
}

func (q *Queries) ConsumeOAuthDeviceAuthorizationByID(ctx context.Context, oauthDeviceAuthorizationID *uuid.UUID) (ConsumeOAuthDeviceAuthorizationByIDRow, error) {
	row := q.db.QueryRow(ctx, consumeOAuthDeviceAuthorizationByID, oauthDeviceAuthorizationID)
	var i ConsumeOAuthDeviceAuthorizationByIDRow
	err := row.Scan(
		&i.OauthDeviceAuthorizationID,
		&i.OauthDeviceAuthorizationDeviceCodeHash,
		&i.OauthClientID,
		&i.OauthDeviceAuthorizationUserCode,
		&i.OauthDeviceAuthorizationScopes,
		&i.UserUuid,
		&i.OauthDeviceAuthorizationExpiresAt,
		&i.OauthDeviceAuthorizationApprovedAt,
		&i.OauthDeviceAuthorizationDeniedAt,
		&i.OauthDeviceAuthorizationConsumedAt,
		&i.OauthDeviceAuthorizationCreatedAt,
		&i.OauthDeviceAuthorizationUpdatedAt,
	)
	return i, err
}

const createOAuthDeviceAuthorization = `-- name: CreateOAuthDeviceAuthorization :one
insert into oauth_device_authorizations (
  oauth_device_authorization_device_code_hash,
  oauth_client_id,
  oauth_device_authorization_user_code,
  oauth_device_authorization_scopes,
  oauth_device_authorization_audience,
  oauth_device_authorization_expires_at
) values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
returning
  oauth_device_authorization_id,
  oauth_device_authorization_device_code_hash,
  oauth_client_id,
  oauth_device_authorization_user_code,
  oauth_device_authorization_scopes,
  oauth_device_authorization_audience,
  user_uuid,
  oauth_device_authorization_expires_at,
  oauth_device_authorization_approved_at,
  oauth_device_authorization_denied_at,
  oauth_device_authorization_consumed_at,
  oauth_device_authorization_created_at,
  oauth_device_authorization_updated_at
`

type CreateOAuthDeviceAuthorizationParams struct {
	OauthDeviceAuthorizationDeviceCodeHash *string    `json:"oauth_device_authorization_device_code_hash"`
	OauthClientID                          *string    `json:"oauth_client_id"`
	OauthDeviceAuthorizationUserCode       *string    `json:"oauth_device_authorization_user_code"`
	OauthDeviceAuthorizationScopes         []string   `json:"oauth_device_authorization_scopes"`
	OauthDeviceAuthorizationAudience       *string    `json:"oauth_device_authorization_audience"`
	OauthDeviceAuthorizationExpiresAt      *time.Time `json:"oauth_device_authorization_expires_at"`
}

type CreateOAuthDeviceAuthorizationRow struct {
	OauthDeviceAuthorizationID             uuid.UUID  `json:"oauth_device_authorization_id"`
	OauthDeviceAuthorizationDeviceCodeHash string     `json:"oauth_device_authorization_device_code_hash"`
	OauthClientID                          string     `json:"oauth_client_id"`
	OauthDeviceAuthorizationUserCode       string     `json:"oauth_device_authorization_user_code"`
	OauthDeviceAuthorizationScopes         []string   `json:"oauth_device_authorization_scopes"`
	OauthDeviceAuthorizationAudience       string     `json:"oauth_device_authorization_audience"`
	UserUuid                               *uuid.UUID `json:"user_uuid"`
	OauthDeviceAuthorizationExpiresAt      time.Time  `json:"oauth_device_authorization_expires_at"`
	OauthDeviceAuthorizationApprovedAt     *time.Time `json:"oauth_device_authorization_approved_at"`
	OauthDeviceAuthorizationDeniedAt       *time.Time `json:"oauth_device_authorization_denied_at"`
	OauthDeviceAuthorizationConsumedAt     *time.Time `json:"oauth_device_authorization_consumed_at"`
	OauthDeviceAuthorizationCreatedAt      time.Time  `json:"oauth_device_authorization_created_at"`
	OauthDeviceAuthorizationUpdatedAt      time.Time  `json:"oauth_device_authorization_updated_at"`
}

func (q *Queries) CreateOAuthDeviceAuthorization(ctx context.Context, arg CreateOAuthDeviceAuthorizationParams) (CreateOAuthDeviceAuthorizationRow, error) {
	row := q.db.QueryRow(ctx, createOAuthDeviceAuthorization,
		arg.OauthDeviceAuthorizationDeviceCodeHash,
		arg.OauthClientID,
		arg.OauthDeviceAuthorizationUserCode,
		arg.OauthDeviceAuthorizationScopes,
		arg.OauthDeviceAuthorizationAudience,
		arg.OauthDeviceAuthorizationExpiresAt,
	)
	var i CreateOAuthDeviceAuthorizationRow
	err := row.Scan(
		&i.OauthDeviceAuthorizationID,
		&i.OauthDeviceAuthorizationDeviceCodeHash,
		&i.OauthClientID,
		&i.OauthDeviceAuthorizationUserCode,
		&i.OauthDeviceAuthorizationScopes,
		&i.OauthDeviceAuthorizationAudience,
		&i.UserUuid,
		&i.OauthDeviceAuthorizationExpiresAt,
		&i.OauthDeviceAuthorizationApprovedAt,
		&i.OauthDeviceAuthorizationDeniedAt,
		&i.OauthDeviceAuthorizationConsumedAt,
		&i.OauthDeviceAuthorizationCreatedAt,
		&i.OauthDeviceAuthorizationUpdatedAt,
	)
	return i, err
}

const denyOAuthDeviceAuthorizationByUserCode = `-- name: DenyOAuthDeviceAuthorizationByUserCode :one
update oauth_device_authorizations
set
  oauth_device_authorization_denied_at = now(),
  oauth_device_authorization_updated_at = now()
where
  oauth_device_authorization_user_code = $1
  and oauth_device_authorization_denied_at is null
  and oauth_device_authorization_consumed_at is null
  and oauth_device_authorization_expires_at > now()
returning
  oauth_device_authorization_id,
  oauth_device_authorization_device_code_hash,
  oauth_client_id,
  oauth_device_authorization_user_code,
  oauth_device_authorization_scopes,
  oauth_device_authorization_audience,
  user_uuid,
  oauth_device_authorization_expires_at,
  oauth_device_authorization_approved_at,
  oauth_device_authorization_denied_at,
  oauth_device_authorization_consumed_at,
  oauth_device_authorization_created_at,
  oauth_device_authorization_updated_at
`

type DenyOAuthDeviceAuthorizationByUserCodeRow struct {
	OauthDeviceAuthorizationID             uuid.UUID  `json:"oauth_device_authorization_id"`
	OauthDeviceAuthorizationDeviceCodeHash string     `json:"oauth_device_authorization_device_code_hash"`
	OauthClientID                          string     `json:"oauth_client_id"`
	OauthDeviceAuthorizationUserCode       string     `json:"oauth_device_authorization_user_code"`
	OauthDeviceAuthorizationScopes         []string   `json:"oauth_device_authorization_scopes"`
	OauthDeviceAuthorizationAudience       string     `json:"oauth_device_authorization_audience"`
	UserUuid                               *uuid.UUID `json:"user_uuid"`
	OauthDeviceAuthorizationExpiresAt      time.Time  `json:"oauth_device_authorization_expires_at"`
	OauthDeviceAuthorizationApprovedAt     *time.Time `json:"oauth_device_authorization_approved_at"`
	OauthDeviceAuthorizationDeniedAt       *time.Time `json:"oauth_device_authorization_denied_at"`
	OauthDeviceAuthorizationConsumedAt     *time.Time `json:"oauth_device_authorization_consumed_at"`
	OauthDeviceAuthorizationCreatedAt      time.Time  `json:"oauth_device_authorization_created_at"`
	OauthDeviceAuthorizationUpdatedAt      time.Time  `json:"oauth_device_authorization_updated_at"`
}

func (q *Queries) DenyOAuthDeviceAuthorizationByUserCode(ctx context.Context, oauthDeviceAuthorizationUserCode *string) (DenyOAuthDeviceAuthorizationByUserCodeRow, error) {
	row := q.db.QueryRow(ctx, denyOAuthDeviceAuthorizationByUserCode, oauthDeviceAuthorizationUserCode)
	var i DenyOAuthDeviceAuthorizationByUserCodeRow
	err := row.Scan(
		&i.OauthDeviceAuthorizationID,
		&i.OauthDeviceAuthorizationDeviceCodeHash,
		&i.OauthClientID,
		&i.OauthDeviceAuthorizationUserCode,
		&i.OauthDeviceAuthorizationScopes,
		&i.OauthDeviceAuthorizationAudience,
		&i.UserUuid,
		&i.OauthDeviceAuthorizationExpiresAt,
		&i.OauthDeviceAuthorizationApprovedAt,
		&i.OauthDeviceAuthorizationDeniedAt,
		&i.OauthDeviceAuthorizationConsumedAt,
		&i.OauthDeviceAuthorizationCreatedAt,
		&i.OauthDeviceAuthorizationUpdatedAt,
	)
	return i, err
}

const getOAuthDeviceAuthorizationByDeviceCodeHash = `-- name: GetOAuthDeviceAuthorizationByDeviceCodeHash :one
select
  oauth_device_authorization_id,
  oauth_device_authorization_device_code_hash,
  oauth_client_id,
  oauth_device_authorization_user_code,
  oauth_device_authorization_scopes,
  oauth_device_authorization_audience,
  user_uuid,
  oauth_device_authorization_expires_at,
  oauth_device_authorization_approved_at,
  oauth_device_authorization_denied_at,
  oauth_device_authorization_consumed_at,
  oauth_device_authorization_created_at,
  oauth_device_authorization_updated_at
from oauth_device_authorizations
where oauth_device_authorization_device_code_hash = $1
`

type GetOAuthDeviceAuthorizationByDeviceCodeHashRow struct {
	OauthDeviceAuthorizationID             uuid.UUID  `json:"oauth_device_authorization_id"`
	OauthDeviceAuthorizationDeviceCodeHash string     `json:"oauth_device_authorization_device_code_hash"`
	OauthClientID                          string     `json:"oauth_client_id"`
	OauthDeviceAuthorizationUserCode       string     `json:"oauth_device_authorization_user_code"`
	OauthDeviceAuthorizationScopes         []string   `json:"oauth_device_authorization_scopes"`
	OauthDeviceAuthorizationAudience       string     `json:"oauth_device_authorization_audience"`
	UserUuid                               *uuid.UUID `json:"user_uuid"`
	OauthDeviceAuthorizationExpiresAt      time.Time  `json:"oauth_device_authorization_expires_at"`
	OauthDeviceAuthorizationApprovedAt     *time.Time `json:"oauth_device_authorization_approved_at"`
	OauthDeviceAuthorizationDeniedAt       *time.Time `json:"oauth_device_authorization_denied_at"`
	OauthDeviceAuthorizationConsumedAt     *time.Time `json:"oauth_device_authorization_consumed_at"`
	OauthDeviceAuthorizationCreatedAt      time.Time  `json:"oauth_device_authorization_created_at"`
	OauthDeviceAuthorizationUpdatedAt      time.Time  `json:"oauth_device_authorization_updated_at"`
}

func (q *Queries) GetOAuthDeviceAuthorizationByDeviceCodeHash(ctx context.Context, oauthDeviceAuthorizationDeviceCodeHash *string) (GetOAuthDeviceAuthorizationByDeviceCodeHashRow, error) {
	row := q.db.QueryRow(ctx, getOAuthDeviceAuthorizationByDeviceCodeHash, oauthDeviceAuthorizationDeviceCodeHash)
	var i GetOAuthDeviceAuthorizationByDeviceCodeHashRow
	err := row.Scan(
		&i.OauthDeviceAuthorizationID,
		&i.OauthDeviceAuthorizationDeviceCodeHash,
		&i.OauthClientID,
		&i.OauthDeviceAuthorizationUserCode,
		&i.OauthDeviceAuthorizationScopes,
		&i.OauthDeviceAuthorizationAudience,
		&i.UserUuid,
		&i.OauthDeviceAuthorizationExpiresAt,
		&i.OauthDeviceAuthorizationApprovedAt,
		&i.OauthDeviceAuthorizationDeniedAt,
		&i.OauthDeviceAuthorizationConsumedAt,
		&i.OauthDeviceAuthorizationCreatedAt,
		&i.OauthDeviceAuthorizationUpdatedAt,
	)
	return i, err
}

const getOAuthDeviceAuthorizationByUserCode = `-- name: GetOAuthDeviceAuthorizationByUserCode :one
select
  oauth_device_authorization_id,
  oauth_device_authorization_device_code_hash,
  oauth_client_id,
  oauth_device_authorization_user_code,
  oauth_device_authorization_scopes,
  oauth_device_authorization_audience,
  user_uuid,
  oauth_device_authorization_expires_at,
  oauth_device_authorization_approved_at,
  oauth_device_authorization_denied_at,
  oauth_device_authorization_consumed_at,
  oauth_device_authorization_created_at,
  oauth_device_authorization_updated_at
from oauth_device_authorizations
where oauth_device_authorization_user_code = $1
`

type GetOAuthDeviceAuthorizationByUserCodeRow struct {
	OauthDeviceAuthorizationID             uuid.UUID  `json:"oauth_device_authorization_id"`
	OauthDeviceAuthorizationDeviceCodeHash string     `json:"oauth_device_authorization_device_code_hash"`
	OauthClientID                          string     `json:"oauth_client_id"`
	OauthDeviceAuthorizationUserCode       string     `json:"oauth_device_authorization_user_code"`
	OauthDeviceAuthorizationScopes         []string   `json:"oauth_device_authorization_scopes"`
	OauthDeviceAuthorizationAudience       string     `json:"oauth_device_authorization_audience"`
	UserUuid                               *uuid.UUID `json:"user_uuid"`
	OauthDeviceAuthorizationExpiresAt      time.Time  `json:"oauth_device_authorization_expires_at"`
	OauthDeviceAuthorizationApprovedAt     *time.Time `json:"oauth_device_authorization_approved_at"`
	OauthDeviceAuthorizationDeniedAt       *time.Time `json:"oauth_device_authorization_denied_at"`
	OauthDeviceAuthorizationConsumedAt     *time.Time `json:"oauth_device_authorization_consumed_at"`
	OauthDeviceAuthorizationCreatedAt      time.Time  `json:"oauth_device_authorization_created_at"`
	OauthDeviceAuthorizationUpdatedAt      time.Time  `json:"oauth_device_authorization_updated_at"`
}

func (q *Queries) GetOAuthDeviceAuthorizationByUserCode(ctx context.Context, oauthDeviceAuthorizationUserCode *string) (GetOAuthDeviceAuthorizationByUserCodeRow, error) {
	row := q.db.QueryRow(ctx, getOAuthDeviceAuthorizationByUserCode, oauthDeviceAuthorizationUserCode)
	var i GetOAuthDeviceAuthorizationByUserCodeRow
	err := row.Scan(
		&i.OauthDeviceAuthorizationID,
		&i.OauthDeviceAuthorizationDeviceCodeHash,
		&i.OauthClientID,
		&i.OauthDeviceAuthorizationUserCode,
		&i.OauthDeviceAuthorizationScopes,
		&i.OauthDeviceAuthorizationAudience,
		&i.UserUuid,
		&i.OauthDeviceAuthorizationExpiresAt,
		&i.OauthDeviceAuthorizationApprovedAt,
		&i.OauthDeviceAuthorizationDeniedAt,
		&i.OauthDeviceAuthorizationConsumedAt,
		&i.OauthDeviceAuthorizationCreatedAt,
		&i.OauthDeviceAuthorizationUpdatedAt,
	)
	return i, err
}
