// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: searches.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const listTransactionsByNeighborhoods = `-- name: ListTransactionsByNeighborhoods :many
WITH selected_neighborhoods AS (
    SELECT UNNEST($1::uuid[]) AS neighborhood_id
)
SELECT
    ht.prices_transaction_id,
    ht.prices_transaction_description,
    ht.prices_transaction_type,
    ht.prices_transaction_area,
    ht.prices_transaction_price,
    ht.prices_transaction_price_per_square_meter,
    ht.prices_transaction_build_year,
    ht.prices_transaction_floor,
    ht.prices_transaction_elevator,
    ht.prices_transaction_condition,
    ht.prices_transaction_plot,
    ht.prices_transaction_energy_class,
    ht.prices_transaction_period_identifier,
    ht.prices_transaction_created_at,
    ht.prices_transaction_updated_at,
    ht.prices_transaction_category,
    hn.prices_neighborhood_id,
    hn.prices_neighborhood_name,
    hp.prices_postal_code_code,
    hc.prices_city_name
FROM public.prices_transactions AS ht
JOIN selected_neighborhoods AS sn
    ON sn.neighborhood_id = ht.prices_neighborhood_id
LEFT JOIN public.prices_neighborhoods AS hn
    ON ht.prices_neighborhood_id = hn.prices_neighborhood_id
LEFT JOIN public.prices_postal_codes AS hp
    ON hn.prices_postal_code_id = hp.prices_postal_code_id
LEFT JOIN public.prices_cities AS hc
    ON hn.prices_city_id = hc.prices_city_id
ORDER BY ht.prices_transaction_created_at DESC
`

type ListTransactionsByNeighborhoodsRow struct {
	PricesTransactionID                  pgtype.UUID `db:"prices_transaction_id" json:"prices_transaction_id"`
	PricesTransactionDescription         string      `db:"prices_transaction_description" json:"prices_transaction_description"`
	PricesTransactionType                string      `db:"prices_transaction_type" json:"prices_transaction_type"`
	PricesTransactionArea                float64     `db:"prices_transaction_area" json:"prices_transaction_area"`
	PricesTransactionPrice               int32       `db:"prices_transaction_price" json:"prices_transaction_price"`
	PricesTransactionPricePerSquareMeter int32       `db:"prices_transaction_price_per_square_meter" json:"prices_transaction_price_per_square_meter"`
	PricesTransactionBuildYear           int32       `db:"prices_transaction_build_year" json:"prices_transaction_build_year"`
	PricesTransactionFloor               *string     `db:"prices_transaction_floor" json:"prices_transaction_floor"`
	PricesTransactionElevator            bool        `db:"prices_transaction_elevator" json:"prices_transaction_elevator"`
	PricesTransactionCondition           *string     `db:"prices_transaction_condition" json:"prices_transaction_condition"`
	PricesTransactionPlot                *string     `db:"prices_transaction_plot" json:"prices_transaction_plot"`
	PricesTransactionEnergyClass         *string     `db:"prices_transaction_energy_class" json:"prices_transaction_energy_class"`
	PricesTransactionPeriodIdentifier    string      `db:"prices_transaction_period_identifier" json:"prices_transaction_period_identifier"`
	PricesTransactionCreatedAt           time.Time   `db:"prices_transaction_created_at" json:"prices_transaction_created_at"`
	PricesTransactionUpdatedAt           time.Time   `db:"prices_transaction_updated_at" json:"prices_transaction_updated_at"`
	PricesTransactionCategory            string      `db:"prices_transaction_category" json:"prices_transaction_category"`
	PricesNeighborhoodID                 pgtype.UUID `db:"prices_neighborhood_id" json:"prices_neighborhood_id"`
	PricesNeighborhoodName               *string     `db:"prices_neighborhood_name" json:"prices_neighborhood_name"`
	PricesPostalCodeCode                 *string     `db:"prices_postal_code_code" json:"prices_postal_code_code"`
	PricesCityName                       *string     `db:"prices_city_name" json:"prices_city_name"`
}

func (q *Queries) ListTransactionsByNeighborhoods(ctx context.Context, neighborhoodIds []pgtype.UUID) ([]ListTransactionsByNeighborhoodsRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByNeighborhoods, neighborhoodIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsByNeighborhoodsRow{}
	for rows.Next() {
		var i ListTransactionsByNeighborhoodsRow
		if err := rows.Scan(
			&i.PricesTransactionID,
			&i.PricesTransactionDescription,
			&i.PricesTransactionType,
			&i.PricesTransactionArea,
			&i.PricesTransactionPrice,
			&i.PricesTransactionPricePerSquareMeter,
			&i.PricesTransactionBuildYear,
			&i.PricesTransactionFloor,
			&i.PricesTransactionElevator,
			&i.PricesTransactionCondition,
			&i.PricesTransactionPlot,
			&i.PricesTransactionEnergyClass,
			&i.PricesTransactionPeriodIdentifier,
			&i.PricesTransactionCreatedAt,
			&i.PricesTransactionUpdatedAt,
			&i.PricesTransactionCategory,
			&i.PricesNeighborhoodID,
			&i.PricesNeighborhoodName,
			&i.PricesPostalCodeCode,
			&i.PricesCityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByPostalSelection = `-- name: ListTransactionsByPostalSelection :many
SELECT
    ht.prices_transaction_id,
    ht.prices_transaction_description,
    ht.prices_transaction_type,
    ht.prices_transaction_area,
    ht.prices_transaction_price,
    ht.prices_transaction_price_per_square_meter,
    ht.prices_transaction_build_year,
    ht.prices_transaction_floor,
    ht.prices_transaction_elevator,
    ht.prices_transaction_condition,
    ht.prices_transaction_plot,
    ht.prices_transaction_energy_class,
    ht.prices_transaction_period_identifier,
    ht.prices_transaction_created_at,
    ht.prices_transaction_updated_at,
    ht.prices_transaction_category,
    pn.prices_neighborhood_id,
    pn.prices_neighborhood_name,
    ppc.postal_postal_code_id,
    ppc.postal_postal_code_code,
    ppc.postal_postal_code_name_fi,
    pm.postal_municipality_id,
    pm.postal_municipality_name_fi
FROM public.prices_transactions AS ht
JOIN public.prices_neighborhoods AS pn
    ON pn.prices_neighborhood_id = ht.prices_neighborhood_id
JOIN public.postal_postal_codes AS ppc
    ON ppc.postal_postal_code_id = pn.prices_neighborhood_postal_postal_code_id
JOIN public.postal_municipalities AS pm
    ON pm.postal_municipality_id = ppc.postal_municipality_id
WHERE pn.prices_neighborhood_postal_postal_code_id IS NOT NULL
  AND pm.postal_municipality_id = $1
  AND ppc.postal_postal_code_id = $2
ORDER BY ht.prices_transaction_created_at DESC
`

type ListTransactionsByPostalSelectionParams struct {
	MunicipalityID pgtype.UUID `db:"municipality_id" json:"municipality_id"`
	PostalCodeID   pgtype.UUID `db:"postal_code_id" json:"postal_code_id"`
}

type ListTransactionsByPostalSelectionRow struct {
	PricesTransactionID                  pgtype.UUID `db:"prices_transaction_id" json:"prices_transaction_id"`
	PricesTransactionDescription         string      `db:"prices_transaction_description" json:"prices_transaction_description"`
	PricesTransactionType                string      `db:"prices_transaction_type" json:"prices_transaction_type"`
	PricesTransactionArea                float64     `db:"prices_transaction_area" json:"prices_transaction_area"`
	PricesTransactionPrice               int32       `db:"prices_transaction_price" json:"prices_transaction_price"`
	PricesTransactionPricePerSquareMeter int32       `db:"prices_transaction_price_per_square_meter" json:"prices_transaction_price_per_square_meter"`
	PricesTransactionBuildYear           int32       `db:"prices_transaction_build_year" json:"prices_transaction_build_year"`
	PricesTransactionFloor               *string     `db:"prices_transaction_floor" json:"prices_transaction_floor"`
	PricesTransactionElevator            bool        `db:"prices_transaction_elevator" json:"prices_transaction_elevator"`
	PricesTransactionCondition           *string     `db:"prices_transaction_condition" json:"prices_transaction_condition"`
	PricesTransactionPlot                *string     `db:"prices_transaction_plot" json:"prices_transaction_plot"`
	PricesTransactionEnergyClass         *string     `db:"prices_transaction_energy_class" json:"prices_transaction_energy_class"`
	PricesTransactionPeriodIdentifier    string      `db:"prices_transaction_period_identifier" json:"prices_transaction_period_identifier"`
	PricesTransactionCreatedAt           time.Time   `db:"prices_transaction_created_at" json:"prices_transaction_created_at"`
	PricesTransactionUpdatedAt           time.Time   `db:"prices_transaction_updated_at" json:"prices_transaction_updated_at"`
	PricesTransactionCategory            string      `db:"prices_transaction_category" json:"prices_transaction_category"`
	PricesNeighborhoodID                 pgtype.UUID `db:"prices_neighborhood_id" json:"prices_neighborhood_id"`
	PricesNeighborhoodName               string      `db:"prices_neighborhood_name" json:"prices_neighborhood_name"`
	PostalPostalCodeID                   pgtype.UUID `db:"postal_postal_code_id" json:"postal_postal_code_id"`
	PostalPostalCodeCode                 string      `db:"postal_postal_code_code" json:"postal_postal_code_code"`
	PostalPostalCodeNameFi               string      `db:"postal_postal_code_name_fi" json:"postal_postal_code_name_fi"`
	PostalMunicipalityID                 pgtype.UUID `db:"postal_municipality_id" json:"postal_municipality_id"`
	PostalMunicipalityNameFi             string      `db:"postal_municipality_name_fi" json:"postal_municipality_name_fi"`
}

func (q *Queries) ListTransactionsByPostalSelection(ctx context.Context, arg *ListTransactionsByPostalSelectionParams) ([]ListTransactionsByPostalSelectionRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByPostalSelection, arg.MunicipalityID, arg.PostalCodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsByPostalSelectionRow{}
	for rows.Next() {
		var i ListTransactionsByPostalSelectionRow
		if err := rows.Scan(
			&i.PricesTransactionID,
			&i.PricesTransactionDescription,
			&i.PricesTransactionType,
			&i.PricesTransactionArea,
			&i.PricesTransactionPrice,
			&i.PricesTransactionPricePerSquareMeter,
			&i.PricesTransactionBuildYear,
			&i.PricesTransactionFloor,
			&i.PricesTransactionElevator,
			&i.PricesTransactionCondition,
			&i.PricesTransactionPlot,
			&i.PricesTransactionEnergyClass,
			&i.PricesTransactionPeriodIdentifier,
			&i.PricesTransactionCreatedAt,
			&i.PricesTransactionUpdatedAt,
			&i.PricesTransactionCategory,
			&i.PricesNeighborhoodID,
			&i.PricesNeighborhoodName,
			&i.PostalPostalCodeID,
			&i.PostalPostalCodeCode,
			&i.PostalPostalCodeNameFi,
			&i.PostalMunicipalityID,
			&i.PostalMunicipalityNameFi,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsFiltered = `-- name: ListTransactionsFiltered :many
SELECT
    ht.prices_transaction_id,
    ht.prices_transaction_description,
    ht.prices_transaction_type,
    ht.prices_transaction_area,
    ht.prices_transaction_price,
    ht.prices_transaction_price_per_square_meter,
    ht.prices_transaction_build_year,
    ht.prices_transaction_floor,
    ht.prices_transaction_elevator,
    ht.prices_transaction_condition,
    ht.prices_transaction_plot,
    ht.prices_transaction_energy_class,
    ht.prices_transaction_period_identifier,
    ht.prices_transaction_created_at,
    ht.prices_transaction_updated_at,
    ht.prices_transaction_category,
    pn.prices_neighborhood_id,
    pn.prices_neighborhood_name,
    ppc.postal_postal_code_id,
    ppc.postal_postal_code_code,
    ppc.postal_postal_code_name_fi,
    pm.postal_municipality_id,
    pm.postal_municipality_name_fi
FROM public.prices_transactions AS ht
JOIN public.prices_neighborhoods AS pn
    ON pn.prices_neighborhood_id = ht.prices_neighborhood_id
JOIN public.postal_postal_codes AS ppc
    ON ppc.postal_postal_code_id = pn.prices_neighborhood_postal_postal_code_id
JOIN public.postal_municipalities AS pm
    ON pm.postal_municipality_id = ppc.postal_municipality_id
WHERE pn.prices_neighborhood_postal_postal_code_id IS NOT NULL
  AND ($1::uuid[] IS NULL OR pm.postal_municipality_id = ANY($1::uuid[]))
  AND ($2::uuid[] IS NULL OR ppc.postal_postal_code_id = ANY($2::uuid[]))
  AND ($3::text[] IS NULL OR ht.prices_transaction_category = ANY($3::text[]))
  AND ($4::text[] IS NULL OR ht.prices_transaction_type = ANY($4::text[]))
  AND ($5::double precision IS NULL OR ht.prices_transaction_area >= $5::double precision)
  AND ($6::double precision IS NULL OR ht.prices_transaction_area <= $6::double precision)
ORDER BY ht.prices_transaction_created_at DESC
LIMIT COALESCE($7::int, 100)
`

type ListTransactionsFilteredParams struct {
	MunicipalityIds []pgtype.UUID `db:"municipality_ids" json:"municipality_ids"`
	PostalCodeIds   []pgtype.UUID `db:"postal_code_ids" json:"postal_code_ids"`
	Categories      []string      `db:"categories" json:"categories"`
	Types           []string      `db:"types" json:"types"`
	MinArea         *float64      `db:"min_area" json:"min_area"`
	MaxArea         *float64      `db:"max_area" json:"max_area"`
	LimitCount      *int32        `db:"limit_count" json:"limit_count"`
}

type ListTransactionsFilteredRow struct {
	PricesTransactionID                  pgtype.UUID `db:"prices_transaction_id" json:"prices_transaction_id"`
	PricesTransactionDescription         string      `db:"prices_transaction_description" json:"prices_transaction_description"`
	PricesTransactionType                string      `db:"prices_transaction_type" json:"prices_transaction_type"`
	PricesTransactionArea                float64     `db:"prices_transaction_area" json:"prices_transaction_area"`
	PricesTransactionPrice               int32       `db:"prices_transaction_price" json:"prices_transaction_price"`
	PricesTransactionPricePerSquareMeter int32       `db:"prices_transaction_price_per_square_meter" json:"prices_transaction_price_per_square_meter"`
	PricesTransactionBuildYear           int32       `db:"prices_transaction_build_year" json:"prices_transaction_build_year"`
	PricesTransactionFloor               *string     `db:"prices_transaction_floor" json:"prices_transaction_floor"`
	PricesTransactionElevator            bool        `db:"prices_transaction_elevator" json:"prices_transaction_elevator"`
	PricesTransactionCondition           *string     `db:"prices_transaction_condition" json:"prices_transaction_condition"`
	PricesTransactionPlot                *string     `db:"prices_transaction_plot" json:"prices_transaction_plot"`
	PricesTransactionEnergyClass         *string     `db:"prices_transaction_energy_class" json:"prices_transaction_energy_class"`
	PricesTransactionPeriodIdentifier    string      `db:"prices_transaction_period_identifier" json:"prices_transaction_period_identifier"`
	PricesTransactionCreatedAt           time.Time   `db:"prices_transaction_created_at" json:"prices_transaction_created_at"`
	PricesTransactionUpdatedAt           time.Time   `db:"prices_transaction_updated_at" json:"prices_transaction_updated_at"`
	PricesTransactionCategory            string      `db:"prices_transaction_category" json:"prices_transaction_category"`
	PricesNeighborhoodID                 pgtype.UUID `db:"prices_neighborhood_id" json:"prices_neighborhood_id"`
	PricesNeighborhoodName               string      `db:"prices_neighborhood_name" json:"prices_neighborhood_name"`
	PostalPostalCodeID                   pgtype.UUID `db:"postal_postal_code_id" json:"postal_postal_code_id"`
	PostalPostalCodeCode                 string      `db:"postal_postal_code_code" json:"postal_postal_code_code"`
	PostalPostalCodeNameFi               string      `db:"postal_postal_code_name_fi" json:"postal_postal_code_name_fi"`
	PostalMunicipalityID                 pgtype.UUID `db:"postal_municipality_id" json:"postal_municipality_id"`
	PostalMunicipalityNameFi             string      `db:"postal_municipality_name_fi" json:"postal_municipality_name_fi"`
}

func (q *Queries) ListTransactionsFiltered(ctx context.Context, arg *ListTransactionsFilteredParams) ([]ListTransactionsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsFiltered,
		arg.MunicipalityIds,
		arg.PostalCodeIds,
		arg.Categories,
		arg.Types,
		arg.MinArea,
		arg.MaxArea,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsFilteredRow{}
	for rows.Next() {
		var i ListTransactionsFilteredRow
		if err := rows.Scan(
			&i.PricesTransactionID,
			&i.PricesTransactionDescription,
			&i.PricesTransactionType,
			&i.PricesTransactionArea,
			&i.PricesTransactionPrice,
			&i.PricesTransactionPricePerSquareMeter,
			&i.PricesTransactionBuildYear,
			&i.PricesTransactionFloor,
			&i.PricesTransactionElevator,
			&i.PricesTransactionCondition,
			&i.PricesTransactionPlot,
			&i.PricesTransactionEnergyClass,
			&i.PricesTransactionPeriodIdentifier,
			&i.PricesTransactionCreatedAt,
			&i.PricesTransactionUpdatedAt,
			&i.PricesTransactionCategory,
			&i.PricesNeighborhoodID,
			&i.PricesNeighborhoodName,
			&i.PostalPostalCodeID,
			&i.PostalPostalCodeCode,
			&i.PostalPostalCodeNameFi,
			&i.PostalMunicipalityID,
			&i.PostalMunicipalityNameFi,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTransactionsByCityAndAddress = `-- name: SearchTransactionsByCityAndAddress :many
SELECT
    ht.prices_transaction_id,
    ht.prices_transaction_description,
    ht.prices_transaction_type,
    ht.prices_transaction_area,
    ht.prices_transaction_price,
    ht.prices_transaction_price_per_square_meter,
    ht.prices_transaction_build_year,
    ht.prices_transaction_floor,
    ht.prices_transaction_elevator,
    ht.prices_transaction_condition,
    ht.prices_transaction_plot,
    ht.prices_transaction_energy_class,
    ht.prices_transaction_period_identifier,
    ht.prices_transaction_created_at,
    ht.prices_transaction_updated_at,
    ht.prices_transaction_category,
    pn.prices_neighborhood_name,
    COALESCE(ppc.postal_postal_code_code, ppc_prices.prices_postal_code_code) AS postal_code,
    COALESCE(ppc.postal_postal_code_name_fi, '') AS postal_area_name_fi,
    COALESCE(pm.postal_municipality_name_fi, '') AS municipality_name_fi,
    pc.prices_city_name
FROM public.prices_transactions AS ht
JOIN public.prices_neighborhoods AS pn
    ON pn.prices_neighborhood_id = ht.prices_neighborhood_id
JOIN public.prices_cities AS pc
    ON pc.prices_city_id = pn.prices_city_id
LEFT JOIN public.prices_postal_codes AS ppc_prices
    ON ppc_prices.prices_postal_code_id = pn.prices_postal_code_id
LEFT JOIN public.postal_postal_codes AS ppc
    ON ppc.postal_postal_code_id = pn.prices_neighborhood_postal_postal_code_id
LEFT JOIN public.postal_municipalities AS pm
    ON pm.postal_municipality_id = ppc.postal_municipality_id
WHERE lower(trim(pc.prices_city_name)) LIKE ('%' || lower(trim($1)) || '%')
  AND (
      trim($2) = ''
      OR pn.prices_neighborhood_name ILIKE ('%' || $2 || '%')
      OR COALESCE(ppc.postal_postal_code_code, '') ILIKE ('%' || $2 || '%')
      OR COALESCE(ppc_prices.prices_postal_code_code, '') ILIKE ('%' || $2 || '%')
      OR COALESCE(ppc.postal_postal_code_name_fi, '') ILIKE ('%' || $2 || '%')
      OR COALESCE(pm.postal_municipality_name_fi, '') ILIKE ('%' || $2 || '%')
      OR lower(regexp_replace(COALESCE(pn.prices_neighborhood_name, ''), '[^[:alnum:]]+', '', 'g'))
            LIKE ('%' || lower(regexp_replace($2, '[^[:alnum:]]+', '', 'g')) || '%')
  )
ORDER BY ht.prices_transaction_created_at DESC
LIMIT COALESCE($3::int, 200)
`

type SearchTransactionsByCityAndAddressParams struct {
	CityName   string `db:"city_name" json:"city_name"`
	SearchTerm string `db:"search_term" json:"search_term"`
	LimitCount *int32 `db:"limit_count" json:"limit_count"`
}

type SearchTransactionsByCityAndAddressRow struct {
	PricesTransactionID                  pgtype.UUID `db:"prices_transaction_id" json:"prices_transaction_id"`
	PricesTransactionDescription         string      `db:"prices_transaction_description" json:"prices_transaction_description"`
	PricesTransactionType                string      `db:"prices_transaction_type" json:"prices_transaction_type"`
	PricesTransactionArea                float64     `db:"prices_transaction_area" json:"prices_transaction_area"`
	PricesTransactionPrice               int32       `db:"prices_transaction_price" json:"prices_transaction_price"`
	PricesTransactionPricePerSquareMeter int32       `db:"prices_transaction_price_per_square_meter" json:"prices_transaction_price_per_square_meter"`
	PricesTransactionBuildYear           int32       `db:"prices_transaction_build_year" json:"prices_transaction_build_year"`
	PricesTransactionFloor               *string     `db:"prices_transaction_floor" json:"prices_transaction_floor"`
	PricesTransactionElevator            bool        `db:"prices_transaction_elevator" json:"prices_transaction_elevator"`
	PricesTransactionCondition           *string     `db:"prices_transaction_condition" json:"prices_transaction_condition"`
	PricesTransactionPlot                *string     `db:"prices_transaction_plot" json:"prices_transaction_plot"`
	PricesTransactionEnergyClass         *string     `db:"prices_transaction_energy_class" json:"prices_transaction_energy_class"`
	PricesTransactionPeriodIdentifier    string      `db:"prices_transaction_period_identifier" json:"prices_transaction_period_identifier"`
	PricesTransactionCreatedAt           time.Time   `db:"prices_transaction_created_at" json:"prices_transaction_created_at"`
	PricesTransactionUpdatedAt           time.Time   `db:"prices_transaction_updated_at" json:"prices_transaction_updated_at"`
	PricesTransactionCategory            string      `db:"prices_transaction_category" json:"prices_transaction_category"`
	PricesNeighborhoodName               string      `db:"prices_neighborhood_name" json:"prices_neighborhood_name"`
	PostalCode                           string      `db:"postal_code" json:"postal_code"`
	PostalAreaNameFi                     string      `db:"postal_area_name_fi" json:"postal_area_name_fi"`
	MunicipalityNameFi                   string      `db:"municipality_name_fi" json:"municipality_name_fi"`
	PricesCityName                       string      `db:"prices_city_name" json:"prices_city_name"`
}

func (q *Queries) SearchTransactionsByCityAndAddress(ctx context.Context, arg *SearchTransactionsByCityAndAddressParams) ([]SearchTransactionsByCityAndAddressRow, error) {
	rows, err := q.db.Query(ctx, searchTransactionsByCityAndAddress, arg.CityName, arg.SearchTerm, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTransactionsByCityAndAddressRow{}
	for rows.Next() {
		var i SearchTransactionsByCityAndAddressRow
		if err := rows.Scan(
			&i.PricesTransactionID,
			&i.PricesTransactionDescription,
			&i.PricesTransactionType,
			&i.PricesTransactionArea,
			&i.PricesTransactionPrice,
			&i.PricesTransactionPricePerSquareMeter,
			&i.PricesTransactionBuildYear,
			&i.PricesTransactionFloor,
			&i.PricesTransactionElevator,
			&i.PricesTransactionCondition,
			&i.PricesTransactionPlot,
			&i.PricesTransactionEnergyClass,
			&i.PricesTransactionPeriodIdentifier,
			&i.PricesTransactionCreatedAt,
			&i.PricesTransactionUpdatedAt,
			&i.PricesTransactionCategory,
			&i.PricesNeighborhoodName,
			&i.PostalCode,
			&i.PostalAreaNameFi,
			&i.MunicipalityNameFi,
			&i.PricesCityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
