// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: signup_email_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeActiveSignupEmailTokenByHash = `-- name: ConsumeActiveSignupEmailTokenByHash :one
update public.auth_signup_email_tokens
set auth_signup_email_consumed_at = now()
where auth_signup_email_token_hash = $1
  and auth_signup_email_consumed_at is null
  and auth_signup_email_expires_at > now()
returning
  auth_signup_email_target_email
`

func (q *Queries) ConsumeActiveSignupEmailTokenByHash(ctx context.Context, authSignupEmailTokenHash *string) (string, error) {
	row := q.db.QueryRow(ctx, consumeActiveSignupEmailTokenByHash, authSignupEmailTokenHash)
	var auth_signup_email_target_email string
	err := row.Scan(&auth_signup_email_target_email)
	return auth_signup_email_target_email, err
}

const createSignupEmailToken = `-- name: CreateSignupEmailToken :one
insert into public.auth_signup_email_tokens (
  auth_signup_email_target_email,
  auth_signup_email_token_hash,
  auth_signup_email_expires_at
)
values (
  $1,
  $2,
  $3
)
returning
  auth_signup_email_token_uuid,
  auth_signup_email_expires_at
`

type CreateSignupEmailTokenParams struct {
	AuthSignupEmailTargetEmail *string            `json:"auth_signup_email_target_email"`
	AuthSignupEmailTokenHash   *string            `json:"auth_signup_email_token_hash"`
	AuthSignupEmailExpiresAt   pgtype.Timestamptz `json:"auth_signup_email_expires_at"`
}

type CreateSignupEmailTokenRow struct {
	AuthSignupEmailTokenUuid uuid.UUID `json:"auth_signup_email_token_uuid"`
	AuthSignupEmailExpiresAt time.Time `json:"auth_signup_email_expires_at"`
}

func (q *Queries) CreateSignupEmailToken(ctx context.Context, arg CreateSignupEmailTokenParams) (CreateSignupEmailTokenRow, error) {
	row := q.db.QueryRow(ctx, createSignupEmailToken, arg.AuthSignupEmailTargetEmail, arg.AuthSignupEmailTokenHash, arg.AuthSignupEmailExpiresAt)
	var i CreateSignupEmailTokenRow
	err := row.Scan(&i.AuthSignupEmailTokenUuid, &i.AuthSignupEmailExpiresAt)
	return i, err
}

const getSignupEmailTokenStatusByHash = `-- name: GetSignupEmailTokenStatusByHash :one
select
  case
    when auth_signup_email_consumed_at is not null then 'consumed'
    when auth_signup_email_expires_at <= now() then 'expired'
    else 'active'
  end as token_status
from
  public.auth_signup_email_tokens
where
  auth_signup_email_token_hash = $1
order by
  auth_signup_email_created_at desc
limit 1
`

func (q *Queries) GetSignupEmailTokenStatusByHash(ctx context.Context, authSignupEmailTokenHash *string) (*string, error) {
	row := q.db.QueryRow(ctx, getSignupEmailTokenStatusByHash, authSignupEmailTokenHash)
	var token_status *string
	err := row.Scan(&token_status)
	return token_status, err
}

const invalidateActiveSignupEmailTokensForEmail = `-- name: InvalidateActiveSignupEmailTokensForEmail :exec
update
  public.auth_signup_email_tokens
set
  auth_signup_email_consumed_at = now()
where
  lower(btrim(auth_signup_email_target_email)) = lower(btrim($1))
  and auth_signup_email_consumed_at is null
`

func (q *Queries) InvalidateActiveSignupEmailTokensForEmail(ctx context.Context, authSignupEmailTargetEmail *string) error {
	_, err := q.db.Exec(ctx, invalidateActiveSignupEmailTokensForEmail, authSignupEmailTargetEmail)
	return err
}
