// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTasksByStatus = `-- name: CountTasksByStatus :one
SELECT COUNT(*) AS count
FROM task_queue.task
WHERE status = $1
`

func (q *Queries) CountTasksByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO task_queue.task (
    entity_id,
    task_type,
    status,
    priority,
    attempt,
    max_attempts,
    scheduled_for,
    run_on
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING task_id, entity_id, task_type, status, priority, attempt, max_attempts, last_error, worker_id, scheduled_for, started_at, completed_at, run_on, queue_message_id, created_at, updated_at
`

type CreateTaskParams struct {
	EntityID     string     `db:"entity_id" json:"entity_id"`
	TaskType     string     `db:"task_type" json:"task_type"`
	Status       string     `db:"status" json:"status"`
	Priority     int32      `db:"priority" json:"priority"`
	Attempt      int32      `db:"attempt" json:"attempt"`
	MaxAttempts  int32      `db:"max_attempts" json:"max_attempts"`
	ScheduledFor time.Time  `db:"scheduled_for" json:"scheduled_for"`
	RunOn        *time.Time `db:"run_on" json:"run_on"`
}

func (q *Queries) CreateTask(ctx context.Context, arg *CreateTaskParams) (TaskQueueTask, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.EntityID,
		arg.TaskType,
		arg.Status,
		arg.Priority,
		arg.Attempt,
		arg.MaxAttempts,
		arg.ScheduledFor,
		arg.RunOn,
	)
	var i TaskQueueTask
	err := row.Scan(
		&i.TaskID,
		&i.EntityID,
		&i.TaskType,
		&i.Status,
		&i.Priority,
		&i.Attempt,
		&i.MaxAttempts,
		&i.LastError,
		&i.WorkerID,
		&i.ScheduledFor,
		&i.StartedAt,
		&i.CompletedAt,
		&i.RunOn,
		&i.QueueMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTaskWithPriority = `-- name: CreateTaskWithPriority :one
INSERT INTO task_queue.task (
    entity_id,
    task_type,
    status,
    priority,
    attempt,
    max_attempts,
    scheduled_for,
    run_on
) VALUES (
    $1, $2, 'pending', $3, 0, $4, $5, $6
)
RETURNING task_id, entity_id, task_type, status, priority, attempt, max_attempts, last_error, worker_id, scheduled_for, started_at, completed_at, run_on, queue_message_id, created_at, updated_at
`

type CreateTaskWithPriorityParams struct {
	EntityID     string     `db:"entity_id" json:"entity_id"`
	TaskType     string     `db:"task_type" json:"task_type"`
	Priority     int32      `db:"priority" json:"priority"`
	MaxAttempts  int32      `db:"max_attempts" json:"max_attempts"`
	ScheduledFor time.Time  `db:"scheduled_for" json:"scheduled_for"`
	RunOn        *time.Time `db:"run_on" json:"run_on"`
}

func (q *Queries) CreateTaskWithPriority(ctx context.Context, arg *CreateTaskWithPriorityParams) (TaskQueueTask, error) {
	row := q.db.QueryRow(ctx, createTaskWithPriority,
		arg.EntityID,
		arg.TaskType,
		arg.Priority,
		arg.MaxAttempts,
		arg.ScheduledFor,
		arg.RunOn,
	)
	var i TaskQueueTask
	err := row.Scan(
		&i.TaskID,
		&i.EntityID,
		&i.TaskType,
		&i.Status,
		&i.Priority,
		&i.Attempt,
		&i.MaxAttempts,
		&i.LastError,
		&i.WorkerID,
		&i.ScheduledFor,
		&i.StartedAt,
		&i.CompletedAt,
		&i.RunOn,
		&i.QueueMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOldCompletedTasks = `-- name: DeleteOldCompletedTasks :execrows
DELETE FROM task_queue.task
WHERE status = 'completed'
    AND completed_at < $1
`

func (q *Queries) DeleteOldCompletedTasks(ctx context.Context, completedAt *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldCompletedTasks, completedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldFailedTasks = `-- name: DeleteOldFailedTasks :execrows
DELETE FROM task_queue.task
WHERE status IN ('failed', 'stopped')
    AND completed_at < $1
`

func (q *Queries) DeleteOldFailedTasks(ctx context.Context, completedAt *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldFailedTasks, completedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM task_queue.task
WHERE task_id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, taskID int64) error {
	_, err := q.db.Exec(ctx, deleteTask, taskID)
	return err
}

const getDailyProgress = `-- name: GetDailyProgress :one
SELECT
    COUNT(*) FILTER (WHERE status = 'completed' AND completed_at >= CURRENT_DATE) AS completed_today,
    COUNT(*) FILTER (WHERE status = 'processing') AS in_progress,
    COUNT(*) FILTER (WHERE status = 'pending' AND scheduled_for <= NOW()) AS ready_to_process,
    COUNT(*) FILTER (WHERE status = 'pending' AND scheduled_for > NOW()) AS scheduled_later,
    COUNT(*) FILTER (WHERE status IN ('failed', 'stopped') AND completed_at >= CURRENT_DATE) AS failed_today
FROM task_queue.task
`

type GetDailyProgressRow struct {
	CompletedToday int64 `db:"completed_today" json:"completed_today"`
	InProgress     int64 `db:"in_progress" json:"in_progress"`
	ReadyToProcess int64 `db:"ready_to_process" json:"ready_to_process"`
	ScheduledLater int64 `db:"scheduled_later" json:"scheduled_later"`
	FailedToday    int64 `db:"failed_today" json:"failed_today"`
}

func (q *Queries) GetDailyProgress(ctx context.Context) (GetDailyProgressRow, error) {
	row := q.db.QueryRow(ctx, getDailyProgress)
	var i GetDailyProgressRow
	err := row.Scan(
		&i.CompletedToday,
		&i.InProgress,
		&i.ReadyToProcess,
		&i.ScheduledLater,
		&i.FailedToday,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT
    task_id,
    entity_id,
    task_type,
    status,
    priority,
    attempt,
    max_attempts,
    last_error,
    worker_id,
    scheduled_for,
    started_at,
    completed_at,
    run_on,
    queue_message_id,
    created_at,
    updated_at
FROM task_queue.task
WHERE task_id = $1
`

func (q *Queries) GetTask(ctx context.Context, taskID int64) (TaskQueueTask, error) {
	row := q.db.QueryRow(ctx, getTask, taskID)
	var i TaskQueueTask
	err := row.Scan(
		&i.TaskID,
		&i.EntityID,
		&i.TaskType,
		&i.Status,
		&i.Priority,
		&i.Attempt,
		&i.MaxAttempts,
		&i.LastError,
		&i.WorkerID,
		&i.ScheduledFor,
		&i.StartedAt,
		&i.CompletedAt,
		&i.RunOn,
		&i.QueueMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByEntityAndDate = `-- name: GetTaskByEntityAndDate :one
SELECT
    task_id,
    entity_id,
    task_type,
    status,
    priority,
    attempt,
    max_attempts,
    last_error,
    worker_id,
    scheduled_for,
    started_at,
    completed_at,
    run_on,
    queue_message_id,
    created_at,
    updated_at
FROM task_queue.task
WHERE entity_id = $1
    AND task_type = $2
    AND run_on = $3
`

type GetTaskByEntityAndDateParams struct {
	EntityID string     `db:"entity_id" json:"entity_id"`
	TaskType string     `db:"task_type" json:"task_type"`
	RunOn    *time.Time `db:"run_on" json:"run_on"`
}

func (q *Queries) GetTaskByEntityAndDate(ctx context.Context, arg *GetTaskByEntityAndDateParams) (TaskQueueTask, error) {
	row := q.db.QueryRow(ctx, getTaskByEntityAndDate, arg.EntityID, arg.TaskType, arg.RunOn)
	var i TaskQueueTask
	err := row.Scan(
		&i.TaskID,
		&i.EntityID,
		&i.TaskType,
		&i.Status,
		&i.Priority,
		&i.Attempt,
		&i.MaxAttempts,
		&i.LastError,
		&i.WorkerID,
		&i.ScheduledFor,
		&i.StartedAt,
		&i.CompletedAt,
		&i.RunOn,
		&i.QueueMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskStatusSummary = `-- name: GetTaskStatusSummary :one
SELECT
    COUNT(*) FILTER (WHERE status = 'pending') AS pending,
    COUNT(*) FILTER (WHERE status = 'processing') AS processing,
    COUNT(*) FILTER (WHERE status = 'completed') AS completed,
    COUNT(*) FILTER (WHERE status = 'failed') AS failed,
    COUNT(*) FILTER (WHERE status = 'stopped') AS stopped,
    COUNT(*) AS total,
    COALESCE(ROUND(100.0 * COUNT(*) FILTER (WHERE status = 'completed') / NULLIF(COUNT(*), 0), 2), 0) AS success_rate_pct
FROM task_queue.task
`

type GetTaskStatusSummaryRow struct {
	Pending        int64          `db:"pending" json:"pending"`
	Processing     int64          `db:"processing" json:"processing"`
	Completed      int64          `db:"completed" json:"completed"`
	Failed         int64          `db:"failed" json:"failed"`
	Stopped        int64          `db:"stopped" json:"stopped"`
	Total          int64          `db:"total" json:"total"`
	SuccessRatePct pgtype.Numeric `db:"success_rate_pct" json:"success_rate_pct"`
}

func (q *Queries) GetTaskStatusSummary(ctx context.Context) (GetTaskStatusSummaryRow, error) {
	row := q.db.QueryRow(ctx, getTaskStatusSummary)
	var i GetTaskStatusSummaryRow
	err := row.Scan(
		&i.Pending,
		&i.Processing,
		&i.Completed,
		&i.Failed,
		&i.Stopped,
		&i.Total,
		&i.SuccessRatePct,
	)
	return i, err
}

const getTasksByRunDate = `-- name: GetTasksByRunDate :many
SELECT
    task_id,
    entity_id,
    task_type,
    status,
    priority,
    attempt,
    max_attempts,
    last_error,
    worker_id,
    scheduled_for,
    started_at,
    completed_at,
    run_on,
    queue_message_id,
    created_at,
    updated_at
FROM task_queue.task
WHERE run_on = $1
ORDER BY priority DESC, scheduled_for ASC
`

func (q *Queries) GetTasksByRunDate(ctx context.Context, runOn *time.Time) ([]TaskQueueTask, error) {
	rows, err := q.db.Query(ctx, getTasksByRunDate, runOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskQueueTask{}
	for rows.Next() {
		var i TaskQueueTask
		if err := rows.Scan(
			&i.TaskID,
			&i.EntityID,
			&i.TaskType,
			&i.Status,
			&i.Priority,
			&i.Attempt,
			&i.MaxAttempts,
			&i.LastError,
			&i.WorkerID,
			&i.ScheduledFor,
			&i.StartedAt,
			&i.CompletedAt,
			&i.RunOn,
			&i.QueueMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveWorkers = `-- name: ListActiveWorkers :many
SELECT
    worker_id,
    COUNT(*) AS active_tasks,
    MIN(started_at) AS oldest_task_started,
    EXTRACT(EPOCH FROM (NOW() - MIN(started_at)))::INT AS oldest_task_age_seconds
FROM task_queue.task
WHERE status = 'processing'
    AND worker_id IS NOT NULL
GROUP BY worker_id
ORDER BY oldest_task_started
`

type ListActiveWorkersRow struct {
	WorkerID             *string   `db:"worker_id" json:"worker_id"`
	ActiveTasks          int64     `db:"active_tasks" json:"active_tasks"`
	OldestTaskStarted    time.Time `db:"oldest_task_started" json:"oldest_task_started"`
	OldestTaskAgeSeconds int32     `db:"oldest_task_age_seconds" json:"oldest_task_age_seconds"`
}

func (q *Queries) ListActiveWorkers(ctx context.Context) ([]ListActiveWorkersRow, error) {
	rows, err := q.db.Query(ctx, listActiveWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveWorkersRow{}
	for rows.Next() {
		var i ListActiveWorkersRow
		if err := rows.Scan(
			&i.WorkerID,
			&i.ActiveTasks,
			&i.OldestTaskStarted,
			&i.OldestTaskAgeSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingTasks = `-- name: ListPendingTasks :many
SELECT
    task_id,
    entity_id,
    task_type,
    status,
    priority,
    attempt,
    max_attempts,
    last_error,
    worker_id,
    scheduled_for,
    started_at,
    completed_at,
    run_on,
    queue_message_id,
    created_at,
    updated_at
FROM task_queue.task
WHERE status = 'pending'
    AND scheduled_for <= NOW()
ORDER BY priority DESC, scheduled_for ASC
LIMIT $1
`

func (q *Queries) ListPendingTasks(ctx context.Context, limit int64) ([]TaskQueueTask, error) {
	rows, err := q.db.Query(ctx, listPendingTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskQueueTask{}
	for rows.Next() {
		var i TaskQueueTask
		if err := rows.Scan(
			&i.TaskID,
			&i.EntityID,
			&i.TaskType,
			&i.Status,
			&i.Priority,
			&i.Attempt,
			&i.MaxAttempts,
			&i.LastError,
			&i.WorkerID,
			&i.ScheduledFor,
			&i.StartedAt,
			&i.CompletedAt,
			&i.RunOn,
			&i.QueueMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentFailures = `-- name: ListRecentFailures :many
SELECT
    task_id,
    entity_id,
    task_type,
    status,
    priority,
    attempt,
    max_attempts,
    last_error,
    completed_at AS failed_at,
    created_at,
    updated_at
FROM task_queue.task
WHERE status IN ('failed', 'stopped')
ORDER BY completed_at DESC
LIMIT $1
`

type ListRecentFailuresRow struct {
	TaskID      int64      `db:"task_id" json:"task_id"`
	EntityID    string     `db:"entity_id" json:"entity_id"`
	TaskType    string     `db:"task_type" json:"task_type"`
	Status      string     `db:"status" json:"status"`
	Priority    int32      `db:"priority" json:"priority"`
	Attempt     int32      `db:"attempt" json:"attempt"`
	MaxAttempts int32      `db:"max_attempts" json:"max_attempts"`
	LastError   *string    `db:"last_error" json:"last_error"`
	FailedAt    *time.Time `db:"failed_at" json:"failed_at"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListRecentFailures(ctx context.Context, limit int64) ([]ListRecentFailuresRow, error) {
	rows, err := q.db.Query(ctx, listRecentFailures, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentFailuresRow{}
	for rows.Next() {
		var i ListRecentFailuresRow
		if err := rows.Scan(
			&i.TaskID,
			&i.EntityID,
			&i.TaskType,
			&i.Status,
			&i.Priority,
			&i.Attempt,
			&i.MaxAttempts,
			&i.LastError,
			&i.FailedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledTasks = `-- name: ListScheduledTasks :many
SELECT
    task_id,
    entity_id,
    task_type,
    status,
    priority,
    attempt,
    max_attempts,
    last_error,
    worker_id,
    scheduled_for,
    started_at,
    completed_at,
    run_on,
    queue_message_id,
    created_at,
    updated_at
FROM task_queue.task
WHERE status = 'pending'
    AND scheduled_for > NOW()
ORDER BY priority DESC, scheduled_for ASC
LIMIT $1 OFFSET $2
`

type ListScheduledTasksParams struct {
	Limit  int64 `db:"limit" json:"limit"`
	Offset int64 `db:"offset" json:"offset"`
}

func (q *Queries) ListScheduledTasks(ctx context.Context, arg *ListScheduledTasksParams) ([]TaskQueueTask, error) {
	rows, err := q.db.Query(ctx, listScheduledTasks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskQueueTask{}
	for rows.Next() {
		var i TaskQueueTask
		if err := rows.Scan(
			&i.TaskID,
			&i.EntityID,
			&i.TaskType,
			&i.Status,
			&i.Priority,
			&i.Attempt,
			&i.MaxAttempts,
			&i.LastError,
			&i.WorkerID,
			&i.ScheduledFor,
			&i.StartedAt,
			&i.CompletedAt,
			&i.RunOn,
			&i.QueueMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStuckTasks = `-- name: ListStuckTasks :many
SELECT
    task_id,
    entity_id,
    task_type,
    status,
    priority,
    attempt,
    max_attempts,
    last_error,
    worker_id,
    scheduled_for,
    started_at,
    completed_at,
    run_on,
    queue_message_id,
    created_at,
    updated_at,
    EXTRACT(EPOCH FROM (NOW() - started_at))::INT AS stuck_seconds
FROM task_queue.task
WHERE status = 'processing'
    AND updated_at < NOW() - INTERVAL '10 minutes'
ORDER BY started_at
`

type ListStuckTasksRow struct {
	TaskID         int64      `db:"task_id" json:"task_id"`
	EntityID       string     `db:"entity_id" json:"entity_id"`
	TaskType       string     `db:"task_type" json:"task_type"`
	Status         string     `db:"status" json:"status"`
	Priority       int32      `db:"priority" json:"priority"`
	Attempt        int32      `db:"attempt" json:"attempt"`
	MaxAttempts    int32      `db:"max_attempts" json:"max_attempts"`
	LastError      *string    `db:"last_error" json:"last_error"`
	WorkerID       *string    `db:"worker_id" json:"worker_id"`
	ScheduledFor   time.Time  `db:"scheduled_for" json:"scheduled_for"`
	StartedAt      *time.Time `db:"started_at" json:"started_at"`
	CompletedAt    *time.Time `db:"completed_at" json:"completed_at"`
	RunOn          *time.Time `db:"run_on" json:"run_on"`
	QueueMessageID *int64     `db:"queue_message_id" json:"queue_message_id"`
	CreatedAt      time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time  `db:"updated_at" json:"updated_at"`
	StuckSeconds   int32      `db:"stuck_seconds" json:"stuck_seconds"`
}

func (q *Queries) ListStuckTasks(ctx context.Context) ([]ListStuckTasksRow, error) {
	rows, err := q.db.Query(ctx, listStuckTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStuckTasksRow{}
	for rows.Next() {
		var i ListStuckTasksRow
		if err := rows.Scan(
			&i.TaskID,
			&i.EntityID,
			&i.TaskType,
			&i.Status,
			&i.Priority,
			&i.Attempt,
			&i.MaxAttempts,
			&i.LastError,
			&i.WorkerID,
			&i.ScheduledFor,
			&i.StartedAt,
			&i.CompletedAt,
			&i.RunOn,
			&i.QueueMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StuckSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT
    task_id,
    entity_id,
    task_type,
    status,
    priority,
    attempt,
    max_attempts,
    last_error,
    worker_id,
    scheduled_for,
    started_at,
    completed_at,
    run_on,
    queue_message_id,
    created_at,
    updated_at
FROM task_queue.task
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTasksParams struct {
	Limit  int64 `db:"limit" json:"limit"`
	Offset int64 `db:"offset" json:"offset"`
}

func (q *Queries) ListTasks(ctx context.Context, arg *ListTasksParams) ([]TaskQueueTask, error) {
	rows, err := q.db.Query(ctx, listTasks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskQueueTask{}
	for rows.Next() {
		var i TaskQueueTask
		if err := rows.Scan(
			&i.TaskID,
			&i.EntityID,
			&i.TaskType,
			&i.Status,
			&i.Priority,
			&i.Attempt,
			&i.MaxAttempts,
			&i.LastError,
			&i.WorkerID,
			&i.ScheduledFor,
			&i.StartedAt,
			&i.CompletedAt,
			&i.RunOn,
			&i.QueueMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByEntity = `-- name: ListTasksByEntity :many
SELECT
    task_id,
    entity_id,
    task_type,
    status,
    priority,
    attempt,
    max_attempts,
    last_error,
    worker_id,
    scheduled_for,
    started_at,
    completed_at,
    run_on,
    queue_message_id,
    created_at,
    updated_at
FROM task_queue.task
WHERE entity_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTasksByEntityParams struct {
	EntityID string `db:"entity_id" json:"entity_id"`
	Limit    int64  `db:"limit" json:"limit"`
	Offset   int64  `db:"offset" json:"offset"`
}

func (q *Queries) ListTasksByEntity(ctx context.Context, arg *ListTasksByEntityParams) ([]TaskQueueTask, error) {
	rows, err := q.db.Query(ctx, listTasksByEntity, arg.EntityID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskQueueTask{}
	for rows.Next() {
		var i TaskQueueTask
		if err := rows.Scan(
			&i.TaskID,
			&i.EntityID,
			&i.TaskType,
			&i.Status,
			&i.Priority,
			&i.Attempt,
			&i.MaxAttempts,
			&i.LastError,
			&i.WorkerID,
			&i.ScheduledFor,
			&i.StartedAt,
			&i.CompletedAt,
			&i.RunOn,
			&i.QueueMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatus = `-- name: ListTasksByStatus :many
SELECT
    task_id,
    entity_id,
    task_type,
    status,
    priority,
    attempt,
    max_attempts,
    last_error,
    worker_id,
    scheduled_for,
    started_at,
    completed_at,
    run_on,
    queue_message_id,
    created_at,
    updated_at
FROM task_queue.task
WHERE status = $1
ORDER BY priority DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListTasksByStatusParams struct {
	Status string `db:"status" json:"status"`
	Limit  int64  `db:"limit" json:"limit"`
	Offset int64  `db:"offset" json:"offset"`
}

func (q *Queries) ListTasksByStatus(ctx context.Context, arg *ListTasksByStatusParams) ([]TaskQueueTask, error) {
	rows, err := q.db.Query(ctx, listTasksByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskQueueTask{}
	for rows.Next() {
		var i TaskQueueTask
		if err := rows.Scan(
			&i.TaskID,
			&i.EntityID,
			&i.TaskType,
			&i.Status,
			&i.Priority,
			&i.Attempt,
			&i.MaxAttempts,
			&i.LastError,
			&i.WorkerID,
			&i.ScheduledFor,
			&i.StartedAt,
			&i.CompletedAt,
			&i.RunOn,
			&i.QueueMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByWorker = `-- name: ListTasksByWorker :many
SELECT
    task_id,
    entity_id,
    task_type,
    status,
    priority,
    attempt,
    max_attempts,
    last_error,
    worker_id,
    scheduled_for,
    started_at,
    completed_at,
    run_on,
    queue_message_id,
    created_at,
    updated_at
FROM task_queue.task
WHERE worker_id = $1
    AND status = 'processing'
ORDER BY started_at
`

func (q *Queries) ListTasksByWorker(ctx context.Context, workerID *string) ([]TaskQueueTask, error) {
	rows, err := q.db.Query(ctx, listTasksByWorker, workerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskQueueTask{}
	for rows.Next() {
		var i TaskQueueTask
		if err := rows.Scan(
			&i.TaskID,
			&i.EntityID,
			&i.TaskType,
			&i.Status,
			&i.Priority,
			&i.Attempt,
			&i.MaxAttempts,
			&i.LastError,
			&i.WorkerID,
			&i.ScheduledFor,
			&i.StartedAt,
			&i.CompletedAt,
			&i.RunOn,
			&i.QueueMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskPriority = `-- name: UpdateTaskPriority :exec
UPDATE task_queue.task
SET
    priority = $2,
    updated_at = NOW()
WHERE task_id = $1
`

type UpdateTaskPriorityParams struct {
	TaskID   int64 `db:"task_id" json:"task_id"`
	Priority int32 `db:"priority" json:"priority"`
}

func (q *Queries) UpdateTaskPriority(ctx context.Context, arg *UpdateTaskPriorityParams) error {
	_, err := q.db.Exec(ctx, updateTaskPriority, arg.TaskID, arg.Priority)
	return err
}

const updateTaskQueueMessageId = `-- name: UpdateTaskQueueMessageId :exec
UPDATE task_queue.task
SET
    queue_message_id = $2,
    updated_at = NOW()
WHERE task_id = $1
`

type UpdateTaskQueueMessageIdParams struct {
	TaskID         int64  `db:"task_id" json:"task_id"`
	QueueMessageID *int64 `db:"queue_message_id" json:"queue_message_id"`
}

func (q *Queries) UpdateTaskQueueMessageId(ctx context.Context, arg *UpdateTaskQueueMessageIdParams) error {
	_, err := q.db.Exec(ctx, updateTaskQueueMessageId, arg.TaskID, arg.QueueMessageID)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE task_queue.task
SET
    status = $2,
    updated_at = NOW()
WHERE task_id = $1
`

type UpdateTaskStatusParams struct {
	TaskID int64  `db:"task_id" json:"task_id"`
	Status string `db:"status" json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg *UpdateTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatus, arg.TaskID, arg.Status)
	return err
}

const updateTaskToCompleted = `-- name: UpdateTaskToCompleted :exec
UPDATE task_queue.task
SET
    status = 'completed',
    last_error = NULL,
    completed_at = NOW(),
    updated_at = NOW()
WHERE task_id = $1
`

func (q *Queries) UpdateTaskToCompleted(ctx context.Context, taskID int64) error {
	_, err := q.db.Exec(ctx, updateTaskToCompleted, taskID)
	return err
}

const updateTaskToFailed = `-- name: UpdateTaskToFailed :exec
UPDATE task_queue.task
SET
    status = 'failed',
    last_error = $2,
    completed_at = NOW(),
    updated_at = NOW()
WHERE task_id = $1
`

type UpdateTaskToFailedParams struct {
	TaskID    int64   `db:"task_id" json:"task_id"`
	LastError *string `db:"last_error" json:"last_error"`
}

func (q *Queries) UpdateTaskToFailed(ctx context.Context, arg *UpdateTaskToFailedParams) error {
	_, err := q.db.Exec(ctx, updateTaskToFailed, arg.TaskID, arg.LastError)
	return err
}

const updateTaskToPending = `-- name: UpdateTaskToPending :exec
UPDATE task_queue.task
SET
    status = 'pending',
    attempt = attempt + 1,
    worker_id = NULL,
    scheduled_for = $2,
    started_at = NULL,
    queue_message_id = NULL,
    updated_at = NOW()
WHERE task_id = $1
`

type UpdateTaskToPendingParams struct {
	TaskID       int64     `db:"task_id" json:"task_id"`
	ScheduledFor time.Time `db:"scheduled_for" json:"scheduled_for"`
}

func (q *Queries) UpdateTaskToPending(ctx context.Context, arg *UpdateTaskToPendingParams) error {
	_, err := q.db.Exec(ctx, updateTaskToPending, arg.TaskID, arg.ScheduledFor)
	return err
}

const updateTaskToPendingForRetry = `-- name: UpdateTaskToPendingForRetry :exec
UPDATE task_queue.task
SET
    status = 'pending',
    worker_id = NULL,
    scheduled_for = $2,
    started_at = NULL,
    queue_message_id = NULL,
    updated_at = NOW()
WHERE task_id = $1
`

type UpdateTaskToPendingForRetryParams struct {
	TaskID       int64     `db:"task_id" json:"task_id"`
	ScheduledFor time.Time `db:"scheduled_for" json:"scheduled_for"`
}

func (q *Queries) UpdateTaskToPendingForRetry(ctx context.Context, arg *UpdateTaskToPendingForRetryParams) error {
	_, err := q.db.Exec(ctx, updateTaskToPendingForRetry, arg.TaskID, arg.ScheduledFor)
	return err
}

const updateTaskToProcessing = `-- name: UpdateTaskToProcessing :exec
UPDATE task_queue.task
SET
    status = 'processing',
    attempt = attempt + 1,
    worker_id = $2,
    started_at = CASE WHEN started_at IS NULL THEN NOW() ELSE started_at END,
    updated_at = NOW()
WHERE task_id = $1
`

type UpdateTaskToProcessingParams struct {
	TaskID   int64   `db:"task_id" json:"task_id"`
	WorkerID *string `db:"worker_id" json:"worker_id"`
}

func (q *Queries) UpdateTaskToProcessing(ctx context.Context, arg *UpdateTaskToProcessingParams) error {
	_, err := q.db.Exec(ctx, updateTaskToProcessing, arg.TaskID, arg.WorkerID)
	return err
}

const upsertTaskForDate = `-- name: UpsertTaskForDate :one
INSERT INTO task_queue.task (
    entity_id,
    task_type,
    status,
    priority,
    attempt,
    max_attempts,
    scheduled_for,
    run_on
) VALUES (
    $1,
    $2,
    'pending',
    COALESCE($3, 0),
    0,
    $4,
    $5,
    $6
)
ON CONFLICT (entity_id, task_type, run_on)
WHERE run_on IS NOT NULL
DO UPDATE SET
    scheduled_for = COALESCE(task_queue.task.scheduled_for, EXCLUDED.scheduled_for),
    priority = GREATEST(task_queue.task.priority, EXCLUDED.priority),
    updated_at = NOW()
RETURNING task_id, entity_id, task_type, status, priority, attempt, max_attempts, last_error, worker_id, scheduled_for, started_at, completed_at, run_on, queue_message_id, created_at, updated_at
`

type UpsertTaskForDateParams struct {
	EntityID     string     `db:"entity_id" json:"entity_id"`
	TaskType     string     `db:"task_type" json:"task_type"`
	Column3      *int32     `db:"column_3" json:"column_3"`
	MaxAttempts  int32      `db:"max_attempts" json:"max_attempts"`
	ScheduledFor time.Time  `db:"scheduled_for" json:"scheduled_for"`
	RunOn        *time.Time `db:"run_on" json:"run_on"`
}

func (q *Queries) UpsertTaskForDate(ctx context.Context, arg *UpsertTaskForDateParams) (TaskQueueTask, error) {
	row := q.db.QueryRow(ctx, upsertTaskForDate,
		arg.EntityID,
		arg.TaskType,
		arg.Column3,
		arg.MaxAttempts,
		arg.ScheduledFor,
		arg.RunOn,
	)
	var i TaskQueueTask
	err := row.Scan(
		&i.TaskID,
		&i.EntityID,
		&i.TaskType,
		&i.Status,
		&i.Priority,
		&i.Attempt,
		&i.MaxAttempts,
		&i.LastError,
		&i.WorkerID,
		&i.ScheduledFor,
		&i.StartedAt,
		&i.CompletedAt,
		&i.RunOn,
		&i.QueueMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
