// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package db

import (
	"context"
	"time"
)

const deleteShortcutToken = `-- name: DeleteShortcutToken :exec
DELETE FROM public.shortcut_tokens
WHERE shortcut_token_cuid = $1
`

func (q *Queries) DeleteShortcutToken(ctx context.Context, shortcutTokenCuid string) error {
	_, err := q.db.Exec(ctx, deleteShortcutToken, shortcutTokenCuid)
	return err
}

const getAllValidShortcutTokens = `-- name: GetAllValidShortcutTokens :many
SELECT shortcut_token_id, shortcut_token_cuid, shortcut_token_token, shortcut_token_loaded, shortcut_token_created_at, shortcut_token_updated_at, shortcut_token_expires_at FROM public.shortcut_tokens
ORDER BY shortcut_token_created_at DESC
`

func (q *Queries) GetAllValidShortcutTokens(ctx context.Context) ([]ShortcutToken, error) {
	rows, err := q.db.Query(ctx, getAllValidShortcutTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShortcutToken{}
	for rows.Next() {
		var i ShortcutToken
		if err := rows.Scan(
			&i.ShortcutTokenID,
			&i.ShortcutTokenCuid,
			&i.ShortcutTokenToken,
			&i.ShortcutTokenLoaded,
			&i.ShortcutTokenCreatedAt,
			&i.ShortcutTokenUpdatedAt,
			&i.ShortcutTokenExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidShortcutToken = `-- name: GetValidShortcutToken :one
SELECT shortcut_token_id, shortcut_token_cuid, shortcut_token_token, shortcut_token_loaded, shortcut_token_created_at, shortcut_token_updated_at, shortcut_token_expires_at FROM public.shortcut_tokens
ORDER BY shortcut_token_created_at DESC
LIMIT 1
`

func (q *Queries) GetValidShortcutToken(ctx context.Context) (ShortcutToken, error) {
	row := q.db.QueryRow(ctx, getValidShortcutToken)
	var i ShortcutToken
	err := row.Scan(
		&i.ShortcutTokenID,
		&i.ShortcutTokenCuid,
		&i.ShortcutTokenToken,
		&i.ShortcutTokenLoaded,
		&i.ShortcutTokenCreatedAt,
		&i.ShortcutTokenUpdatedAt,
		&i.ShortcutTokenExpiresAt,
	)
	return i, err
}

const insertShortcutToken = `-- name: InsertShortcutToken :one
INSERT INTO public.shortcut_tokens (
    shortcut_token_cuid,
    shortcut_token_token,
    shortcut_token_loaded,
    shortcut_token_expires_at
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (shortcut_token_cuid) DO UPDATE SET
    shortcut_token_token = EXCLUDED.shortcut_token_token,
    shortcut_token_loaded = EXCLUDED.shortcut_token_loaded,
    shortcut_token_expires_at = EXCLUDED.shortcut_token_expires_at,
    shortcut_token_updated_at = NOW()
RETURNING shortcut_token_id, shortcut_token_cuid, shortcut_token_token, shortcut_token_loaded, shortcut_token_created_at, shortcut_token_updated_at, shortcut_token_expires_at
`

type InsertShortcutTokenParams struct {
	ShortcutTokenCuid      string    `json:"shortcut_token_cuid"`
	ShortcutTokenToken     string    `json:"shortcut_token_token"`
	ShortcutTokenLoaded    string    `json:"shortcut_token_loaded"`
	ShortcutTokenExpiresAt time.Time `json:"shortcut_token_expires_at"`
}

func (q *Queries) InsertShortcutToken(ctx context.Context, arg InsertShortcutTokenParams) (ShortcutToken, error) {
	row := q.db.QueryRow(ctx, insertShortcutToken,
		arg.ShortcutTokenCuid,
		arg.ShortcutTokenToken,
		arg.ShortcutTokenLoaded,
		arg.ShortcutTokenExpiresAt,
	)
	var i ShortcutToken
	err := row.Scan(
		&i.ShortcutTokenID,
		&i.ShortcutTokenCuid,
		&i.ShortcutTokenToken,
		&i.ShortcutTokenLoaded,
		&i.ShortcutTokenCreatedAt,
		&i.ShortcutTokenUpdatedAt,
		&i.ShortcutTokenExpiresAt,
	)
	return i, err
}
