// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction_matcher.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const applyTransactionMatchLink = `-- name: ApplyTransactionMatchLink :execrows
WITH updated_source AS (
    UPDATE public.property_source_offerings
    SET prices_transaction_id = $1::uuid,
        sale_listing_prices_match_status = 'auto_linked',
        sale_listing_prices_match_run_id = $4::uuid,
        sale_listing_updated_at = now()
    WHERE sale_listing_id = $5::uuid
        AND (prices_transaction_id IS NULL OR prices_transaction_id = $1::uuid)
        AND NOT EXISTS (
            SELECT 1
            FROM public.price_links existing
            WHERE existing.prices_transaction_id = $1::uuid
                AND existing.link_status <> 'rejected'
        )
    RETURNING sale_listing_id, sale_listing_created_at, sale_listing_updated_at
)
INSERT INTO public.price_links (
    target_type,
    target_id,
    prices_transaction_id,
    link_status,
    link_method,
    link_score,
    link_reasons,
    created_at,
    updated_at
)
SELECT
    'source_listing',
    sale_listing_id,
    $1::uuid,
    'confirmed',
    'sync_auto',
    $2::int4,
    $3::jsonb,
    sale_listing_created_at,
    sale_listing_updated_at
FROM updated_source
WHERE NOT EXISTS (
        SELECT 1
        FROM public.price_links existing
        WHERE existing.prices_transaction_id = $1::uuid
            AND existing.link_status <> 'rejected'
    )
ON CONFLICT (target_type, target_id, prices_transaction_id) DO UPDATE SET
    link_status = EXCLUDED.link_status,
    link_method = EXCLUDED.link_method,
    link_score = EXCLUDED.link_score,
    link_reasons = EXCLUDED.link_reasons,
    updated_at = now()
`

type ApplyTransactionMatchLinkParams struct {
	TransactionID uuid.UUID       `json:"transaction_id"`
	Score         int32           `json:"score"`
	Reasons       json.RawMessage `json:"reasons"`
	RunID         uuid.UUID       `json:"run_id"`
	ListingID     uuid.UUID       `json:"listing_id"`
}

func (q *Queries) ApplyTransactionMatchLink(ctx context.Context, arg ApplyTransactionMatchLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyTransactionMatchLink,
		arg.TransactionID,
		arg.Score,
		arg.Reasons,
		arg.RunID,
		arg.ListingID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createTransactionMatchRun = `-- name: CreateTransactionMatchRun :one
INSERT INTO public.sale_listing_prices_transaction_match_runs (
    sale_listing_prices_transaction_match_run_mode,
    sale_listing_prices_transaction_match_score_threshold,
    sale_listing_prices_transaction_match_competitor_margin
)
VALUES ($1::text, $2::int4, $3::int4)
RETURNING sale_listing_prices_transaction_match_run_id
`

type CreateTransactionMatchRunParams struct {
	Mode             *string `json:"mode"`
	ScoreThreshold   *int32  `json:"score_threshold"`
	CompetitorMargin *int32  `json:"competitor_margin"`
}

func (q *Queries) CreateTransactionMatchRun(ctx context.Context, arg CreateTransactionMatchRunParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTransactionMatchRun, arg.Mode, arg.ScoreThreshold, arg.CompetitorMargin)
	var sale_listing_prices_transaction_match_run_id uuid.UUID
	err := row.Scan(&sale_listing_prices_transaction_match_run_id)
	return sale_listing_prices_transaction_match_run_id, err
}

const finishTransactionMatchRun = `-- name: FinishTransactionMatchRun :exec
UPDATE public.sale_listing_prices_transaction_match_runs
SET sale_listing_prices_transaction_match_candidates_count = $1::int4,
    sale_listing_prices_transaction_match_auto_linked_count = $2::int4,
    sale_listing_prices_transaction_match_ambiguous_count = $3::int4,
    sale_listing_prices_transaction_match_finished_at = now()
WHERE sale_listing_prices_transaction_match_run_id = $4::uuid
`

type FinishTransactionMatchRunParams struct {
	Candidates *int32     `json:"candidates"`
	AutoLinked *int32     `json:"auto_linked"`
	Ambiguous  *int32     `json:"ambiguous"`
	RunID      *uuid.UUID `json:"run_id"`
}

func (q *Queries) FinishTransactionMatchRun(ctx context.Context, arg FinishTransactionMatchRunParams) error {
	_, err := q.db.Exec(ctx, finishTransactionMatchRun,
		arg.Candidates,
		arg.AutoLinked,
		arg.Ambiguous,
		arg.RunID,
	)
	return err
}

const insertTransactionMatchCandidate = `-- name: InsertTransactionMatchCandidate :exec
INSERT INTO public.sale_listing_prices_transaction_match_candidates (
    sale_listing_prices_transaction_match_run_id,
    sale_listing_id,
    prices_transaction_id,
    sale_listing_prices_transaction_match_score,
    sale_listing_prices_transaction_match_confidence,
    sale_listing_prices_transaction_match_reasons,
    sale_listing_prices_transaction_match_price_delta_percent
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4::int4,
    $5::text,
    $6::jsonb,
    $7::double precision
)
`

type InsertTransactionMatchCandidateParams struct {
	RunID             *uuid.UUID      `json:"run_id"`
	ListingID         *uuid.UUID      `json:"listing_id"`
	TransactionID     *uuid.UUID      `json:"transaction_id"`
	Score             *int32          `json:"score"`
	Confidence        *string         `json:"confidence"`
	Reasons           json.RawMessage `json:"reasons"`
	PriceDeltaPercent *float64        `json:"price_delta_percent"`
}

func (q *Queries) InsertTransactionMatchCandidate(ctx context.Context, arg InsertTransactionMatchCandidateParams) error {
	_, err := q.db.Exec(ctx, insertTransactionMatchCandidate,
		arg.RunID,
		arg.ListingID,
		arg.TransactionID,
		arg.Score,
		arg.Confidence,
		arg.Reasons,
		arg.PriceDeltaPercent,
	)
	return err
}

const loadTransactionMatchCandidateRows = `-- name: LoadTransactionMatchCandidateRows :many
SELECT
    sl.sale_listing_id,
    pt.prices_transaction_id,
    COALESCE(sl.sale_listing_room_layout, '')::text AS listing_layout,
    COALESCE(pt.prices_transaction_description, '')::text AS transaction_layout,
    sl.sale_listing_area_value,
    pt.prices_transaction_area,
    COALESCE(sl.sale_listing_property_type_code, '')::text AS listing_type,
    COALESCE(pt.prices_transaction_type, '')::text AS transaction_type,
    sl.sale_listing_build_year,
    pt.prices_transaction_build_year,
    sl.sale_listing_floor_level,
    sl.sale_listing_total_floors,
    COALESCE(pt.prices_transaction_floor, '')::text AS transaction_floor,
    sl.sale_listing_elevator,
    pt.prices_transaction_elevator,
    COALESCE(sl.sale_listing_condition, '')::text AS listing_condition,
    COALESCE(pt.prices_transaction_condition, '')::text AS transaction_condition,
    sl.sale_listing_plot_owned,
    pt.prices_transaction_plot_owned,
    COALESCE(sl.sale_listing_energy_efficiency_match_code, '')::text AS listing_energy,
    COALESCE(pt.prices_transaction_energy_class, '')::text AS transaction_energy,
    sl.sale_listing_asking_price,
    pt.prices_transaction_price,
    sl.sale_listing_first_seen_at,
    sl.sale_listing_last_seen_at,
    sl.sale_listing_created_at,
    sl.sale_listing_updated_at,
    pt.prices_transaction_created_at
FROM public.property_source_offerings sl
JOIN origin.prices_transactions pt ON true
JOIN origin.prices_neighborhoods pn ON pn.prices_neighborhood_id = pt.prices_neighborhood_id
LEFT JOIN origin.prices_postal_codes ppc ON ppc.prices_postal_code_id = pn.prices_postal_code_id
LEFT JOIN origin.postal_postal_codes postal ON postal.postal_postal_code_id = pn.prices_neighborhood_postal_postal_code_id
WHERE sl.sale_listing_source_kind = 'ad'
    AND ($1::uuid IS NULL OR sl.sale_listing_id = $1::uuid)
    AND sl.sale_listing_postal_norm = NULLIF(regexp_replace(trim(COALESCE(COALESCE(ppc.prices_postal_code_code, postal.postal_postal_code_code), '')), '[^0-9]+', '', 'g'), '')
    AND sl.sale_listing_area_value IS NOT NULL
    AND sl.sale_listing_area_value = pt.prices_transaction_area
    AND NOT EXISTS (
        SELECT 1
        FROM public.price_links source_link
        WHERE source_link.target_type = 'source_listing'
            AND source_link.target_id = sl.sale_listing_id
            AND source_link.link_status <> 'rejected'
    )
    AND NOT EXISTS (
        SELECT 1
        FROM public.price_links linked
        WHERE linked.prices_transaction_id = pt.prices_transaction_id
            AND linked.link_status <> 'rejected'
    )
`

type LoadTransactionMatchCandidateRowsRow struct {
	SaleListingID              uuid.UUID  `json:"sale_listing_id"`
	PricesTransactionID        uuid.UUID  `json:"prices_transaction_id"`
	ListingLayout              *string    `json:"listing_layout"`
	TransactionLayout          *string    `json:"transaction_layout"`
	SaleListingAreaValue       *float64   `json:"sale_listing_area_value"`
	PricesTransactionArea      float64    `json:"prices_transaction_area"`
	ListingType                *string    `json:"listing_type"`
	TransactionType            *string    `json:"transaction_type"`
	SaleListingBuildYear       *int32     `json:"sale_listing_build_year"`
	PricesTransactionBuildYear int32      `json:"prices_transaction_build_year"`
	SaleListingFloorLevel      *int32     `json:"sale_listing_floor_level"`
	SaleListingTotalFloors     *int32     `json:"sale_listing_total_floors"`
	TransactionFloor           *string    `json:"transaction_floor"`
	SaleListingElevator        *bool      `json:"sale_listing_elevator"`
	PricesTransactionElevator  bool       `json:"prices_transaction_elevator"`
	ListingCondition           *string    `json:"listing_condition"`
	TransactionCondition       *string    `json:"transaction_condition"`
	SaleListingPlotOwned       *bool      `json:"sale_listing_plot_owned"`
	PricesTransactionPlotOwned *bool      `json:"prices_transaction_plot_owned"`
	ListingEnergy              *string    `json:"listing_energy"`
	TransactionEnergy          *string    `json:"transaction_energy"`
	SaleListingAskingPrice     *int64     `json:"sale_listing_asking_price"`
	PricesTransactionPrice     int32      `json:"prices_transaction_price"`
	SaleListingFirstSeenAt     *time.Time `json:"sale_listing_first_seen_at"`
	SaleListingLastSeenAt      *time.Time `json:"sale_listing_last_seen_at"`
	SaleListingCreatedAt       time.Time  `json:"sale_listing_created_at"`
	SaleListingUpdatedAt       time.Time  `json:"sale_listing_updated_at"`
	PricesTransactionCreatedAt time.Time  `json:"prices_transaction_created_at"`
}

func (q *Queries) LoadTransactionMatchCandidateRows(ctx context.Context, targetListingID *uuid.UUID) ([]LoadTransactionMatchCandidateRowsRow, error) {
	rows, err := q.db.Query(ctx, loadTransactionMatchCandidateRows, targetListingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadTransactionMatchCandidateRowsRow{}
	for rows.Next() {
		var i LoadTransactionMatchCandidateRowsRow
		if err := rows.Scan(
			&i.SaleListingID,
			&i.PricesTransactionID,
			&i.ListingLayout,
			&i.TransactionLayout,
			&i.SaleListingAreaValue,
			&i.PricesTransactionArea,
			&i.ListingType,
			&i.TransactionType,
			&i.SaleListingBuildYear,
			&i.PricesTransactionBuildYear,
			&i.SaleListingFloorLevel,
			&i.SaleListingTotalFloors,
			&i.TransactionFloor,
			&i.SaleListingElevator,
			&i.PricesTransactionElevator,
			&i.ListingCondition,
			&i.TransactionCondition,
			&i.SaleListingPlotOwned,
			&i.PricesTransactionPlotOwned,
			&i.ListingEnergy,
			&i.TransactionEnergy,
			&i.SaleListingAskingPrice,
			&i.PricesTransactionPrice,
			&i.SaleListingFirstSeenAt,
			&i.SaleListingLastSeenAt,
			&i.SaleListingCreatedAt,
			&i.SaleListingUpdatedAt,
			&i.PricesTransactionCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAmbiguousTransactionMatches = `-- name: MarkAmbiguousTransactionMatches :execrows
UPDATE public.sale_listing_prices_transaction_match_candidates
SET sale_listing_prices_transaction_match_status = 'ambiguous'
WHERE sale_listing_prices_transaction_match_run_id = $1::uuid
    AND sale_listing_prices_transaction_match_status = 'candidate'
    AND sale_listing_prices_transaction_match_score >= $2::int4
`

type MarkAmbiguousTransactionMatchesParams struct {
	RunID     *uuid.UUID `json:"run_id"`
	Threshold *int32     `json:"threshold"`
}

func (q *Queries) MarkAmbiguousTransactionMatches(ctx context.Context, arg MarkAmbiguousTransactionMatchesParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAmbiguousTransactionMatches, arg.RunID, arg.Threshold)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markTransactionMatchLinked = `-- name: MarkTransactionMatchLinked :exec
UPDATE public.sale_listing_prices_transaction_match_candidates
SET sale_listing_prices_transaction_match_status = 'auto_linked'
WHERE sale_listing_prices_transaction_match_run_id = $1::uuid
    AND sale_listing_id = $2::uuid
    AND prices_transaction_id = $3::uuid
`

type MarkTransactionMatchLinkedParams struct {
	RunID         *uuid.UUID `json:"run_id"`
	ListingID     *uuid.UUID `json:"listing_id"`
	TransactionID *uuid.UUID `json:"transaction_id"`
}

func (q *Queries) MarkTransactionMatchLinked(ctx context.Context, arg MarkTransactionMatchLinkedParams) error {
	_, err := q.db.Exec(ctx, markTransactionMatchLinked, arg.RunID, arg.ListingID, arg.TransactionID)
	return err
}

const syncSourceListingTransactionMatchState = `-- name: SyncSourceListingTransactionMatchState :exec
UPDATE origin.source_listings src
SET normalized_at = sl.sale_listing_updated_at,
    updated_at = sl.sale_listing_updated_at
FROM public.property_source_offerings sl
WHERE sl.sale_listing_id = $1::uuid
    AND src.source_listing_id = sl.sale_listing_id
`

func (q *Queries) SyncSourceListingTransactionMatchState(ctx context.Context, listingID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, syncSourceListingTransactionMatchState, listingID)
	return err
}
