// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO auth.users DEFAULT VALUES
RETURNING user_id, user_created_at, user_updated_at, user_deleted_at
`

func (q *Queries) CreateUser(ctx context.Context) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createUser)
	var i AuthUser
	err := row.Scan(
		&i.UserID,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
		&i.UserDeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE auth.users
SET user_deleted_at = now(), user_updated_at = now()
WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, userID)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, user_created_at, user_updated_at, user_deleted_at FROM auth.users
WHERE user_id = $1 AND user_deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, userID pgtype.UUID) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i AuthUser
	err := row.Scan(
		&i.UserID,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
		&i.UserDeletedAt,
	)
	return i, err
}
