// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webauthn_challenges.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const consumeWebauthnChallenge = `-- name: ConsumeWebauthnChallenge :one
update auth.auth_webauthn_challenges
set auth_webauthn_challenge_consumed_at = now()
where auth_webauthn_challenge_uuid = $1
  and auth_webauthn_challenge_flow = $2
  and auth_webauthn_challenge_consumed_at is null
  and auth_webauthn_challenge_expires_at > now()
returning
  auth_webauthn_challenge_uuid,
  auth_webauthn_challenge_flow,
  auth_webauthn_challenge_session,
  auth_webauthn_challenge_expires_at,
  auth_webauthn_challenge_user_handle,
  auth_webauthn_challenge_user_display_name,
  auth_webauthn_challenge_verified_email,
  auth_webauthn_challenge_device_id,
  auth_webauthn_challenge_consumed_at,
  auth_webauthn_challenge_created_at,
  (
    select user_uuid
    from auth.users u
    where u.user_id = auth_webauthn_challenges.user_id
  ) as user_uuid
`

type ConsumeWebauthnChallengeParams struct {
	AuthWebauthnChallengeUuid *uuid.UUID `json:"auth_webauthn_challenge_uuid"`
	AuthWebauthnChallengeFlow *string    `json:"auth_webauthn_challenge_flow"`
}

type ConsumeWebauthnChallengeRow struct {
	AuthWebauthnChallengeUuid            uuid.UUID       `json:"auth_webauthn_challenge_uuid"`
	AuthWebauthnChallengeFlow            string          `json:"auth_webauthn_challenge_flow"`
	AuthWebauthnChallengeSession         json.RawMessage `json:"auth_webauthn_challenge_session"`
	AuthWebauthnChallengeExpiresAt       time.Time       `json:"auth_webauthn_challenge_expires_at"`
	AuthWebauthnChallengeUserHandle      []byte          `json:"auth_webauthn_challenge_user_handle"`
	AuthWebauthnChallengeUserDisplayName *string         `json:"auth_webauthn_challenge_user_display_name"`
	AuthWebauthnChallengeVerifiedEmail   *string         `json:"auth_webauthn_challenge_verified_email"`
	AuthWebauthnChallengeDeviceID        *uuid.UUID      `json:"auth_webauthn_challenge_device_id"`
	AuthWebauthnChallengeConsumedAt      *time.Time      `json:"auth_webauthn_challenge_consumed_at"`
	AuthWebauthnChallengeCreatedAt       time.Time       `json:"auth_webauthn_challenge_created_at"`
	UserUuid                             *uuid.UUID      `json:"user_uuid"`
}

func (q *Queries) ConsumeWebauthnChallenge(ctx context.Context, arg ConsumeWebauthnChallengeParams) (ConsumeWebauthnChallengeRow, error) {
	row := q.db.QueryRow(ctx, consumeWebauthnChallenge, arg.AuthWebauthnChallengeUuid, arg.AuthWebauthnChallengeFlow)
	var i ConsumeWebauthnChallengeRow
	err := row.Scan(
		&i.AuthWebauthnChallengeUuid,
		&i.AuthWebauthnChallengeFlow,
		&i.AuthWebauthnChallengeSession,
		&i.AuthWebauthnChallengeExpiresAt,
		&i.AuthWebauthnChallengeUserHandle,
		&i.AuthWebauthnChallengeUserDisplayName,
		&i.AuthWebauthnChallengeVerifiedEmail,
		&i.AuthWebauthnChallengeDeviceID,
		&i.AuthWebauthnChallengeConsumedAt,
		&i.AuthWebauthnChallengeCreatedAt,
		&i.UserUuid,
	)
	return i, err
}

const createWebauthnChallenge = `-- name: CreateWebauthnChallenge :one
insert into auth.auth_webauthn_challenges (
  auth_webauthn_challenge_flow,
  auth_webauthn_challenge_session,
  auth_webauthn_challenge_expires_at,
  auth_webauthn_challenge_user_handle,
  auth_webauthn_challenge_user_display_name,
  auth_webauthn_challenge_verified_email,
  auth_webauthn_challenge_device_id,
  user_id
)
values (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  (
    select user_id
    from auth.users u
    where u.user_uuid = $8
  )
)
returning
  auth_webauthn_challenge_uuid,
  auth_webauthn_challenge_flow,
  auth_webauthn_challenge_session,
  auth_webauthn_challenge_expires_at,
  auth_webauthn_challenge_user_handle,
  auth_webauthn_challenge_user_display_name,
  auth_webauthn_challenge_verified_email,
  auth_webauthn_challenge_device_id,
  auth_webauthn_challenge_consumed_at,
  auth_webauthn_challenge_created_at,
  (
    select user_uuid
    from auth.users u
    where u.user_id = auth_webauthn_challenges.user_id
  ) as user_uuid
`

type CreateWebauthnChallengeParams struct {
	AuthWebauthnChallengeFlow            *string         `json:"auth_webauthn_challenge_flow"`
	AuthWebauthnChallengeSession         json.RawMessage `json:"auth_webauthn_challenge_session"`
	AuthWebauthnChallengeExpiresAt       *time.Time      `json:"auth_webauthn_challenge_expires_at"`
	AuthWebauthnChallengeUserHandle      []byte          `json:"auth_webauthn_challenge_user_handle"`
	AuthWebauthnChallengeUserDisplayName *string         `json:"auth_webauthn_challenge_user_display_name"`
	AuthWebauthnChallengeVerifiedEmail   *string         `json:"auth_webauthn_challenge_verified_email"`
	AuthWebauthnChallengeDeviceID        *uuid.UUID      `json:"auth_webauthn_challenge_device_id"`
	UserUuid                             *uuid.UUID      `json:"user_uuid"`
}

type CreateWebauthnChallengeRow struct {
	AuthWebauthnChallengeUuid            uuid.UUID       `json:"auth_webauthn_challenge_uuid"`
	AuthWebauthnChallengeFlow            string          `json:"auth_webauthn_challenge_flow"`
	AuthWebauthnChallengeSession         json.RawMessage `json:"auth_webauthn_challenge_session"`
	AuthWebauthnChallengeExpiresAt       time.Time       `json:"auth_webauthn_challenge_expires_at"`
	AuthWebauthnChallengeUserHandle      []byte          `json:"auth_webauthn_challenge_user_handle"`
	AuthWebauthnChallengeUserDisplayName *string         `json:"auth_webauthn_challenge_user_display_name"`
	AuthWebauthnChallengeVerifiedEmail   *string         `json:"auth_webauthn_challenge_verified_email"`
	AuthWebauthnChallengeDeviceID        *uuid.UUID      `json:"auth_webauthn_challenge_device_id"`
	AuthWebauthnChallengeConsumedAt      *time.Time      `json:"auth_webauthn_challenge_consumed_at"`
	AuthWebauthnChallengeCreatedAt       time.Time       `json:"auth_webauthn_challenge_created_at"`
	UserUuid                             *uuid.UUID      `json:"user_uuid"`
}

func (q *Queries) CreateWebauthnChallenge(ctx context.Context, arg CreateWebauthnChallengeParams) (CreateWebauthnChallengeRow, error) {
	row := q.db.QueryRow(ctx, createWebauthnChallenge,
		arg.AuthWebauthnChallengeFlow,
		arg.AuthWebauthnChallengeSession,
		arg.AuthWebauthnChallengeExpiresAt,
		arg.AuthWebauthnChallengeUserHandle,
		arg.AuthWebauthnChallengeUserDisplayName,
		arg.AuthWebauthnChallengeVerifiedEmail,
		arg.AuthWebauthnChallengeDeviceID,
		arg.UserUuid,
	)
	var i CreateWebauthnChallengeRow
	err := row.Scan(
		&i.AuthWebauthnChallengeUuid,
		&i.AuthWebauthnChallengeFlow,
		&i.AuthWebauthnChallengeSession,
		&i.AuthWebauthnChallengeExpiresAt,
		&i.AuthWebauthnChallengeUserHandle,
		&i.AuthWebauthnChallengeUserDisplayName,
		&i.AuthWebauthnChallengeVerifiedEmail,
		&i.AuthWebauthnChallengeDeviceID,
		&i.AuthWebauthnChallengeConsumedAt,
		&i.AuthWebauthnChallengeCreatedAt,
		&i.UserUuid,
	)
	return i, err
}
