// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPricesTransactions = `-- name: ListPricesTransactions :many
SELECT
    ht.prices_transactions_id,
    ht.prices_transactions_neighborhood,
    ht.prices_transactions_description,
    ht.prices_transactions_type,
    ht.prices_transactions_area,
    ht.prices_transactions_price,
    ht.prices_transactions_price_per_square_meter,
    ht.prices_transactions_build_year,
    ht.prices_transactions_floor,
    ht.prices_transactions_elevator,
    ht.prices_transactions_condition,
    ht.prices_transactions_plot,
    ht.prices_transactions_energy_class,
    ht.prices_transactions_first_seen_at,
    ht.prices_transactions_last_seen_at,
    ht.prices_transactions_category,
    ht.prices_neighborhoods_postal_code,
    hn.prices_neighborhoods_name
FROM public.prices_transactions AS ht
NATURAL JOIN public.prices_neighborhoods AS hn
ORDER BY ht.prices_transactions_first_seen_at
`

type ListPricesTransactionsRow struct {
	PricesTransactionsID                  pgtype.UUID        `db:"prices_transactions_id" json:"prices_transactions_id"`
	PricesTransactionsNeighborhood        string             `db:"prices_transactions_neighborhood" json:"prices_transactions_neighborhood"`
	PricesTransactionsDescription         string             `db:"prices_transactions_description" json:"prices_transactions_description"`
	PricesTransactionsType                string             `db:"prices_transactions_type" json:"prices_transactions_type"`
	PricesTransactionsArea                float64            `db:"prices_transactions_area" json:"prices_transactions_area"`
	PricesTransactionsPrice               int32              `db:"prices_transactions_price" json:"prices_transactions_price"`
	PricesTransactionsPricePerSquareMeter int32              `db:"prices_transactions_price_per_square_meter" json:"prices_transactions_price_per_square_meter"`
	PricesTransactionsBuildYear           int32              `db:"prices_transactions_build_year" json:"prices_transactions_build_year"`
	PricesTransactionsFloor               string             `db:"prices_transactions_floor" json:"prices_transactions_floor"`
	PricesTransactionsElevator            string             `db:"prices_transactions_elevator" json:"prices_transactions_elevator"`
	PricesTransactionsCondition           string             `db:"prices_transactions_condition" json:"prices_transactions_condition"`
	PricesTransactionsPlot                string             `db:"prices_transactions_plot" json:"prices_transactions_plot"`
	PricesTransactionsEnergyClass         pgtype.Text        `db:"prices_transactions_energy_class" json:"prices_transactions_energy_class"`
	PricesTransactionsFirstSeenAt         pgtype.Timestamptz `db:"prices_transactions_first_seen_at" json:"prices_transactions_first_seen_at"`
	PricesTransactionsLastSeenAt          pgtype.Timestamptz `db:"prices_transactions_last_seen_at" json:"prices_transactions_last_seen_at"`
	PricesTransactionsCategory            string             `db:"prices_transactions_category" json:"prices_transactions_category"`
	PricesNeighborhoodsPostalCode         string             `db:"prices_neighborhoods_postal_code" json:"prices_neighborhoods_postal_code"`
	PricesNeighborhoodsName               string             `db:"prices_neighborhoods_name" json:"prices_neighborhoods_name"`
}

func (q *Queries) ListPricesTransactions(ctx context.Context) ([]ListPricesTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listPricesTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPricesTransactionsRow{}
	for rows.Next() {
		var i ListPricesTransactionsRow
		if err := rows.Scan(
			&i.PricesTransactionsID,
			&i.PricesTransactionsNeighborhood,
			&i.PricesTransactionsDescription,
			&i.PricesTransactionsType,
			&i.PricesTransactionsArea,
			&i.PricesTransactionsPrice,
			&i.PricesTransactionsPricePerSquareMeter,
			&i.PricesTransactionsBuildYear,
			&i.PricesTransactionsFloor,
			&i.PricesTransactionsElevator,
			&i.PricesTransactionsCondition,
			&i.PricesTransactionsPlot,
			&i.PricesTransactionsEnergyClass,
			&i.PricesTransactionsFirstSeenAt,
			&i.PricesTransactionsLastSeenAt,
			&i.PricesTransactionsCategory,
			&i.PricesNeighborhoodsPostalCode,
			&i.PricesNeighborhoodsName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
