// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnifiedEntities = `-- name: CountUnifiedEntities :one
WITH unified AS (
    SELECT
        'shortcut'::text AS source,
        'ad'::text AS kind,
        COALESCE(sa.shortcut_ad_data #>> '{address,city,name}', sa.shortcut_ad_data #>> '{address,city}') AS city,
        COALESCE(sa.shortcut_ad_data #>> '{address,zipCode,value}', sa.shortcut_ad_data #>> '{address,zipCode,name}') AS postal,
        COALESCE(
            NULLIF(regexp_replace(sa.shortcut_ad_data #>> '{priceData,priceSell}', '[^0-9\.-]', '', 'g'), '')::numeric::bigint,
            NULLIF(regexp_replace(sa.shortcut_ad_data #>> '{priceData,price}', '[^0-9\.-]', '', 'g'), '')::numeric::bigint
        ) AS price,
        COALESCE(NULLIF(sa.shortcut_ad_data #>> '{adData,size}', '')::float8, 0::float8) AS area,
        concat_ws(' ', sa.shortcut_ad_id::text, sa.shortcut_ad_url, sa.shortcut_ad_data #>> '{address,formattedAddress}', sa.shortcut_ad_data #>> '{address,city,name}', sa.shortcut_ad_data #>> '{address,zipCode,value}', sa.shortcut_ad_data #>> '{adData,roomConfiguration}', sb.shortcut_building_address, sb.shortcut_building_housing_company) AS searchable
    FROM public.shortcut_ads sa
    LEFT JOIN public.shortcut_buildings sb ON sb.shortcut_building_id = sa.shortcut_building_id
    UNION ALL
    SELECT
        'shortcut'::text AS source,
        'building'::text AS kind,
        NULL::text AS city,
        NULL::text AS postal,
        NULL::bigint AS price,
        0::float8 AS area,
        concat_ws(' ', sb.shortcut_building_id::text, sb.shortcut_building_external_id::text, sb.shortcut_building_url, sb.shortcut_building_address, sb.shortcut_building_housing_company, sb.shortcut_building_building_type, sb.shortcut_building_building_subtype) AS searchable
    FROM public.shortcut_buildings sb
    UNION ALL
    SELECT
        'frontdoor'::text AS source,
        'ad'::text AS kind,
        COALESCE(fa.frontdoor_ad_data #>> '{property,municipality}', fa.frontdoor_ad_data #>> '{property,city}') AS city,
        COALESCE(fa.frontdoor_ad_data #>> '{property,postalCode}', fa.frontdoor_ad_data #>> '{property,addressPostalCode}') AS postal,
        COALESCE(
            NULLIF(regexp_replace(fa.frontdoor_ad_data #>> '{debfFreePrice}', '[^0-9\.-]', '', 'g'), '')::numeric::bigint,
            NULLIF(regexp_replace(fa.frontdoor_ad_data #>> '{preparsed,price}', '[^0-9\.-]', '', 'g'), '')::numeric::bigint
        ) AS price,
        COALESCE(NULLIF(fa.frontdoor_ad_data #>> '{preparsed,area}', '')::float8, 0::float8) AS area,
        concat_ws(' ', fa.frontdoor_ad_external_id, fa.frontdoor_ad_url, fa.frontdoor_ad_data #>> '{property,streetAddressFreeForm}', fa.frontdoor_ad_data #>> '{property,address}', fa.frontdoor_ad_data #>> '{property,municipality}', fa.frontdoor_ad_data #>> '{property,city}', fa.frontdoor_ad_data #>> '{property,postalCode}', fa.frontdoor_ad_data #>> '{residenceDetailsDTO,roomStructure}') AS searchable
    FROM public.frontdoor_ads fa
    UNION ALL
    SELECT
        'frontdoor'::text AS source,
        'announcement'::text AS kind,
        COALESCE(fba.frontdoor_building_announcement_location, fb.frontdoor_building_municipality, fb.frontdoor_building_post_area) AS city,
        fb.frontdoor_building_postcode AS postal,
        CASE WHEN fba.frontdoor_building_announcement_search_price IS NULL THEN NULL ELSE fba.frontdoor_building_announcement_search_price::bigint END AS price,
        COALESCE(fba.frontdoor_building_announcement_area, 0::float8) AS area,
        concat_ws(' ', fba.frontdoor_building_announcement_id::text, fba.frontdoor_building_announcement_external_id::text, fba.frontdoor_building_announcement_friendly_id, fba.frontdoor_building_announcement_address_line1, fba.frontdoor_building_announcement_address_line2, fba.frontdoor_building_announcement_location, fb.frontdoor_building_postcode, fb.frontdoor_building_municipality, fb.frontdoor_building_post_area, fb.frontdoor_building_url, fba.frontdoor_building_announcement_room_structure) AS searchable
    FROM public.frontdoor_building_announcements fba
    JOIN public.frontdoor_buildings fb ON fb.frontdoor_building_id = fba.frontdoor_building_id
    UNION ALL
    SELECT
        'frontdoor'::text AS source,
        'building'::text AS kind,
        COALESCE(fb.frontdoor_building_municipality, fb.frontdoor_building_post_area) AS city,
        fb.frontdoor_building_postcode AS postal,
        NULL::bigint AS price,
        0::float8 AS area,
        concat_ws(' ', fb.frontdoor_building_id::text, fb.frontdoor_building_url, fb.frontdoor_building_housing_company_id::text, fb.frontdoor_building_housing_company_friendly_id, fb.frontdoor_building_company_name, fb.frontdoor_building_street_address, fb.frontdoor_building_house_number, fb.frontdoor_building_postcode, fb.frontdoor_building_post_area, fb.frontdoor_building_municipality) AS searchable
    FROM public.frontdoor_buildings fb
)
SELECT COUNT(*)::bigint AS count
FROM unified u
WHERE ($1 = 'all' OR u.source = $1)
  AND ($2 = 'all' OR u.kind = $2)
  AND ($3::text IS NULL OR trim($3::text) = '' OR lower(u.searchable) LIKE ('%' || lower(trim($3::text)) || '%'))
  AND ($4::text IS NULL OR trim($4::text) = '' OR lower(COALESCE(u.city, '')) LIKE ('%' || lower(trim($4::text)) || '%'))
  AND ($5::text IS NULL OR trim($5::text) = '' OR lower(COALESCE(u.postal, '')) LIKE ('%' || lower(trim($5::text)) || '%'))
  AND ($6::bigint IS NULL OR u.price >= $6::bigint)
  AND ($7::bigint IS NULL OR u.price <= $7::bigint)
  AND ($8::float8 IS NULL OR u.area >= $8::float8)
  AND ($9::float8 IS NULL OR u.area <= $9::float8)
`

type CountUnifiedEntitiesParams struct {
	SourceFilter *string  `db:"source_filter" json:"source_filter"`
	KindFilter   *string  `db:"kind_filter" json:"kind_filter"`
	QueryText    *string  `db:"query_text" json:"query_text"`
	CityFilter   *string  `db:"city_filter" json:"city_filter"`
	PostalFilter *string  `db:"postal_filter" json:"postal_filter"`
	MinPrice     *int64   `db:"min_price" json:"min_price"`
	MaxPrice     *int64   `db:"max_price" json:"max_price"`
	MinArea      *float64 `db:"min_area" json:"min_area"`
	MaxArea      *float64 `db:"max_area" json:"max_area"`
}

func (q *Queries) CountUnifiedEntities(ctx context.Context, arg *CountUnifiedEntitiesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnifiedEntities,
		arg.SourceFilter,
		arg.KindFilter,
		arg.QueryText,
		arg.CityFilter,
		arg.PostalFilter,
		arg.MinPrice,
		arg.MaxPrice,
		arg.MinArea,
		arg.MaxArea,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFrontdoorAdUnifiedDetail = `-- name: GetFrontdoorAdUnifiedDetail :one
SELECT
    fa.frontdoor_ad_id,
    fa.frontdoor_ad_external_id,
    fa.frontdoor_ad_url,
    fa.frontdoor_ad_last_seen_at,
    fa.frontdoor_ad_page_not_found,
    fa.frontdoor_ad_data #>> '{property,streetAddressFreeForm}' AS ad_address,
    COALESCE(fa.frontdoor_ad_data #>> '{property,municipality}', fa.frontdoor_ad_data #>> '{property,city}') AS ad_city,
    COALESCE(fa.frontdoor_ad_data #>> '{property,postalCode}', fa.frontdoor_ad_data #>> '{property,addressPostalCode}') AS ad_postal,
    COALESCE(
        NULLIF(regexp_replace(fa.frontdoor_ad_data #>> '{debfFreePrice}', '[^0-9\.-]', '', 'g'), '')::numeric::bigint,
        NULLIF(regexp_replace(fa.frontdoor_ad_data #>> '{preparsed,price}', '[^0-9\.-]', '', 'g'), '')::numeric::bigint
    ) AS ad_price,
    COALESCE(NULLIF(fa.frontdoor_ad_data #>> '{preparsed,area}', '')::float8, 0::float8) AS ad_area,
    fa.frontdoor_ad_data #>> '{residenceDetailsDTO,roomStructure}' AS ad_room_layout,
    fa.frontdoor_ad_data #>> '{property,apartmentType}' AS ad_property_type,
    fa.frontdoor_ad_data #>> '{property,condition}' AS ad_condition,
    fa.frontdoor_ad_data
FROM public.frontdoor_ads fa
WHERE fa.frontdoor_ad_external_id = $1
LIMIT 1
`

type GetFrontdoorAdUnifiedDetailRow struct {
	FrontdoorAdID           pgtype.UUID        `db:"frontdoor_ad_id" json:"frontdoor_ad_id"`
	FrontdoorAdExternalID   string             `db:"frontdoor_ad_external_id" json:"frontdoor_ad_external_id"`
	FrontdoorAdUrl          string             `db:"frontdoor_ad_url" json:"frontdoor_ad_url"`
	FrontdoorAdLastSeenAt   pgtype.Timestamptz `db:"frontdoor_ad_last_seen_at" json:"frontdoor_ad_last_seen_at"`
	FrontdoorAdPageNotFound bool               `db:"frontdoor_ad_page_not_found" json:"frontdoor_ad_page_not_found"`
	AdAddress               *string            `db:"ad_address" json:"ad_address"`
	AdCity                  *string            `db:"ad_city" json:"ad_city"`
	AdPostal                *string            `db:"ad_postal" json:"ad_postal"`
	AdPrice                 pgtype.Int8        `db:"ad_price" json:"ad_price"`
	AdArea                  pgtype.Float8      `db:"ad_area" json:"ad_area"`
	AdRoomLayout            *string            `db:"ad_room_layout" json:"ad_room_layout"`
	AdPropertyType          *string            `db:"ad_property_type" json:"ad_property_type"`
	AdCondition             *string            `db:"ad_condition" json:"ad_condition"`
	FrontdoorAdData         []byte             `db:"frontdoor_ad_data" json:"frontdoor_ad_data"`
}

func (q *Queries) GetFrontdoorAdUnifiedDetail(ctx context.Context, externalID string) (GetFrontdoorAdUnifiedDetailRow, error) {
	row := q.db.QueryRow(ctx, getFrontdoorAdUnifiedDetail, externalID)
	var i GetFrontdoorAdUnifiedDetailRow
	err := row.Scan(
		&i.FrontdoorAdID,
		&i.FrontdoorAdExternalID,
		&i.FrontdoorAdUrl,
		&i.FrontdoorAdLastSeenAt,
		&i.FrontdoorAdPageNotFound,
		&i.AdAddress,
		&i.AdCity,
		&i.AdPostal,
		&i.AdPrice,
		&i.AdArea,
		&i.AdRoomLayout,
		&i.AdPropertyType,
		&i.AdCondition,
		&i.FrontdoorAdData,
	)
	return i, err
}

const getFrontdoorAnnouncementUnifiedDetail = `-- name: GetFrontdoorAnnouncementUnifiedDetail :one
SELECT
    fba.frontdoor_building_announcement_id,
    fba.frontdoor_building_announcement_external_id,
    fba.frontdoor_building_announcement_friendly_id,
    fba.frontdoor_building_announcement_last_seen_at,
    fba.frontdoor_building_announcement_address_line1,
    fba.frontdoor_building_announcement_address_line2,
    fba.frontdoor_building_announcement_location,
    fba.frontdoor_building_announcement_search_price,
    fba.frontdoor_building_announcement_area,
    fba.frontdoor_building_announcement_room_structure,
    fba.frontdoor_building_announcement_property_type,
    fba.frontdoor_building_announcement_property_subtype,
    fba.frontdoor_building_announcement_published,
    fb.frontdoor_building_id,
    fb.frontdoor_building_url,
    fb.frontdoor_building_housing_company_id,
    fb.frontdoor_building_housing_company_friendly_id,
    fb.frontdoor_building_company_name,
    fb.frontdoor_building_street_address,
    fb.frontdoor_building_house_number,
    fb.frontdoor_building_postcode,
    fb.frontdoor_building_post_area,
    fb.frontdoor_building_municipality,
    jsonb_build_object(
        'announcement_id', fba.frontdoor_building_announcement_id,
        'external_id', fba.frontdoor_building_announcement_external_id,
        'friendly_id', fba.frontdoor_building_announcement_friendly_id,
        'address_line1', fba.frontdoor_building_announcement_address_line1,
        'address_line2', fba.frontdoor_building_announcement_address_line2,
        'location', fba.frontdoor_building_announcement_location,
        'search_price', fba.frontdoor_building_announcement_search_price,
        'area', fba.frontdoor_building_announcement_area,
        'room_structure', fba.frontdoor_building_announcement_room_structure,
        'property_type', fba.frontdoor_building_announcement_property_type,
        'property_subtype', fba.frontdoor_building_announcement_property_subtype,
        'published', fba.frontdoor_building_announcement_published,
        'building', jsonb_build_object(
            'building_id', fb.frontdoor_building_id,
            'building_url', fb.frontdoor_building_url,
            'housing_company_id', fb.frontdoor_building_housing_company_id,
            'housing_company_friendly_id', fb.frontdoor_building_housing_company_friendly_id,
            'company_name', fb.frontdoor_building_company_name,
            'street_address', fb.frontdoor_building_street_address,
            'house_number', fb.frontdoor_building_house_number,
            'postcode', fb.frontdoor_building_postcode,
            'post_area', fb.frontdoor_building_post_area,
            'municipality', fb.frontdoor_building_municipality
        )
    ) AS raw_json
FROM public.frontdoor_building_announcements fba
JOIN public.frontdoor_buildings fb ON fb.frontdoor_building_id = fba.frontdoor_building_id
WHERE fba.frontdoor_building_announcement_id = $1
LIMIT 1
`

type GetFrontdoorAnnouncementUnifiedDetailRow struct {
	FrontdoorBuildingAnnouncementID              pgtype.UUID        `db:"frontdoor_building_announcement_id" json:"frontdoor_building_announcement_id"`
	FrontdoorBuildingAnnouncementExternalID      *int32             `db:"frontdoor_building_announcement_external_id" json:"frontdoor_building_announcement_external_id"`
	FrontdoorBuildingAnnouncementFriendlyID      *string            `db:"frontdoor_building_announcement_friendly_id" json:"frontdoor_building_announcement_friendly_id"`
	FrontdoorBuildingAnnouncementLastSeenAt      pgtype.Timestamptz `db:"frontdoor_building_announcement_last_seen_at" json:"frontdoor_building_announcement_last_seen_at"`
	FrontdoorBuildingAnnouncementAddressLine1    *string            `db:"frontdoor_building_announcement_address_line1" json:"frontdoor_building_announcement_address_line1"`
	FrontdoorBuildingAnnouncementAddressLine2    *string            `db:"frontdoor_building_announcement_address_line2" json:"frontdoor_building_announcement_address_line2"`
	FrontdoorBuildingAnnouncementLocation        *string            `db:"frontdoor_building_announcement_location" json:"frontdoor_building_announcement_location"`
	FrontdoorBuildingAnnouncementSearchPrice     *float64           `db:"frontdoor_building_announcement_search_price" json:"frontdoor_building_announcement_search_price"`
	FrontdoorBuildingAnnouncementArea            *float64           `db:"frontdoor_building_announcement_area" json:"frontdoor_building_announcement_area"`
	FrontdoorBuildingAnnouncementRoomStructure   *string            `db:"frontdoor_building_announcement_room_structure" json:"frontdoor_building_announcement_room_structure"`
	FrontdoorBuildingAnnouncementPropertyType    *string            `db:"frontdoor_building_announcement_property_type" json:"frontdoor_building_announcement_property_type"`
	FrontdoorBuildingAnnouncementPropertySubtype *string            `db:"frontdoor_building_announcement_property_subtype" json:"frontdoor_building_announcement_property_subtype"`
	FrontdoorBuildingAnnouncementPublished       *bool              `db:"frontdoor_building_announcement_published" json:"frontdoor_building_announcement_published"`
	FrontdoorBuildingID                          pgtype.UUID        `db:"frontdoor_building_id" json:"frontdoor_building_id"`
	FrontdoorBuildingUrl                         *string            `db:"frontdoor_building_url" json:"frontdoor_building_url"`
	FrontdoorBuildingHousingCompanyID            pgtype.Int8        `db:"frontdoor_building_housing_company_id" json:"frontdoor_building_housing_company_id"`
	FrontdoorBuildingHousingCompanyFriendlyID    *string            `db:"frontdoor_building_housing_company_friendly_id" json:"frontdoor_building_housing_company_friendly_id"`
	FrontdoorBuildingCompanyName                 *string            `db:"frontdoor_building_company_name" json:"frontdoor_building_company_name"`
	FrontdoorBuildingStreetAddress               *string            `db:"frontdoor_building_street_address" json:"frontdoor_building_street_address"`
	FrontdoorBuildingHouseNumber                 *string            `db:"frontdoor_building_house_number" json:"frontdoor_building_house_number"`
	FrontdoorBuildingPostcode                    *string            `db:"frontdoor_building_postcode" json:"frontdoor_building_postcode"`
	FrontdoorBuildingPostArea                    *string            `db:"frontdoor_building_post_area" json:"frontdoor_building_post_area"`
	FrontdoorBuildingMunicipality                *string            `db:"frontdoor_building_municipality" json:"frontdoor_building_municipality"`
	RawJson                                      json.RawMessage    `db:"raw_json" json:"raw_json"`
}

func (q *Queries) GetFrontdoorAnnouncementUnifiedDetail(ctx context.Context, announcementID pgtype.UUID) (GetFrontdoorAnnouncementUnifiedDetailRow, error) {
	row := q.db.QueryRow(ctx, getFrontdoorAnnouncementUnifiedDetail, announcementID)
	var i GetFrontdoorAnnouncementUnifiedDetailRow
	err := row.Scan(
		&i.FrontdoorBuildingAnnouncementID,
		&i.FrontdoorBuildingAnnouncementExternalID,
		&i.FrontdoorBuildingAnnouncementFriendlyID,
		&i.FrontdoorBuildingAnnouncementLastSeenAt,
		&i.FrontdoorBuildingAnnouncementAddressLine1,
		&i.FrontdoorBuildingAnnouncementAddressLine2,
		&i.FrontdoorBuildingAnnouncementLocation,
		&i.FrontdoorBuildingAnnouncementSearchPrice,
		&i.FrontdoorBuildingAnnouncementArea,
		&i.FrontdoorBuildingAnnouncementRoomStructure,
		&i.FrontdoorBuildingAnnouncementPropertyType,
		&i.FrontdoorBuildingAnnouncementPropertySubtype,
		&i.FrontdoorBuildingAnnouncementPublished,
		&i.FrontdoorBuildingID,
		&i.FrontdoorBuildingUrl,
		&i.FrontdoorBuildingHousingCompanyID,
		&i.FrontdoorBuildingHousingCompanyFriendlyID,
		&i.FrontdoorBuildingCompanyName,
		&i.FrontdoorBuildingStreetAddress,
		&i.FrontdoorBuildingHouseNumber,
		&i.FrontdoorBuildingPostcode,
		&i.FrontdoorBuildingPostArea,
		&i.FrontdoorBuildingMunicipality,
		&i.RawJson,
	)
	return i, err
}

const getFrontdoorBuildingUnifiedDetail = `-- name: GetFrontdoorBuildingUnifiedDetail :one
SELECT
    fb.frontdoor_building_id,
    fb.frontdoor_building_url,
    fb.frontdoor_building_last_seen_at,
    fb.frontdoor_building_company_name,
    fb.frontdoor_building_business_id,
    fb.frontdoor_building_apartment_count,
    fb.frontdoor_building_floor_count,
    fb.frontdoor_building_build_year,
    fb.frontdoor_building_has_elevator,
    fb.frontdoor_building_has_sauna,
    fb.frontdoor_building_energy_certificate_code,
    fb.frontdoor_building_heating,
    fb.frontdoor_building_street_address,
    fb.frontdoor_building_house_number,
    fb.frontdoor_building_postcode,
    fb.frontdoor_building_post_area,
    fb.frontdoor_building_municipality,
    fb.frontdoor_building_latitude,
    fb.frontdoor_building_longitude,
    fb.frontdoor_building_housing_company_id,
    fb.frontdoor_building_housing_company_friendly_id,
    (SELECT COUNT(*)::bigint FROM public.frontdoor_building_announcements fba WHERE fba.frontdoor_building_id = fb.frontdoor_building_id) AS announcement_count,
    fb.frontdoor_building_data
FROM public.frontdoor_buildings fb
WHERE fb.frontdoor_building_id = $1
LIMIT 1
`

type GetFrontdoorBuildingUnifiedDetailRow struct {
	FrontdoorBuildingID                       pgtype.UUID        `db:"frontdoor_building_id" json:"frontdoor_building_id"`
	FrontdoorBuildingUrl                      *string            `db:"frontdoor_building_url" json:"frontdoor_building_url"`
	FrontdoorBuildingLastSeenAt               pgtype.Timestamptz `db:"frontdoor_building_last_seen_at" json:"frontdoor_building_last_seen_at"`
	FrontdoorBuildingCompanyName              *string            `db:"frontdoor_building_company_name" json:"frontdoor_building_company_name"`
	FrontdoorBuildingBusinessID               *string            `db:"frontdoor_building_business_id" json:"frontdoor_building_business_id"`
	FrontdoorBuildingApartmentCount           *int32             `db:"frontdoor_building_apartment_count" json:"frontdoor_building_apartment_count"`
	FrontdoorBuildingFloorCount               *int32             `db:"frontdoor_building_floor_count" json:"frontdoor_building_floor_count"`
	FrontdoorBuildingBuildYear                *int32             `db:"frontdoor_building_build_year" json:"frontdoor_building_build_year"`
	FrontdoorBuildingHasElevator              *bool              `db:"frontdoor_building_has_elevator" json:"frontdoor_building_has_elevator"`
	FrontdoorBuildingHasSauna                 *bool              `db:"frontdoor_building_has_sauna" json:"frontdoor_building_has_sauna"`
	FrontdoorBuildingEnergyCertificateCode    *string            `db:"frontdoor_building_energy_certificate_code" json:"frontdoor_building_energy_certificate_code"`
	FrontdoorBuildingHeating                  *string            `db:"frontdoor_building_heating" json:"frontdoor_building_heating"`
	FrontdoorBuildingStreetAddress            *string            `db:"frontdoor_building_street_address" json:"frontdoor_building_street_address"`
	FrontdoorBuildingHouseNumber              *string            `db:"frontdoor_building_house_number" json:"frontdoor_building_house_number"`
	FrontdoorBuildingPostcode                 *string            `db:"frontdoor_building_postcode" json:"frontdoor_building_postcode"`
	FrontdoorBuildingPostArea                 *string            `db:"frontdoor_building_post_area" json:"frontdoor_building_post_area"`
	FrontdoorBuildingMunicipality             *string            `db:"frontdoor_building_municipality" json:"frontdoor_building_municipality"`
	FrontdoorBuildingLatitude                 *float64           `db:"frontdoor_building_latitude" json:"frontdoor_building_latitude"`
	FrontdoorBuildingLongitude                *float64           `db:"frontdoor_building_longitude" json:"frontdoor_building_longitude"`
	FrontdoorBuildingHousingCompanyID         pgtype.Int8        `db:"frontdoor_building_housing_company_id" json:"frontdoor_building_housing_company_id"`
	FrontdoorBuildingHousingCompanyFriendlyID *string            `db:"frontdoor_building_housing_company_friendly_id" json:"frontdoor_building_housing_company_friendly_id"`
	AnnouncementCount                         int64              `db:"announcement_count" json:"announcement_count"`
	FrontdoorBuildingData                     []byte             `db:"frontdoor_building_data" json:"frontdoor_building_data"`
}

func (q *Queries) GetFrontdoorBuildingUnifiedDetail(ctx context.Context, buildingID pgtype.UUID) (GetFrontdoorBuildingUnifiedDetailRow, error) {
	row := q.db.QueryRow(ctx, getFrontdoorBuildingUnifiedDetail, buildingID)
	var i GetFrontdoorBuildingUnifiedDetailRow
	err := row.Scan(
		&i.FrontdoorBuildingID,
		&i.FrontdoorBuildingUrl,
		&i.FrontdoorBuildingLastSeenAt,
		&i.FrontdoorBuildingCompanyName,
		&i.FrontdoorBuildingBusinessID,
		&i.FrontdoorBuildingApartmentCount,
		&i.FrontdoorBuildingFloorCount,
		&i.FrontdoorBuildingBuildYear,
		&i.FrontdoorBuildingHasElevator,
		&i.FrontdoorBuildingHasSauna,
		&i.FrontdoorBuildingEnergyCertificateCode,
		&i.FrontdoorBuildingHeating,
		&i.FrontdoorBuildingStreetAddress,
		&i.FrontdoorBuildingHouseNumber,
		&i.FrontdoorBuildingPostcode,
		&i.FrontdoorBuildingPostArea,
		&i.FrontdoorBuildingMunicipality,
		&i.FrontdoorBuildingLatitude,
		&i.FrontdoorBuildingLongitude,
		&i.FrontdoorBuildingHousingCompanyID,
		&i.FrontdoorBuildingHousingCompanyFriendlyID,
		&i.AnnouncementCount,
		&i.FrontdoorBuildingData,
	)
	return i, err
}

const getShortcutAdUnifiedDetail = `-- name: GetShortcutAdUnifiedDetail :one
SELECT
    sa.shortcut_ad_id,
    sa.shortcut_ad_url,
    sa.shortcut_ad_type,
    sa.shortcut_ad_last_seen_at,
    sa.shortcut_building_id,
    sa.shortcut_ad_data #>> '{address,formattedAddress}' AS ad_address,
    sa.shortcut_ad_data #>> '{address,city,name}' AS ad_city,
    COALESCE(sa.shortcut_ad_data #>> '{address,zipCode,value}', sa.shortcut_ad_data #>> '{address,zipCode,name}') AS ad_postal,
    sa.shortcut_ad_data #>> '{adData,roomConfiguration}' AS ad_room_layout,
    COALESCE(
        NULLIF(regexp_replace(sa.shortcut_ad_data #>> '{priceData,priceSell}', '[^0-9\.-]', '', 'g'), '')::numeric::bigint,
        NULLIF(regexp_replace(sa.shortcut_ad_data #>> '{priceData,price}', '[^0-9\.-]', '', 'g'), '')::numeric::bigint
    ) AS ad_price,
    COALESCE(NULLIF(sa.shortcut_ad_data #>> '{adData,size}', '')::float8, 0::float8) AS ad_area,
    sa.shortcut_ad_data,
    sb.shortcut_building_external_id,
    sb.shortcut_building_url,
    sb.shortcut_building_address,
    sb.shortcut_building_housing_company,
    (SELECT COUNT(*)::bigint FROM public.shortcut_building_listings sbl WHERE sbl.shortcut_building_id = sb.shortcut_building_id) AS building_listing_count,
    (SELECT COUNT(*)::bigint FROM public.shortcut_building_rentals sbr WHERE sbr.shortcut_building_id = sb.shortcut_building_id) AS building_rental_count
FROM public.shortcut_ads sa
LEFT JOIN public.shortcut_buildings sb ON sb.shortcut_building_id = sa.shortcut_building_id
WHERE sa.shortcut_ad_id = $1
LIMIT 1
`

type GetShortcutAdUnifiedDetailRow struct {
	ShortcutAdID                   int64              `db:"shortcut_ad_id" json:"shortcut_ad_id"`
	ShortcutAdUrl                  string             `db:"shortcut_ad_url" json:"shortcut_ad_url"`
	ShortcutAdType                 string             `db:"shortcut_ad_type" json:"shortcut_ad_type"`
	ShortcutAdLastSeenAt           pgtype.Timestamptz `db:"shortcut_ad_last_seen_at" json:"shortcut_ad_last_seen_at"`
	ShortcutBuildingID             pgtype.UUID        `db:"shortcut_building_id" json:"shortcut_building_id"`
	AdAddress                      *string            `db:"ad_address" json:"ad_address"`
	AdCity                         *string            `db:"ad_city" json:"ad_city"`
	AdPostal                       *string            `db:"ad_postal" json:"ad_postal"`
	AdRoomLayout                   *string            `db:"ad_room_layout" json:"ad_room_layout"`
	AdPrice                        pgtype.Int8        `db:"ad_price" json:"ad_price"`
	AdArea                         pgtype.Float8      `db:"ad_area" json:"ad_area"`
	ShortcutAdData                 []byte             `db:"shortcut_ad_data" json:"shortcut_ad_data"`
	ShortcutBuildingExternalID     pgtype.Int8        `db:"shortcut_building_external_id" json:"shortcut_building_external_id"`
	ShortcutBuildingUrl            *string            `db:"shortcut_building_url" json:"shortcut_building_url"`
	ShortcutBuildingAddress        *string            `db:"shortcut_building_address" json:"shortcut_building_address"`
	ShortcutBuildingHousingCompany *string            `db:"shortcut_building_housing_company" json:"shortcut_building_housing_company"`
	BuildingListingCount           int64              `db:"building_listing_count" json:"building_listing_count"`
	BuildingRentalCount            int64              `db:"building_rental_count" json:"building_rental_count"`
}

func (q *Queries) GetShortcutAdUnifiedDetail(ctx context.Context, adID int64) (GetShortcutAdUnifiedDetailRow, error) {
	row := q.db.QueryRow(ctx, getShortcutAdUnifiedDetail, adID)
	var i GetShortcutAdUnifiedDetailRow
	err := row.Scan(
		&i.ShortcutAdID,
		&i.ShortcutAdUrl,
		&i.ShortcutAdType,
		&i.ShortcutAdLastSeenAt,
		&i.ShortcutBuildingID,
		&i.AdAddress,
		&i.AdCity,
		&i.AdPostal,
		&i.AdRoomLayout,
		&i.AdPrice,
		&i.AdArea,
		&i.ShortcutAdData,
		&i.ShortcutBuildingExternalID,
		&i.ShortcutBuildingUrl,
		&i.ShortcutBuildingAddress,
		&i.ShortcutBuildingHousingCompany,
		&i.BuildingListingCount,
		&i.BuildingRentalCount,
	)
	return i, err
}

const getShortcutBuildingUnifiedDetail = `-- name: GetShortcutBuildingUnifiedDetail :one
SELECT
    sb.shortcut_building_id,
    sb.shortcut_building_external_id,
    sb.shortcut_building_url,
    sb.shortcut_building_address,
    sb.shortcut_building_housing_company,
    sb.shortcut_building_building_type,
    sb.shortcut_building_building_subtype,
    sb.shortcut_building_construction_year,
    sb.shortcut_building_floor_count,
    sb.shortcut_building_apartment_count,
    sb.shortcut_building_heating_system,
    sb.shortcut_building_building_material,
    sb.shortcut_building_plot_type,
    sb.shortcut_building_wall_structure,
    sb.shortcut_building_heat_source,
    sb.shortcut_building_has_elevator,
    sb.shortcut_building_has_sauna,
    sb.shortcut_building_latitude,
    sb.shortcut_building_longitude,
    sb.shortcut_building_updated_at,
    sb.shortcut_building_processed_at,
    sb.shortcut_building_page_not_found,
    (SELECT COUNT(*)::bigint FROM public.shortcut_ads sa WHERE sa.shortcut_building_id = sb.shortcut_building_id) AS ad_count,
    (SELECT COUNT(*)::bigint FROM public.shortcut_building_listings sbl WHERE sbl.shortcut_building_id = sb.shortcut_building_id) AS listing_count,
    (SELECT COUNT(*)::bigint FROM public.shortcut_building_rentals sbr WHERE sbr.shortcut_building_id = sb.shortcut_building_id) AS rental_count,
    jsonb_build_object(
        'building_id', sb.shortcut_building_id,
        'external_id', sb.shortcut_building_external_id,
        'address', sb.shortcut_building_address,
        'housing_company', sb.shortcut_building_housing_company,
        'building_type', sb.shortcut_building_building_type,
        'building_subtype', sb.shortcut_building_building_subtype,
        'construction_year', sb.shortcut_building_construction_year,
        'floor_count', sb.shortcut_building_floor_count,
        'apartment_count', sb.shortcut_building_apartment_count,
        'heating_system', sb.shortcut_building_heating_system,
        'building_material', sb.shortcut_building_building_material,
        'plot_type', sb.shortcut_building_plot_type,
        'wall_structure', sb.shortcut_building_wall_structure,
        'heat_source', sb.shortcut_building_heat_source,
        'has_elevator', sb.shortcut_building_has_elevator,
        'has_sauna', sb.shortcut_building_has_sauna,
        'latitude', sb.shortcut_building_latitude,
        'longitude', sb.shortcut_building_longitude,
        'updated_at', sb.shortcut_building_updated_at,
        'processed_at', sb.shortcut_building_processed_at,
        'page_not_found', sb.shortcut_building_page_not_found
    ) AS raw_json
FROM public.shortcut_buildings sb
WHERE sb.shortcut_building_id = $1
LIMIT 1
`

type GetShortcutBuildingUnifiedDetailRow struct {
	ShortcutBuildingID               pgtype.UUID        `db:"shortcut_building_id" json:"shortcut_building_id"`
	ShortcutBuildingExternalID       int64              `db:"shortcut_building_external_id" json:"shortcut_building_external_id"`
	ShortcutBuildingUrl              string             `db:"shortcut_building_url" json:"shortcut_building_url"`
	ShortcutBuildingAddress          *string            `db:"shortcut_building_address" json:"shortcut_building_address"`
	ShortcutBuildingHousingCompany   *string            `db:"shortcut_building_housing_company" json:"shortcut_building_housing_company"`
	ShortcutBuildingBuildingType     *string            `db:"shortcut_building_building_type" json:"shortcut_building_building_type"`
	ShortcutBuildingBuildingSubtype  *string            `db:"shortcut_building_building_subtype" json:"shortcut_building_building_subtype"`
	ShortcutBuildingConstructionYear *int32             `db:"shortcut_building_construction_year" json:"shortcut_building_construction_year"`
	ShortcutBuildingFloorCount       *int32             `db:"shortcut_building_floor_count" json:"shortcut_building_floor_count"`
	ShortcutBuildingApartmentCount   *int32             `db:"shortcut_building_apartment_count" json:"shortcut_building_apartment_count"`
	ShortcutBuildingHeatingSystem    *string            `db:"shortcut_building_heating_system" json:"shortcut_building_heating_system"`
	ShortcutBuildingBuildingMaterial *string            `db:"shortcut_building_building_material" json:"shortcut_building_building_material"`
	ShortcutBuildingPlotType         *string            `db:"shortcut_building_plot_type" json:"shortcut_building_plot_type"`
	ShortcutBuildingWallStructure    *string            `db:"shortcut_building_wall_structure" json:"shortcut_building_wall_structure"`
	ShortcutBuildingHeatSource       *string            `db:"shortcut_building_heat_source" json:"shortcut_building_heat_source"`
	ShortcutBuildingHasElevator      *string            `db:"shortcut_building_has_elevator" json:"shortcut_building_has_elevator"`
	ShortcutBuildingHasSauna         *string            `db:"shortcut_building_has_sauna" json:"shortcut_building_has_sauna"`
	ShortcutBuildingLatitude         *float64           `db:"shortcut_building_latitude" json:"shortcut_building_latitude"`
	ShortcutBuildingLongitude        *float64           `db:"shortcut_building_longitude" json:"shortcut_building_longitude"`
	ShortcutBuildingUpdatedAt        pgtype.Timestamptz `db:"shortcut_building_updated_at" json:"shortcut_building_updated_at"`
	ShortcutBuildingProcessedAt      pgtype.Timestamptz `db:"shortcut_building_processed_at" json:"shortcut_building_processed_at"`
	ShortcutBuildingPageNotFound     *bool              `db:"shortcut_building_page_not_found" json:"shortcut_building_page_not_found"`
	AdCount                          int64              `db:"ad_count" json:"ad_count"`
	ListingCount                     int64              `db:"listing_count" json:"listing_count"`
	RentalCount                      int64              `db:"rental_count" json:"rental_count"`
	RawJson                          json.RawMessage    `db:"raw_json" json:"raw_json"`
}

func (q *Queries) GetShortcutBuildingUnifiedDetail(ctx context.Context, buildingID pgtype.UUID) (GetShortcutBuildingUnifiedDetailRow, error) {
	row := q.db.QueryRow(ctx, getShortcutBuildingUnifiedDetail, buildingID)
	var i GetShortcutBuildingUnifiedDetailRow
	err := row.Scan(
		&i.ShortcutBuildingID,
		&i.ShortcutBuildingExternalID,
		&i.ShortcutBuildingUrl,
		&i.ShortcutBuildingAddress,
		&i.ShortcutBuildingHousingCompany,
		&i.ShortcutBuildingBuildingType,
		&i.ShortcutBuildingBuildingSubtype,
		&i.ShortcutBuildingConstructionYear,
		&i.ShortcutBuildingFloorCount,
		&i.ShortcutBuildingApartmentCount,
		&i.ShortcutBuildingHeatingSystem,
		&i.ShortcutBuildingBuildingMaterial,
		&i.ShortcutBuildingPlotType,
		&i.ShortcutBuildingWallStructure,
		&i.ShortcutBuildingHeatSource,
		&i.ShortcutBuildingHasElevator,
		&i.ShortcutBuildingHasSauna,
		&i.ShortcutBuildingLatitude,
		&i.ShortcutBuildingLongitude,
		&i.ShortcutBuildingUpdatedAt,
		&i.ShortcutBuildingProcessedAt,
		&i.ShortcutBuildingPageNotFound,
		&i.AdCount,
		&i.ListingCount,
		&i.RentalCount,
		&i.RawJson,
	)
	return i, err
}

const searchUnifiedEntities = `-- name: SearchUnifiedEntities :many
WITH unified AS (
    SELECT
        'shortcut'::text AS source,
        'ad'::text AS kind,
        sa.shortcut_ad_id::text AS native_id,
        ('shortcut:ad:' || sa.shortcut_ad_id::text) AS canonical_id,
        COALESCE(sa.shortcut_ad_data #>> '{address,formattedAddress}', sb.shortcut_building_address, sa.shortcut_ad_id::text) AS headline,
        COALESCE(sa.shortcut_ad_data #>> '{address,formattedAddress}', sb.shortcut_building_address) AS address,
        COALESCE(sa.shortcut_ad_data #>> '{address,city,name}', sa.shortcut_ad_data #>> '{address,city}') AS city,
        COALESCE(sa.shortcut_ad_data #>> '{address,zipCode,value}', sa.shortcut_ad_data #>> '{address,zipCode,name}') AS postal,
        COALESCE(
            NULLIF(regexp_replace(sa.shortcut_ad_data #>> '{priceData,priceSell}', '[^0-9\.-]', '', 'g'), '')::numeric::bigint,
            NULLIF(regexp_replace(sa.shortcut_ad_data #>> '{priceData,price}', '[^0-9\.-]', '', 'g'), '')::numeric::bigint
        ) AS price,
        COALESCE(NULLIF(sa.shortcut_ad_data #>> '{adData,size}', '')::float8, 0::float8) AS area,
        sa.shortcut_ad_data #>> '{adData,roomConfiguration}' AS room_layout,
        sa.shortcut_ad_url AS url,
        sa.shortcut_ad_last_seen_at AS last_seen_at,
        concat_ws(' ', sa.shortcut_ad_id::text, sa.shortcut_ad_url, sa.shortcut_ad_data #>> '{address,formattedAddress}', sa.shortcut_ad_data #>> '{address,city,name}', sa.shortcut_ad_data #>> '{address,zipCode,value}', sa.shortcut_ad_data #>> '{adData,roomConfiguration}', sb.shortcut_building_address, sb.shortcut_building_housing_company) AS searchable
    FROM public.shortcut_ads sa
    LEFT JOIN public.shortcut_buildings sb ON sb.shortcut_building_id = sa.shortcut_building_id
    UNION ALL
    SELECT
        'shortcut'::text AS source,
        'building'::text AS kind,
        sb.shortcut_building_id::text AS native_id,
        ('shortcut:building:' || sb.shortcut_building_id::text) AS canonical_id,
        COALESCE(sb.shortcut_building_address, sb.shortcut_building_housing_company, sb.shortcut_building_external_id::text) AS headline,
        sb.shortcut_building_address AS address,
        NULL::text AS city,
        NULL::text AS postal,
        NULL::bigint AS price,
        0::float8 AS area,
        NULL::text AS room_layout,
        sb.shortcut_building_url AS url,
        COALESCE(sb.shortcut_building_updated_at, sb.shortcut_building_processed_at, now()) AS last_seen_at,
        concat_ws(' ', sb.shortcut_building_id::text, sb.shortcut_building_external_id::text, sb.shortcut_building_url, sb.shortcut_building_address, sb.shortcut_building_housing_company, sb.shortcut_building_building_type, sb.shortcut_building_building_subtype) AS searchable
    FROM public.shortcut_buildings sb
    UNION ALL
    SELECT
        'frontdoor'::text AS source,
        'ad'::text AS kind,
        fa.frontdoor_ad_external_id AS native_id,
        ('frontdoor:ad:' || fa.frontdoor_ad_external_id) AS canonical_id,
        COALESCE(fa.frontdoor_ad_data #>> '{property,streetAddressFreeForm}', fa.frontdoor_ad_data #>> '{property,address}', fa.frontdoor_ad_external_id) AS headline,
        COALESCE(fa.frontdoor_ad_data #>> '{property,streetAddressFreeForm}', fa.frontdoor_ad_data #>> '{property,address}') AS address,
        COALESCE(fa.frontdoor_ad_data #>> '{property,municipality}', fa.frontdoor_ad_data #>> '{property,city}') AS city,
        COALESCE(fa.frontdoor_ad_data #>> '{property,postalCode}', fa.frontdoor_ad_data #>> '{property,addressPostalCode}') AS postal,
        COALESCE(
            NULLIF(regexp_replace(fa.frontdoor_ad_data #>> '{debfFreePrice}', '[^0-9\.-]', '', 'g'), '')::numeric::bigint,
            NULLIF(regexp_replace(fa.frontdoor_ad_data #>> '{preparsed,price}', '[^0-9\.-]', '', 'g'), '')::numeric::bigint
        ) AS price,
        COALESCE(NULLIF(fa.frontdoor_ad_data #>> '{preparsed,area}', '')::float8, 0::float8) AS area,
        fa.frontdoor_ad_data #>> '{residenceDetailsDTO,roomStructure}' AS room_layout,
        fa.frontdoor_ad_url AS url,
        fa.frontdoor_ad_last_seen_at AS last_seen_at,
        concat_ws(' ', fa.frontdoor_ad_external_id, fa.frontdoor_ad_url, fa.frontdoor_ad_data #>> '{property,streetAddressFreeForm}', fa.frontdoor_ad_data #>> '{property,address}', fa.frontdoor_ad_data #>> '{property,municipality}', fa.frontdoor_ad_data #>> '{property,city}', fa.frontdoor_ad_data #>> '{property,postalCode}', fa.frontdoor_ad_data #>> '{residenceDetailsDTO,roomStructure}') AS searchable
    FROM public.frontdoor_ads fa
    UNION ALL
    SELECT
        'frontdoor'::text AS source,
        'announcement'::text AS kind,
        fba.frontdoor_building_announcement_id::text AS native_id,
        ('frontdoor:announcement:' || fba.frontdoor_building_announcement_id::text) AS canonical_id,
        COALESCE(fba.frontdoor_building_announcement_address_line1, fba.frontdoor_building_announcement_friendly_id, fba.frontdoor_building_announcement_external_id::text, fba.frontdoor_building_announcement_id::text) AS headline,
        concat_ws(' ', fba.frontdoor_building_announcement_address_line1, fba.frontdoor_building_announcement_address_line2) AS address,
        COALESCE(fba.frontdoor_building_announcement_location, fb.frontdoor_building_municipality, fb.frontdoor_building_post_area) AS city,
        fb.frontdoor_building_postcode AS postal,
        CASE WHEN fba.frontdoor_building_announcement_search_price IS NULL THEN NULL ELSE fba.frontdoor_building_announcement_search_price::bigint END AS price,
        COALESCE(fba.frontdoor_building_announcement_area, 0::float8) AS area,
        fba.frontdoor_building_announcement_room_structure AS room_layout,
        fb.frontdoor_building_url AS url,
        fba.frontdoor_building_announcement_last_seen_at AS last_seen_at,
        concat_ws(' ', fba.frontdoor_building_announcement_id::text, fba.frontdoor_building_announcement_external_id::text, fba.frontdoor_building_announcement_friendly_id, fba.frontdoor_building_announcement_address_line1, fba.frontdoor_building_announcement_address_line2, fba.frontdoor_building_announcement_location, fb.frontdoor_building_postcode, fb.frontdoor_building_municipality, fb.frontdoor_building_post_area, fb.frontdoor_building_url, fba.frontdoor_building_announcement_room_structure) AS searchable
    FROM public.frontdoor_building_announcements fba
    JOIN public.frontdoor_buildings fb ON fb.frontdoor_building_id = fba.frontdoor_building_id
    UNION ALL
    SELECT
        'frontdoor'::text AS source,
        'building'::text AS kind,
        fb.frontdoor_building_id::text AS native_id,
        ('frontdoor:building:' || fb.frontdoor_building_id::text) AS canonical_id,
        COALESCE(fb.frontdoor_building_company_name, concat_ws(' ', fb.frontdoor_building_street_address, fb.frontdoor_building_house_number), fb.frontdoor_building_housing_company_friendly_id, fb.frontdoor_building_housing_company_id::text, fb.frontdoor_building_id::text) AS headline,
        concat_ws(' ', fb.frontdoor_building_street_address, fb.frontdoor_building_house_number) AS address,
        COALESCE(fb.frontdoor_building_municipality, fb.frontdoor_building_post_area) AS city,
        fb.frontdoor_building_postcode AS postal,
        NULL::bigint AS price,
        0::float8 AS area,
        NULL::text AS room_layout,
        fb.frontdoor_building_url AS url,
        COALESCE(fb.frontdoor_building_last_seen_at, now()) AS last_seen_at,
        concat_ws(' ', fb.frontdoor_building_id::text, fb.frontdoor_building_url, fb.frontdoor_building_housing_company_id::text, fb.frontdoor_building_housing_company_friendly_id, fb.frontdoor_building_company_name, fb.frontdoor_building_street_address, fb.frontdoor_building_house_number, fb.frontdoor_building_postcode, fb.frontdoor_building_post_area, fb.frontdoor_building_municipality) AS searchable
    FROM public.frontdoor_buildings fb
), filtered AS (
    SELECT source, kind, native_id, canonical_id, headline, address, city, postal, price, area, room_layout, url, last_seen_at, searchable
    FROM unified u
    WHERE ($4 = 'all' OR u.source = $4)
      AND ($5 = 'all' OR u.kind = $5)
      AND ($6::text IS NULL OR trim($6::text) = '' OR lower(u.searchable) LIKE ('%' || lower(trim($6::text)) || '%'))
      AND ($7::text IS NULL OR trim($7::text) = '' OR lower(COALESCE(u.city, '')) LIKE ('%' || lower(trim($7::text)) || '%'))
      AND ($8::text IS NULL OR trim($8::text) = '' OR lower(COALESCE(u.postal, '')) LIKE ('%' || lower(trim($8::text)) || '%'))
      AND ($9::bigint IS NULL OR u.price >= $9::bigint)
      AND ($10::bigint IS NULL OR u.price <= $10::bigint)
      AND ($11::float8 IS NULL OR u.area >= $11::float8)
      AND ($12::float8 IS NULL OR u.area <= $12::float8)
)
SELECT
    source,
    kind,
    native_id,
    canonical_id,
    headline,
    address,
    city,
    postal,
    price,
    area,
    room_layout,
    url,
    last_seen_at
FROM filtered
ORDER BY
    CASE WHEN $1 = 'price_asc' THEN price END ASC NULLS LAST,
    CASE WHEN $1 = 'price_desc' THEN price END DESC NULLS LAST,
    CASE WHEN $1 = 'area_asc' THEN area END ASC NULLS LAST,
    CASE WHEN $1 = 'area_desc' THEN area END DESC NULLS LAST,
    CASE WHEN $1 = 'seen_desc' THEN last_seen_at END DESC NULLS LAST,
    last_seen_at DESC,
    source,
    kind,
    native_id
LIMIT $3::int
OFFSET $2::int
`

type SearchUnifiedEntitiesParams struct {
	SortMode     *string  `db:"sort_mode" json:"sort_mode"`
	OffsetCount  int32    `db:"offset_count" json:"offset_count"`
	LimitCount   int32    `db:"limit_count" json:"limit_count"`
	SourceFilter *string  `db:"source_filter" json:"source_filter"`
	KindFilter   *string  `db:"kind_filter" json:"kind_filter"`
	QueryText    *string  `db:"query_text" json:"query_text"`
	CityFilter   *string  `db:"city_filter" json:"city_filter"`
	PostalFilter *string  `db:"postal_filter" json:"postal_filter"`
	MinPrice     *int64   `db:"min_price" json:"min_price"`
	MaxPrice     *int64   `db:"max_price" json:"max_price"`
	MinArea      *float64 `db:"min_area" json:"min_area"`
	MaxArea      *float64 `db:"max_area" json:"max_area"`
}

type SearchUnifiedEntitiesRow struct {
	Source      string             `db:"source" json:"source"`
	Kind        string             `db:"kind" json:"kind"`
	NativeID    string             `db:"native_id" json:"native_id"`
	CanonicalID *string            `db:"canonical_id" json:"canonical_id"`
	Headline    *string            `db:"headline" json:"headline"`
	Address     *string            `db:"address" json:"address"`
	City        *string            `db:"city" json:"city"`
	Postal      *string            `db:"postal" json:"postal"`
	Price       pgtype.Int8        `db:"price" json:"price"`
	Area        pgtype.Float8      `db:"area" json:"area"`
	RoomLayout  *string            `db:"room_layout" json:"room_layout"`
	Url         string             `db:"url" json:"url"`
	LastSeenAt  pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
}

func (q *Queries) SearchUnifiedEntities(ctx context.Context, arg *SearchUnifiedEntitiesParams) ([]SearchUnifiedEntitiesRow, error) {
	rows, err := q.db.Query(ctx, searchUnifiedEntities,
		arg.SortMode,
		arg.OffsetCount,
		arg.LimitCount,
		arg.SourceFilter,
		arg.KindFilter,
		arg.QueryText,
		arg.CityFilter,
		arg.PostalFilter,
		arg.MinPrice,
		arg.MaxPrice,
		arg.MinArea,
		arg.MaxArea,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUnifiedEntitiesRow{}
	for rows.Next() {
		var i SearchUnifiedEntitiesRow
		if err := rows.Scan(
			&i.Source,
			&i.Kind,
			&i.NativeID,
			&i.CanonicalID,
			&i.Headline,
			&i.Address,
			&i.City,
			&i.Postal,
			&i.Price,
			&i.Area,
			&i.RoomLayout,
			&i.Url,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
